### ISSUE TITLE
xmlunit does not work with JUnit 5

### ISSUE THREAD

**Issue by ychulovskyy** [xmlunit/xmlunit#106]
xmlunit does not work with JUnit 5.
e.g. XMLAssert extends Assert but Assert doesn't exists in JUnit5. Assertions should be used instead.

**Comment by bodewig** [comment]
you are talking about the legacy module, right?

The legacy module only exists to help people stuck with XMLUnit 1.x. I'd expect people who want t upgrade to JUnit 5 to also use XMLUnit 2.x.

**Comment by ychulovskyy** [comment]
Works for me, closing the issue.
P.S.: It wasn't obvious that there is XmlUnit 2.x because XmlUnit 1.x has another groupId in maven repo https://mvnrepository.com/artifact/xmlunit/xmlunit

**Comment by bodewig** [comment]
I hope it is obvious from http://www.xmlunit.org/ and https://github.com/xmlunit/xmlunit/ though ;-)

**Comment by ychulovskyy** [comment]
Yep, it's obvious from the websites.
But when a team uses Maven version plugin http://www.mojohaus.org/versions-maven-plugin/ it does NOT suggest to migrate to version XmlUnit 2.x

**Comment by bodewig** [comment]
I see.

Since XMLUnit 2.x's API is completely different from the 1.x API I don't necessarily feel this is a bad thing.
