### ISSUE TITLE
NoSuchElementException from CompareMatcher#describeTo(Description)

### ISSUE THREAD

**Issue by chludwig-haufe** [xmlunit/xmlunit#107]
One of our integration tests fails with a `NoSuchElementException` escaping from `CompareMatcher#describeTo(Description)`. We use org.xmlunit:xmlunit-matchers:2.5.0.

 In the debugger, I can see  that the matcher's `diffResult` is `!= null`, but `diffResult.hasDifferences() == false`. Since `describeTo(Description)` only checks for `diffResult == null`, the code flow enters `ComparisonMatcher#firstComparison()` where the subexpression `diffResult.getDifferences().iterator().next()` throws the `NoSuchElementException`.

The fix seems easy: Simply test for `diffResult == null || !diffResult.hasDifferences()` at the beginning of `CompareMatcher#describeTo(Description)`.

**Comment by bodewig** [comment]
Thanks a lot.

Given this hasn't come up before it seems `describeTo` usually isn't invoked if `matches` returns `true`, I wonder what you are doing to trigger this. :-)

Nevertheless this certainly is a bug. It's fixed on a branch of which I intend to cut 2.5.1 during the weekend.

**Comment by chludwig-haufe** [comment]
Thanks.

Since you wondered: I encountered the bug in a rest-assured body check that calls a hierarchy of delegating matchers:
```
// ...
 .body(isDocumentFrom(getRequestTarget())
                .thatMatches(
                    allOf(
                        metadataIsEqualTo(expectedMetaElement),
                        baselineContent(isSimilarTo(baselineControl)),
                        nativeContent(isSimilarTo(nativeControl)))));
```

**Comment by bodewig** [comment]
Thank you. This is a slightly different incarnation of #81 - sorry for not catching the problem back then.

I've published new 2.5.1-SNAPSHOT artifacts if you need the fix before the weekend.

**Comment by bodewig** [comment]
carved out some time today, 2.5.1 has just been released, I'll officially announce it later.

**Comment by chludwig-haufe** [comment]
Great, thanks a lot!
