### ISSUE TITLE
XPath doesn't support single quote escaping

### ISSUE THREAD

**Issue by claussni** [xmlunit/xmlunit#110]
Element with value containing singel quotes cannot be matched using XPath expression even when escaping the single quote.

```
assertThat("<a>b'b</a>", hasXPath("//a[text()='b''b']")); // won't work
assertThat("<a>b'b</a>", hasXPath("//a[text()='b&apos;b']")); // doesn't work either
```

This might be problematic when querying content with mixed quotes.

I'm using `xmlunit-core 2.5.1` and `xmlunit-matchers 2.5.1`.

The specification is not very clear about this: https://www.w3.org/TR/xpath20/#id-literals

> When XPath expressions are embedded in contexts where quotation marks have special significance, such as inside XML attributes, additional escaping may be needed.

This StackOverflow post brought the idea of using ``''`` :
- https://stackoverflow.com/a/12406443

**Comment by bodewig** [comment]
XMLUnit uses the `javax.xml.xpath` under the covers and I don't think it supports XPath 2.0 so doubling the apostrophe isn't going to work. Your link points to the XPath 2.0 spec as well.

Have you tried

```
assertThat("<a>b'b</a>", hasXPath("//a[text()=\"b'b\"]"));
```

If that doesn't work I'm afraid this is a case where Michael Kay's

> if you want the string delimiter in a string literal, you're hosed

from the post you linked, applies. If you want to use XPath 2.0 you are outside of the scope of the JAXP spec and likely need to use an API like Saxon's s9api directly.

**Comment by bodewig** [comment]
just tried it and my suggestion above seems to work.

**Comment by claussni** [comment]
Thanks for the response! I'm afraid changing the quotes will not be sufficient when handling arbitrary data that could contain both kinds of quotes. Seems I'm hosed.

**Comment by claussni** [comment]
So I am hosed when using javax.xml.xpath. That's bad news. Anyway, switching quotes works OK for the unit test: https://github.com/qucosa/qucosa-fcrepo-migration/blob/master/command-migration/src/test/java/org/qucosa/migration/mappings/TitleMappingTest.java#L235
