### ISSUE TITLE
Comparing the values of an element in xml partially

### ISSUE THREAD

**Issue by KiranBolaj** [xmlunit/xmlunit#112]
Hi,

Is there any way to partially compare the values of the xml element?
Ex : 
file1.xml
<node>
    <node1>abc-test</node1>
    <node2>xyz</node2>
    <node3>pqr</mode3>
</node>

file2.xml
<node>
    <node1>mno-test</node1>
    <node2>xyz</node2>
    <node3>pqr</mode3>
</node>

I want to pass the result of the comparison by ignoring the <node1> value but i want to compare the string after '-' in the value of <node1>

Please help me with this.

**Comment by KiranBolaj** [comment]
file1.xml
"<node><node1>abc-test</node1><node2>xyz</node2><node3>pqr</node3></node>"

file2.xml

"<node><node1>mno-test</node1><node2>xyz</node2><node3>pqr</node3></node>

**Comment by bodewig** [comment]
seems to have turned into #113
