### ISSUE TITLE
Feature in Xmlunit to compare the values of elements partially in XML files comparison

### ISSUE THREAD

**Issue by KiranBolaj** [xmlunit/xmlunit#113]
Hi,

Is there any feature in XmlUnit that compare the values of elements partially during XML files comparison?

Let's consider file1.xml

`<node>
     <node1>345-120</node1>
     <node2>567</node2>
</node>`

and file2.xml

`<node>
    <node1>456-123</node1>
    <node2>567</node2>
</node>`

So I want to compare above files, but I want to compare the values of `<node1/>` partially i.e. only the right part of "-". i.e. I will pass the comparison if it is `<node1>345-120</node1>`  in file1.xml and 
                      `<node1>456-120</node1>` in file2.xml. Else I will fail the comparison if it is `<node1>345-120</node1>`  in file1.xml and  `<node1>456-123</node1>` in file2.xml

And I don't care about the left part of "-".

How do I achieve this using XmlUnit?

**Comment by bodewig** [comment]
@KiranBolaj can you please provide example XMLs, probably by putting the XML into fenced blocks - i.e. triple backticks as in

```
<foo/>
```

or use the "insert code <>" symbol of the editor. I'm afraid without a concrete example I don't understand what you are asking.

**Comment by KiranBolaj** [comment]
Hi,

Let's consider file1.xml
`<node><node1>345-120</node1><node2>567></node2></node>`
and file2.xml
`<node><node1>456-123</node1><node2>567></node2></node>`

So I want to compare above files, but I want to compare the values of `<node1/>` partially i.e. only the right part of "-". i.e. I will pass the comparison if it is `<node1>345-120</node1>`  in file1.xml and `<node1>456-120</node1>` in file2.xml.

How do I do this?

**Comment by bodewig** [comment]
The way you can do this is by providing a `DifferenceEvaluator` of your own. Something like

```
class MyDifferenceEvaluator {
    @Override
    public ComparisonResult evaluate(Comparison comparison, ComparisonResult outcome) {
        if (ComparisonType.TEXT_VALUE != comparison.getType()) {
            // doesn't talk about nested text, use original result
            return outcome;
        }
        if (!"node1".equals(comparison.getControlDetails().getTarget() .getParentNode().getLocalName())) {
            // not a child of "node1" - you may want to add extra checks in order to avoid NullPointerException in the chain above
            return outcome;
        }
        if (!"node1".equals(comparison.getTestDetails().getTarget() .getParentNode().getLocalName())) {
            // not a child of "node1" - you may want to add extra checks in order to avoid NullPointerException in the chain above
            return outcome;
        }
        // here we are comparing two nested strings in node1 elements
        String controlText = (String) comparison.getControlDetails().getValue();
        String testText = (String) comparison.getControlDetails().getValue();
        int controlDash = controlText.indexOf('-');
        int testDash = testText.indexOf('-');
        if (controlDash == -1 || controlDash != testDash) {
            // either there is no prefix, or the prefixes are of different length, use original outcome
            return outcome;
        }
        return controlText.substring(0, controlDash).equals(testText.substring(0, testDash))
            ? ComparisonResult.EQUAL : outcome;
    }
}
```

and chain that to the `DifferenceEvanluator` you'd use without that requirement (most likely `DifferenceEvaluators.Default`).

**Comment by KiranBolaj** [comment]
Thank you for the above solution.

**Comment by bodewig** [comment]
so we can close this?

**Comment by KiranBolaj** [comment]
Yes, please

**Comment by bodewig** [comment]
thank you
