### ISSUE TITLE
NodeDetail (custommonkey package), getXpathLocation() issue

### ISSUE THREAD

**Issue by skamtala** [xmlunit/xmlunit#114]
We noticed that getXPathLocation() method of NodeDetail doesn't give the namespace prefix, is there a way to get the name space of each node? 

where as Compaision.Detail has a similar method which gives name space prefix if we attach the NS map using Diff builder. can we achieve the same with custom monkey classes?

**Comment by bodewig** [comment]
No, this is a feature XMLUnit 1.x never had and I really don't want to encourage people using the 1.x API by backporting new features of 2.x.

**Comment by skamtala** [comment]
Thank you for the quick response,
we have a complex xml and i feel like custom monkey api is handling better especially when node sequence is different between the xmls. 

let me start focus on 2.x version which have some conditional element selectors.
once again thank you.

**Comment by bodewig** [comment]
Actually I believe `ElementSelector` and in particular the conditional variant of it are superior to `ElementQualifier`.

If you find something you can do with the 1.x API that seems hard to do with the 2.x API, please don't hesitate opening an enhancement request.

**Comment by skamtala** [comment]
Thank you, may I know how to raise a enhancement request. Basically I want the NS prefix info in the xpath. 
Thank you.

**Comment by bodewig** [comment]
Oh, I thought about an enhancement request for the 2.x API :-)

Just open an issue and maybe attach labels to it. I won't reject an enhancement request for the legacy stuff but am unlikely to implement it myself (but will gladly accept contributions by others).

**Comment by skamtala** [comment]
I overridden the DifferenceEngine to read the NS map and now xpath gives the NS prefix, thanks for your help.
