### ISSUE TITLE
ElementSelectors.byNameAndText doesnt ignore the order of nodes

### ISSUE THREAD

**Issue by merajani** [xmlunit/xmlunit#115]
Hi,

I am quite impressed with the library and its documentation. Thanks for providing all the support. I have seen your issues https://github.com/xmlunit/xmlunit/issues/77 suggesting to use ElementSelectors.byNameAndText  for ignoring the order of elements. 

However if i have XML's something like this, the XMLUnit comparison fails to believe that its the same XML structure. 

XML Control:

```
<root>
<parent><line>
<segment>L</segment>
</line>
<line>
<segment>K</segment>
</line>
<line>
<segment>P</segment>
</line>
</root>

<root>
<parent><line>
<segment>P</segment>
</line>
<line>
<segment>K</segment>
</line>
<line>
<segment>L</segment>
</line>
</root>
```

Here is my code:

Diff myDiff = DiffBuilder.compare(control).withTest(test).checkForSimilar().
                       withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText)).build();
if(myDiff.hasDifferences())
Iterator<Difference> iterator = myDiff.getDifferences().iterator();
while(iterator.hasNext())
Difference diff = iterator.next();
System.out.println(diff.getComparison().toString)
}

Please let me know what am i missing here, essentially these two structures of XML are same in different Line element order. 

Also, I wanted to ignore white space between elements, i have considered using normalizeWhiteSpace and ignoreWhiteSpace API but they essentially remove the spaces from the text content as well. 
Below both XML's are same except element 'line' is in next time for one of the XML structure.
```
<root>
<parent><line>
<segment>L</segment>
</line>
<line>
<segment>K</segment>
</line>
<line>
<segment>P</segment>
</line>
</root>

<root>
<parent>
<line>
<segment>P</segment>
</line>
<line>
<segment>K</segment>
</line>
<line>
<segment>L</segment>
</line>
</root>

```
I really appreciate your help, I spent quite a bit of time figuring this out.

**Comment by bodewig** [comment]
`byNameAndText` is not a silver bullet, neither is any of the other selectors. It always depends on your concrete scenario.

The elements that are out of order in your example are the `line` elements. The thing that identifies matching lines to you is the nested text of the `segment` element nested into the `line` element. `byNamAndText` looks at the name of the element - `line` - which is the same for all of them and the text nested directly into the element - none at all - which is also the same for all of them. This means `byNameAndText` is not the `ElementSelector` you need.

What you need is "when looking at a `line` element, also look at the nested text of the child element named `segment`". One way to state that in XMLUnit is 

```
ElementSelectors.byXPath("./segment", ElementSelectors.byNameAndText)
```

there would be different ways and the `byName` in `byNameAndText` is redundant as the XPath already ensures only `segment` elements are selected, but this is the most convenient way to state it.

You do not want to use this `ElementSelector` for everything. There is no `segment` child in `parent` for example, so you need different `ElementSelector`s for different parts of your document. This is where conditional selectors come in. For simplicity I will assume that matching on element name is good enough for all elements that are not `line` elements. At least this is true for your example. If you need more complex decisions, then the conditional builder should provide you with everything needed as well. For the simplistic case the solution would be

```
ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("line")
    .thenUse(ElementSelectors.byXPath("./segment", ElementSelectors.byNameAndText))
    .elseUse(ElementSelectors.byName)
    .build();
```

**Comment by merajani** [comment]
Thanks a lot for the prompt response.
yes, my xml is very complication but simplicity I tried the following solution  for the XML structure below. But still xmlUnit is identifies them as two different structures. 

[<root>
<parent><line>
<segment>L</segment>
</line>
<line>
<segment>K</segment>
</line>
<line>
<segment>P</segment>
</line>
</root>

<root>
<parent><line>
<segment>P</segment>
</line>
<line>
<segment>K</segment>
</line>
<line>
<segment>L</segment>
</line>
</root>](url)

Fails with the following error:

Expected text value 'L' but was 'P' - comparing <segment>L</Segment> at /root[1]...
Expected text value 'P' but was 'L' - comparing <segment>P</Segment> at /root[1]...

Please let me know if i am missing anything here.

**Comment by merajani** [comment]
Thank you so much for the prompt reply. The solution above worked for me.


Also, I wanted to ignore white space between elements, i have considered using normalizeWhiteSpace and ignoreWhiteSpace API but they essentially remove the spaces from the text content as well. 
Below both XML's are same except element 'line' is in next time for one of the XML structure.
```
<root>
<parent><line>
<segment>L</segment>
</line>
<line>
<segment>K</segment>
</line>
<line>
<segment>P</segment>
</line>
</root>

<root>
<parent>
<line>
<segment>P</segment>
</line>
<line>
<segment>K</segment>
</line>
<line>
<segment>L</segment>
</line>
</root>

**Comment by merajani** [comment]
Thanks for all your time and really clear explanation with a solution. 

I have a few questions here:

1) I wanted to understand this specific behavior. Following are the 2 XML structures

```
Control:
<root>
<parent>
<line>
<segment>L</segment>
<ID>1</ID>
</line>
<line>
<segment>K</segment>
<ID>3</ID>
</line>
<line>
<segment>P</segment>
<ID>2</ID>
</line>
</parent>
</root>

Test:
<root>
<parent>
<line>
<segment>P</segment>
<ID>2</ID>
</line>
<line>
<segment>K</segment>
<ID>3</ID>
</line>
<line>
<segment>L</segment>
<ID>1</ID>
</line>
</parent>
</root>
```

Here the` 'line' `element, and it has nested text of the child element named segment and `ID`. One way to state that in XMLUnit is following to compare `'segment'` XML elements with same name and text. But when i am doing the following its comparing XML element `'ID'` by its name and text as well.  So the XML structures above are treated as same by XMLUnit which is great, but i wanted to understand how its internally dealing with the XML element `'ID' `since i have NOT defined XPath and ElementSelector for it.
```

ElementSelectors.byXPath("./segment", ElementSelectors.byNameAndText)

 Diff myDiff = DiffBuilder.compare(legacy).withTest(aws)
                .checkForSimilar()
                .withNodeMatcher(new DefaultNodeMatcher(
                        ElementSelectors.conditionalBuilder()
                        .whenElementIsNamed("Line").thenUse(ElementSelectors.byXPath("./segment", ElementSelectors.byNameAndText))
                        .elseUse(ElementSelectors.byNameAndText).build())).build();
```


My original XML is more complicated so i wanted to make sure i have it all covered.

E.g. Original XML is really huge with many children, i have shortened version of it below

```
<s5:Files xmlns:s5="example">
<Report><Enabled>true</Enabled>
<Information><MiddleName></MiddleName>
<FirstName>John</FirstName>
<LastName>Ricardo</LastName>
<Suffix></Suffix>
</Information>
<Lines><Line><ID>2</ID>
<FullName>Robert</FullName>
<Segment>P</Segment>
<History><Date>2017-06-01</Date>
<Days>25</Days>
</History>
<History><Date>2017-05-01</Date>
<Days>25</Days>
</History>
</Line>
<Line><ID>3</ID>
<FullName>Kim</FullName>
<History><Date>2017-06-01</Date>
<Days>257</Days>
</History>
<History><Date>2017-05-01</Date>
<Days>257</Days>
</History>
<Segment>PM</Segment>
</Line>
</Lines>
</Report>
<Report><Enabled>false</Enabled>
<Information><MiddleName></MiddleName>
<FirstName>Jen</FirstName>
<LastName>Mer</LastName>
<Suffix></Suffix>
</Information>
<Lines><Line><ID>2</ID>
<FullName>Padman</FullName>
<Segment>PO</Segment>
<History><Date>2017-06-01</Date>
<Days>25</Days>
</History>
<History><Date>2017-05-01</Date>
<Days>25</Days>
</History>
</Line>
<Line><ID>3</ID>
<FullName>Lorenz</FullName>
<History><Date>2017-06-01</Date>
<Days>257</Days>
</History>
<History><Date>2017-05-01</Date>
<Days>257</Days>
</History>
<Segment>KM</Segment>
</Line>
</Lines>
</Report>
</s5:Files>
```

My second Question
2) The text in these elements is NPI sensitive data so i cannot log the difference nor i can view the real text. So when the 2 XML structures are compared and the elements which fail to match needs to only log the XML element but not the text associated. When i have textByName as element selector the logs are printed like this, I am trying to understand different ways to customize printing the output. Please let me know.

```
Expected child 'ID' but was 'null' - comparing <ID...> at /root[1]/parent[1]/line[1]/ID[1] to <NULL>=>DIFFERENT
Expected child 'null' but was 'ID' - comparing <NULL> to <ID...> at /root[1]/parent[1]/line[3]/ID[1]=>DIFFERENT
```

**Comment by bodewig** [comment]
WRT to element content whitespace you may need to do something yourself, you can take a look at `Nodes.stripWhitespace` for inspiration. You are correct, `ignoreWhitespace` would be close but is mixing two concerns. It might be a good enhancement to have an alternative `stripEmptyTextNodes` that only dealt with element content whitespace.

Next to the `ID` elements: You need to understand that XMLUnit really only looks at a single set of sibling elements at a time and once it has decided which branches of the documents it descends it is never going to look into the other branches. The `byXPath/byNameAndText` combo has been used to select the matching `line` elements. It does not affect the selection of `segment` or `ID` elements at all. Once XMLUnit has settled on the `line` elements to compare there are two child elements in each of them, one is called `segment`, the other `ID` and the `ElementSelector` to use is `byName` (this is what we told XMLUnit to use by default). The is no ambiguity at all. There is no magic that selects the correct `ID` elements, they just happen to be the only choices once XMLUnit has selected the `line` elements.

XMLUnit always compares nested text, the `ElementSelector` is only there to decide which elements to compare with each other, but XMLUnit will always perform all comparisons you find in the `ComparisonType` enum.

For the final question you may want to implement a custom `ComparisonFormatter`. `DefaultComparisonFormatter` may be a good starting point when you only need to override the display of nested text by replacing `appendText`.

**Comment by merajani** [comment]
Thank you so much for all the details, this explanation is very helpful.

**Comment by bodewig** [comment]
you're welcome.

Is there anything I should carry over to the docs to make things clearer? If not, can we close this issue?

**Comment by merajani** [comment]
The explanation and information you provided regarding byXPath/byNameAndText combo was extremely informative. This description  would add huge value to the XPath ElementSelector documentation. 

I also have an additional question..

1) How do i discard namespace during the comparison. Both the files are same but the root i..e Files has a different namespace which is leading to failure during the comparison of the Files.
Expected child '{LFiles}ImpFiles' but was 'null' - comparing <mp5:Files...> at /Files[1] to <NULL>=>DIFFERENT
Expected child 'null' but was '{LFiles}ImpFiles' - comparing <NULL> to <mp3:Files...> at /LFiles[1]=>DIFFERENT

2) As you mentioned about the inspiration of Nodes.stripWhitespace, If i  extend the Nodes.java class  e.g CustomNode with stripEmptyTextNodes functionaly. How do i set the extended CustomNode to be used by the library. Please let me know.

Thanks in Advance.

**Comment by bodewig** [comment]
I'll try to see what of what I've written isn't already part of https://github.com/xmlunit/user-guide/wiki/SelectingNodes - sometimes it is hard to know which detail is missing when you know the concepts too well.

For your first question, most likely it is not only the root element that's in a different namespace but all the elements. From an XML point of view two elements `foo` with two different namespace URIs are two entirely different things, that's why XMLUnit considers the difference significant. You will need to provide a `DifferenceEvaluator` of your own that downgrades `ComparisonType.NAMESPACE_URI` differences to `SIMILAR` or even `EQUAL`. Something like

```
DifferenceEvaluatos.chain(DifferenceEvaluators.Default,
    DifferenceEvaluators.downgradeDifferencesToSimilar(ComparisonType.NAMESPACE_URI))
```

may do.

If `Nodes.stripEmptyTextNodes` returns a `Node` like `stripWhitespace` does, then you can construct a new `DOMSource` from that `Node` and use it as input. See `WhitespaceStrippedSource` for something similar that hides the `stripWhitespace` invocation completely.

**Comment by bodewig** [comment]
Does this answer all questions now and we can close the issue?

**Comment by merajani** [comment]
Thanks for the indepth answers, I would really appreciate if i get some more clarity around this before closing this, thanks for your time and details..

1) If i have to implement a custom WhitespaceStrippedTextNodeSource  similar to WhitespaceStrippedSource. How do i pass this to the DiffBuilder?

public class WhitespaceStrippedTextNodeSource  extends DOMSource {


    public WhitespaceStrippedTextNodeSource  (Source originalSource) {
        super(Nodes.stripEmptyTextNodes (Convert.toDocument(originalSource)));
        setSystemId(originalSource.getSystemId());
    }

  
    public WhitespaceStrippedSource(Source originalSource,
                                    DocumentBuilderFactory dbf) {
        super(Nodes.stripEmptyTextNodes (Convert.toDocument(originalSource, dbf)));
        setSystemId(originalSource.getSystemId());
    }
}

2) Do i need to change the existing code of org.xmlunit.util.Nodes class to implement stripEmptyTextNodes in it, since its a final class i cant extend it in my codebase.

Here is my implementation, but i am unclear how to extend implementation of Nodes with stripEmptyTextNodes.

 public static Node stripEmptyTextNodes (Node original) {
        Node cloned = original.cloneNode(true);
        cloned.normalize();
         return cloned;
    }

Pretty lost, please let me know..

**Comment by bodewig** [comment]
Assuming your goal is to keep everything in your own code base there is no real reason to add the method to the `Nodes` class at all, I'd probably just put it into `WhitespaceStrippedTextNodeSource`.

In order to use your custom `Source` implementation you use it when calling the `compare` or `withTest` methods.

```java
Source whatYouUsedToUseWhenCallingCompare = InputBuilder.....build();
Diff d = DiffBuilder.conpare(new WhitespaceStrippedTextNodeSource(whatYouUsedToUseWhenCallingCompare))
    ...
   .build();
```

**Comment by merajani** [comment]
Thanks for the details and guidance.

I tried to implement custom `WhitespaceStrippedTextNodeSource  `and added `stripEmptyTextNodes  `in it, however it is not stripping the white space so DiffBuilder thinks the XML input files are different.  I am trying to normalize the cloned Nodes in `stripEmptyTextNodes `. I tried a few things, could you please share your thoughts.
```
public class WhitespaceStrippedTextNodeSource extends DOMSource{
    
    public WhitespaceStrippedTextNodeSource  (Source originalSource) {
        
        super(stripEmptyTextNodes (Convert.toDocument(originalSource)));
        setSystemId(originalSource.getSystemId());
    }


    public WhitespaceStrippedTextNodeSource(Source originalSource, DocumentBuilderFactory dbf) {
        super(stripEmptyTextNodes (Convert.toDocument(originalSource, dbf)));
        setSystemId(originalSource.getSystemId());
    }
    
    public static Node stripEmptyTextNodes (Node original) {
        Node cloned = original.cloneNode(true);
        cloned.normalize();
         return cloned;
    }

}
```

```
Diff myDiff = DiffBuilder.compare( new WhitespaceStrippedTextNodeSource(new StreamSource(new java.io.StringReader(xml1))))
                .withTest(new WhitespaceStrippedTextNodeSource(new StreamSource(new java.io.StringReader(xml2))))
                .withDifferenceEvaluator(DifferenceEvaluators.chain(DifferenceEvaluators.Default,
                 DifferenceEvaluators.downgradeDifferencesToSimilar(ComparisonType.NAMESPACE_URI)))
                .checkForSimilar()
                .withNodeMatcher(
                        new DefaultNodeMatcher(ElementSelectors.conditionalBuilder().whenElementIsNamed("Line")
                                .thenUse(ElementSelectors.byXPath("./ID", ElementSelectors.byNameAndText))
                                .elseUse(ElementSelectors.byNameAndText).build())).build();
```

**Comment by bodewig** [comment]
`normalize` usually doesn't do anything, it mostly applies when you've built up the `Document` in memory. What you are missing is something similar to `Nodes.handleWsRec` that doesn't perform the `trim` operation.

As I think you are not the only one needing this kind of functionality I've opened #119.

**Comment by bodewig** [comment]
implemented in master now, will be in XMLUnit 2.6.0

**Comment by merajani** [comment]
Thank you so much for all the guidance and the effort to enhance the library in short time.

**Comment by bodewig** [comment]
you're welcome. I hope you've seen I've already released 2.6.0.

**Comment by merajani** [comment]
I have seen it and upgraded the maven to use 2.6.0. So here is how i am using the custom source - ElementContentWhitespaceStrippedSource .

```
Diff myDiff = DiffBuilder.compare( new ElementContentWhitespaceStrippedSource (new StreamSource(new java.io.StringReader(xml1))))
                .withTest(new ElementContentWhitespaceStrippedSource (new StreamSource(new java.io.StringReader(xml2))))
                .withDifferenceEvaluator(DifferenceEvaluators.chain(DifferenceEvaluators.Default,
                 DifferenceEvaluators.downgradeDifferencesToSimilar(ComparisonType.NAMESPACE_URI)))
                .checkForSimilar()
                .withNodeMatcher(
                        new DefaultNodeMatcher(ElementSelectors.conditionalBuilder().whenElementIsNamed("Line")
                                .thenUse(ElementSelectors.byXPath("./ID", ElementSelectors.byNameAndText))
                                .elseUse(ElementSelectors.byNameAndText).build())).build();
```

**Comment by bodewig** [comment]
You could have used the new `ignoreElementContentWhitespace` method on `DiffBuilder` as well.

**Comment by nikolakurtic** [comment]
Sorry to bring old issue up :)
I'm struggling to compare these two xml structures:
`  control: 
   <node label="TestLabel" type="role">
      <node localname="testLocalName" type="concept">
         <label xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="en">Test-En</label>
         <label xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="de">Test-De</label>
       </node>
   </node>

    test:
   <node label="TestLabel" type="role">
      <node localname="testLocalName" type="concept">
         <label xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="de">Test-De</label>
         <label xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="en">Test-En</label>
       </node>
   </node>
`
Notice that label elements are not in the same order, these should be identical xml-s.
How can I acomplish this? Thanks!

**Comment by nikolakurtic** [comment]
Sorry to bring old issue up :)
I'm struggling to compare these two xml structures:
"  control: 
   <node label="TestLabel" type="role">
      <node localname="testLocalName" type="concept">
         <label xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="en">Test-En</label>
         <label xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="de">Test-De</label>
       </node>
   </node>

    test:
   <node label="TestLabel" type="role">
      <node localname="testLocalName" type="concept">
         <label xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="de">Test-De</label>
         <label xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="en">Test-En</label>
       </node>
   </node>"

Notice that label elements are not in the same order, these should be identical xml-s.
How can I acomplish this? Thanks!

**Comment by krystiankaluzny** [comment]
@nikolakurtic please create new issue for your question. Other folks may easier find solution on similar problems by reviewing titles rather than reading all issues threads. New issue should also include your xmlunit configuration whatever it is (it based xmlunit-core, xmlunit-matchers, xmlunit-assertj or xmlunit-legacy).

**Comment by nikolakurtic** [comment]
Done [https://github.com/xmlunit/xmlunit/issues/146](url)

**Comment by sam757575** [comment]
I am trying to compare two xml which has their child elements unordered. It is failing to compare this.

Here is the code for the same.

```
import org.xmlunit.builder.DiffBuilder;
import org.xmlunit.diff.DefaultNodeMatcher;
import org.xmlunit.diff.Diff;
import org.xmlunit.diff.ElementSelectors;

public class Test2 {
    public static void main(String args[]){
        String controlXml = "<table><tbody><tr><th>some key</th><td>some value</td></tr><tr><th>another key</th><td>another value</td></tr></tbody></table>";
        String testXml = "<table><tbody><tr><th>another key</th><td>another value</td></tr><tr><th>some key</th><td>some value</td></tr></tbody></table>";

        Diff myDiff = DiffBuilder.compare(controlXml).withTest(testXml)
                .checkForSimilar() // a different order is always 'similar' not equals.
                .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))
                .build();


        if (myDiff.hasDifferences()) {
            System.out.println(">>>it has difference");
        } else {
            System.out.println(">>>No difference");
        }

    }
}
```

How will I solve this?
