### ISSUE TITLE
Support AssertJ

### ISSUE THREAD

**Issue by krystiankaluzny** [xmlunit/xmlunit#117]
First of all, thanks for XMLUnit, it's great tool.
I use AssertJ as assertions tool for java and I have to copy implementation of HasXPathMatcher.match() to my code, write some assertj specific helper clesses and finally write tests.

Are there any plans for supporting AssertJ?

**Comment by bodewig** [comment]
I'm not an AssertJ user myself, but would accept pull requests for a new module that adds AssertJ assertions, if anybody provided them ;-)

**Comment by krystiankaluzny** [comment]
I was expecting that :) Maybe soon I will find the time to code something

**Comment by bodewig** [comment]
That would be great, thank you.

**Comment by bbottema** [comment]
@krystiankaluzny, @bodewig, any progress here?

**Comment by bodewig** [comment]
@krystiankaluzny has opened #120 which starts with XPath support,

**Comment by bodewig** [comment]
see also #126 for the next step - great work @krystiankaluzny !

**Comment by bodewig** [comment]
see also #129 - after which I think we can close this issue.

**Comment by krystiankaluzny** [comment]
User guide pages about xmlunit-assertj module:
[Comparing XML](https://github.com/xmlunit/user-guide/wiki/CompareAssert)
[Selecting Nodes with XPath](https://github.com/xmlunit/user-guide/wiki/XPath-Support#multiplenodeassert--singlenodeassert)
[Evaluating XPath](https://github.com/xmlunit/user-guide/wiki/XPath-Support#valueassert)
