### ISSUE TITLE
Compare 2 XMLs with nested elements and un-ordered

### ISSUE THREAD

**Issue by bensam000** [xmlunit/xmlunit#122]
Hi Guys - I want to compare 2 xmls that have nested elements. 

Control XML
```

<books>
    <book>
        <tr>mark</tr>
    </book>
    <book>
        <tr>sam</tr>
    </book>
</books>

```
TEST

```
<books>
    <book>
        <tr>mark</tr>
    </book>

>     <book>
>         <tr>tim</tr>
>     </book>

    <book>
        <tr>sam</tr>
    </book>
</books>
```

From the above sample xml's, I would like to differences only for the new xml block that's added.
I tried using the ElementSelectors byNameandText and other combinations. However, am getting more differences that what I would like.

Options Tried

```
ElementSelectors.conditionalBuilder()
	    .whenElementIsNamed("books")
	    .thenUse(ElementSelectors.byXPath("./book", ElementSelectors.byNameAndText))
	    .elseUse(ElementSelectors.byName)
	    .build();
		
ElementSelectors.or(ElementSelectors.byName,	  
					ElementSelectors.byNameAndText,
					ElementSelectors.byNameAndAllAttributes)		

Expected child nodelist length '2' but was '3' - comparing <books...> at /books[1] to <books...> at /books[1] (DIFFERENT), 
Expected text value 'sam' but was 'tim' - comparing <tr ...>sam</tr> at /books[1]/book[2]/tr[1]/text()[1] to <tr ...>tim</tr> at /books[1]/book[2]/tr[1]/text()[1] (DIFFERENT), 
Expected child 'null' but was 'book' - comparing <NULL> to <book...> at /books[1]/book[3] (DIFFERENT)
```

Is there some other ElementSelectors option thats out there byNameAndXML

**Comment by bensam000** [comment]
Sorry Folks, if this is not a FORUM for discussion. Was not sure where to ask the question, so posted it here

**Comment by bodewig** [comment]
There is a mailing list and some oldish web forums over at sourceforge. I am an old dog and prefer the mailing list but those things are not in fashion anymore. Using the issue tracker for questions is fine with me.

Now to your question: you need an `ElementSelector` for your `book` elements and the criterion is the nested text of the child of the `book` element - which is a level more than what the simple builtin selectors provide. Something like

```
ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("book").thenUse(ElementSelectors.byXPath("./tr", ElementSelectors.byNameAndText))
    .elseUse(ElementSelectors.byName)
    .build();
```

should work. See https://github.com/xmlunit/user-guide/wiki/SelectingNodes#conditional-elementselectors and the whole part of the user guide.

**Comment by bensam000** [comment]
@bodewig  Thanks for your prompt feedback. I did try the above code, but it does not work when i mention namespaces. 

```
<nps:books xmlns:nps="abc">
    <nps:book>
        <nps:tr>mark</nps:tr>
    </nps:book>
	<nps:book>
        <nps:tr>tim</nps:tr>
    </nps:book>
    <nps:book>
        <nps:tr>sam</nps:tr>
    </nps:book>
</nps:books>
```
```
ElementSelectors.conditionalBuilder()
	    .whenElementIsNamed("nps:book")
	    .thenUse(ElementSelectors.byXPath("./nps:tr", ElementSelectors.byNameAndText))
	    .elseUse(ElementSelectors.byName)
	    .build();
```

Is there a different way to use tags with namespaces. Thanks in advance

**Comment by bensam000** [comment]
@bodewig Thanks again, i tried your suggestion and it worked like a charm. I will have to test couple of other scenarios, but this is a good start.

```
                QName paramQName = new QName("http://abc.com", "book", "nps");
		Map<String, String> mapQName = new HashMap<String, String>();
		mapQName.put("nps", "http://abc.com");
		
		ElementSelector esNS = ElementSelectors.conditionalBuilder()
			    .whenElementIsNamed(paramQName)
			    .thenUse(ElementSelectors.byXPath("./nps:tr", mapQName, 
                             ElementSelectors.byNameAndText))
			    .elseUse(ElementSelectors.byName)
			    .build();
```

Appreciate your prompt responses.
