### ISSUE TITLE
Comparing XMLs with different number of nodes

### ISSUE THREAD

**Issue by krishnakanth23** [xmlunit/xmlunit#124]
Hi
If two xmls have different number of nodes, then from the missing node all are considered as difference. It is comparing the next node with missing node and from then all are considered as difference. Is there a way to handle xmls with different node counts?

For example 
**First XML -** 
### <school id="1" name="testschool">
         <userpfrofile id="1" name="testuser">
                  <syllabi>
                             <syllabus id="1" name="123" signature="qwer"/>
                             <syllabus id="2" name ="234" signature="12qq"/>
                             <syllabus id="3" name="123q" signature="11qwer"/>
                             <syllabus id="4" name ="23334" signature="1211qq"/>
                  </syllabi>
         </userprofile>
</school>

**Second XML -**
### <school id="1" name="testschool">
         <userpfrofile id="1" name="testuser">
                  <syllabi>
                             <syllabus id="1" name="123" signature="qwer"/>
                             <syllabus id="3" name="123q" signature="11qwer"/>
                             <syllabus id="4" name ="23334" signature="1211qq"/>
                  </syllabi>
         </userprofile>
</school>

On comparing above two xmls with XMLUnit, it is giving all syllabus node attributes as differences after first syllabus node with id=1. Is there a way to compare xmls with different node count?

**Comment by bodewig** [comment]
You probably need to do two things.

1. ensure you match the "correct" elements to each other. It looks as if you want to use `ElementSelectors.byNameAndAttributes("id")` to ensure only elements with matching `id` are compared.
2. suppress the different node count, for this you use a `DifferenceEvaluator`. For the simple example `DifferenceEvaluators.downgradeDifferencesToSimilar(ComparisonType.CHILD_NODELIST_LENGTH, ComparisonType.CHILD_LOOKUP)` would probably work, but may suppress too many differences in a real use case. I guess you will have to write something more selective your of your own.

**Comment by krishnakanth23** [comment]
@bodewig thanks for helping. Yes it worked by using 

Diff myDiff = DiffBuilder.compare(downloadedNewXML).withTest(actualPresentXML).checkForSimilar()
				.checkForIdentical().ignoreComments().ignoreWhitespace().normalizeWhitespace()
				.withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndAttributes("id")))
				.withDifferenceEvaluator(new DifferenceEvaluator() {

					@Override
					public ComparisonResult evaluate(Comparison comparison, ComparisonResult outcome) {
						return comparison.getType() == ComparisonType.CHILD_NODELIST_SEQUENCE ? null : outcome;
					}
				}).build();

by using above am abble to skip node sequence changes and am getting changed related to particular element only.

**Comment by bodewig** [comment]
Sounds good, thanks for the update.
