### ISSUE TITLE
For missing element in actual XML file is compared with all the elements below the index at which it was suppose to be occured in expected XML file 

### ISSUE THREAD

**Issue by KiranBolaj** [xmlunit/xmlunit#125]
Hi,

I am comparing actual XML file with expected XML file and difference will be stored in object of Diff. ( I am using xmlunit 2.6.0)

Consider actualXML.xml -
`<MainNode>
	<SubMainNode>
		<node1>123</node1>
		<node2>abc</node2>
		<node3>456</node3>
		<node4>457</node4>
		<node5>bcd</node5>
		<node6>456</node6>
	</SubMainNode>
</MainNode>`

expectedXML.xml -
`<MainNode>
	<SubMainNode>
		<node1>123</node1>
		<node2>abc</node2>
		<node4>457</node4>
		<node5>bcd</node5>
		<node6>456</node6>
	</SubMainNode>
</MainNode>`

And I am executing following block of code -  XMLDifference.java

package com.abc;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Iterator;
import java.util.LinkedHashSet;

import org.xmlunit.builder.DiffBuilder;
import org.xmlunit.diff.Diff;
import org.xmlunit.diff.Difference;

public class XMLDifference {
	public static void main(String[] args) {
		File actual = new File("actualXML.xml");
		File expected = new File("expectedXML.xml");
		String control = null;
		String test = null;
		try {
			control = new String(Files.readAllBytes(Paths.get(actual.toString())));
			test = new String(Files.readAllBytes(Paths.get(expected.toString())));
		} catch (IOException e) {
			e.printStackTrace();
		}
		Diff documentDiff = DiffBuilder.compare(control).withTest(test).checkForSimilar().build();
                int i = 0;
		Iterator<Difference> d = documentDiff.getDifferences().iterator();
		LinkedHashSet<String> set = new LinkedHashSet<String>();
		if (documentDiff.hasDifferences()) {
			while(d.hasNext()) {
				System.out.println((++i) + ") " + d.next());
			}
		}
	}
}

I get the console output as -

`1)Expected child nodelist length '13' but was '11' - comparing <SubMainNode...> at /MainNode[1]/SubMainNode[1] to <SubMainNode...> at /MainNode[1]/SubMainNode[1] (DIFFERENT)
2)Expected element tag name 'node3' but was 'node4' - comparing <node3...> at /MainNode[1]/SubMainNode[1]/node3[1] to <node4...> at /MainNode[1]/SubMainNode[1]/node4[1] (DIFFERENT)
3)Expected text value '456' but was '457' - comparing <node3 ...>456</node3> at /MainNode[1]/SubMainNode[1]/node3[1]/text()[1] to <node4 ...>457</node4> at /MainNode[1]/SubMainNode[1]/node4[1]/text()[1] (DIFFERENT)
4)Expected element tag name 'node4' but was 'node5' - comparing <node4...> at /MainNode[1]/SubMainNode[1]/node4[1] to <node5...> at /MainNode[1]/SubMainNode[1]/node5[1] (DIFFERENT)
5)Expected text value '457' but was 'bcd' - comparing <node4 ...>457</node4> at /MainNode[1]/SubMainNode[1]/node4[1]/text()[1] to <node5 ...>bcd</node5> at /MainNode[1]/SubMainNode[1]/node5[1]/text()[1] (DIFFERENT)
6)Expected element tag name 'node5' but was 'node6' - comparing <node5...> at /MainNode[1]/SubMainNode[1]/node5[1] to <node6...> at /MainNode[1]/SubMainNode[1]/node6[1] (DIFFERENT)
7)Expected text value 'bcd' but was '456' - comparing <node5 ...>bcd</node5> at /MainNode[1]/SubMainNode[1]/node5[1]/text()[1] to <node6 ...>456</node6> at /MainNode[1]/SubMainNode[1]/node6[1]/text()[1] (DIFFERENT)
8)Expected text value '
		' but was '
	' - comparing <SubMainNode ...>
		</SubMainNode> at /MainNode[1]/SubMainNode[1]/text()[6] to <SubMainNode ...>
	</SubMainNode> at /MainNode[1]/SubMainNode[1]/text()[6] (DIFFERENT)
9)Expected child 'node6' but was 'null' - comparing <node6...> at /MainNode[1]/SubMainNode[1]/node6[1] to <NULL> (DIFFERENT)
10)Expected child '#text' but was 'null' - comparing <SubMainNode ...>
	</SubMainNode> at /MainNode[1]/SubMainNode[1]/text()[7] to <NULL> (DIFFERENT)
`

So my query is why `<node3>` is compared with all other nodes `<node4>, <node5>, <node6>` ?

And Is it possible to display only mismatch elements or missing elements through XMLUnit?

**Comment by bodewig** [comment]
Sorry for the delay.

You don't tell XMLUnit to only compare elements if their names match. If you throw in

```
            .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byName))
```

then you are down to three difference:

```
1) Expected child nodelist length '11' but was '13' - comparing <SubMainNode...> at /MainNode[1]/SubMainNode[1] to <SubMainNode...> at /MainNode[1]/SubMainNode[1] (DIFFERENT)
2) Expected child 'null' but was 'node3' - comparing <NULL> to <node3...> at /MainNode[1]/SubMainNode[1]/node3[1] (DIFFERENT)
3) Expected child 'null' but was '#text' - comparing <NULL> to <SubMainNode ...> </SubMainNode> at /MainNode[1]/SubMainNode[1]/text()[7] (DIFFERENT)
```

In your original example the default element selector is used - which compares elements in document order.  So actualxml's `node3` is compared to expectedxml's `node4` and so on, leading to all the additional differences you see.

**Comment by KiranBolaj** [comment]
Can you please give me the solution, so that missing element should not be compared with other elements.

**Comment by bodewig** [comment]
See above, it isn't if you use `ElementSelectors.byName`. The differences that still remain is the total number of children, a missing element and a missing text node (the whitespace between elements). In order to get rid of the whitespace differences you can use `ignoreElementContentWhitespace` on the `DiffBuilder`.

If you want to suppress those differences as well, you can try a custom `DifferenceEvaluator`. I'm just not sure I understand your requirement correctly, Do you want to ignore any additional elements? Also ignore missing elements? Or do you just want to accept excess elements as children of a specific element?

**Comment by KiranBolaj** [comment]
Hi,
 Thanks for the response.
As we use Diff API from xmlunit, we get the difference message as  below - 
`1)Expected child nodelist length '13' but was '11' - comparing <SubMainNode...> at /MainNode[1]/SubMainNode[1] to <SubMainNode...> at /MainNode[1]/SubMainNode[1] (DIFFERENT) 2)Expected element tag name 'node3' but was 'node4' - comparing <node3...> at /MainNode[1]/SubMainNode[1]/node3[1] to <node4...> at /MainNode[1]/SubMainNode[1]/node4[1] (DIFFERENT) 3)Expected text value '456' but was '457' - comparing <node3 ...>456</node3> at /MainNode[1]/SubMainNode[1]/node3[1]/text()[1] to <node4 ...>457</node4> at /MainNode[1]/SubMainNode[1]/node4[1]/text()[1] (DIFFERENT) 4)Expected element tag name 'node4' but was 'node5' - comparing <node4...> at /MainNode[1]/SubMainNode[1]/node4[1] to <node5...> at /MainNode[1]/SubMainNode[1]/node5[1] (DIFFERENT) 5)Expected text value '457' but was 'bcd' - comparing <node4 ...>457</node4> at /MainNode[1]/SubMainNode[1]/node4[1]/text()[1] to <node5 ...>bcd</node5> at /MainNode[1]/SubMainNode[1]/node5[1]/text()[1] (DIFFERENT) 6)Expected element tag name 'node5' but was 'node6' - comparing <node5...> at /MainNode[1]/SubMainNode[1]/node5[1] to <node6...> at /MainNode[1]/SubMainNode[1]/node6[1] (DIFFERENT) 7)Expected text value 'bcd' but was '456' - comparing <node5 ...>bcd</node5> at /MainNode[1]/SubMainNode[1]/node5[1]/text()[1] to <node6 ...>456</node6> at /MainNode[1]/SubMainNode[1]/node6[1]/text()[1] (DIFFERENT) 8)Expected text value ' ' but was ' ' - comparing <SubMainNode ...> </SubMainNode> at /MainNode[1]/SubMainNode[1]/text()[6] to <SubMainNode ...> </SubMainNode> at /MainNode[1]/SubMainNode[1]/text()[6] (DIFFERENT) 9)Expected child 'node6' but was 'null' - comparing <node6...> at /MainNode[1]/SubMainNode[1]/node6[1] to <NULL> (DIFFERENT) 10)Expected child '#text' but was 'null' - comparing <SubMainNode ...> </SubMainNode> at /MainNode[1]/SubMainNode[1]/text()[7] to <NULL> (DIFFERENT)`

We extract the names of the elements from above message. At that time we are getting the other elements apart from missing elements even though those elements are not missing.
 
Is there any solution to display or extract only mismatch elements or missing elements?

**Comment by bodewig** [comment]
Please see https://github.com/xmlunit/xmlunit/issues/125#issuecomment-400577100

You need to modify your code to say 

```
Diff documentDiff = DiffBuilder.compare(control).withTest(test)
    .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byName))
    .checkForSimilar().build();
```
