### ISSUE TITLE
Support for XPath2.0 features ends-with/matches

### ISSUE THREAD

**Issue by rbkumar88** [xmlunit/xmlunit#130]
Hi,

Does xmlunit-matchers not support XPATH2.0. PFB code and exception stack trace.
Code:
```
 private static final String EXAMPLE_XML1 = "<stuff>\n"
            + "	<thing>hat</thing>\n" + "	<thing>cat</thing>\n"
            + "	<thing>car</thing>\n" + "</stuff>";

assertThat(EXAMPLE_XML1,
                hasXPath("count(//thing[ends-with(., 'at')])", equalTo("3")));
```
Error
```
org.xmlunit.XMLUnitException: javax.xml.transform.TransformerException: Could not find function: ends-with
```
Thanks
Bharath

**Comment by bodewig** [comment]
XMLUnit simply uses the JAXP XPath engine, so you need to use one that does support XPath 2.0. I know Saxon contains one, but I'm sure that is not the only one.

**Comment by rbkumar88** [comment]
Hi, so in short I cannot use xmlunit-matchers hasXPath to achieve this. Is my understanding right? Any way I can override the hasXPath method to achieve that.

**Comment by bodewig** [comment]
You can use xmlunit-matchers hasXPath as long as you configure Java to use an XPath engine that supports XPath 2.0 using the mechanisms of JAXP: https://docs.oracle.com/javase/10/docs/api/javax/xml/xpath/XPathFactory.html#newInstance(java.lang.String)

**Comment by bodewig** [comment]
I just realized selecting Saxon may not be as straight forward as I thought and opened #131
