### ISSUE TITLE
Support for BigDecimal comparison for arithmetic assertions

### ISSUE THREAD

**Issue by rbkumar88** [xmlunit/xmlunit#133]
Hi,

I see EvaluateXPathMatcher supports only String, it would be better to have an arithmetic comparison/Matcher support so that we can use it with Hamcrest matchers like greaterThan, greaterThanOrEqualTo etc.

Thanks

**Comment by bodewig** [comment]
Using the new `TypeMatcher` you can do stuff like

```java
assertThat(xml, hasXPath("count(//fruits/fruit)", asDouble(equalTo(4.0))));
```

**Comment by bodewig** [comment]
2.6.2 has just been released
