### ISSUE TITLE
Java 11 Compatibility check

### ISSUE THREAD

**Issue by awegrzynptc** [xmlunit/xmlunit#134]
Hi,
We are reaching out to you to check Java 11 compatibility of the library xmlunit.
Our last files:
LIB: xmlunit.jar
SRC: xmlunit-1.6-bin.zip, xmlunit-1.6-src.zip

Could you help us by answering the following questions:
1.	Library Name: 
2.	Lates version: 
3.	Latest version Is the library compatible with Java 11 Compatible? (Y/N)
4.	Is the library supported with Java 11? (Y/N)
5.	(If “N” in compatibility or support) What is the versions that would be compatible and Supported?
6.	Date of support availability?

Thanks,
PTC
Artur Węgrzyn

**Comment by bodewig** [comment]
XMLUnit 1.6 is vastly outdated, 2.6.1 is the current release.

We are running continuous integration tests on Java 10 and the OpenJDK 11 early access build - and are not aware of any problems so far. There is no explicit check for compatibility with Java 11 and we don't intend to perform any such check.

If you encounter any problems with using a recent version of XMLUnit with Java 11, please open a bug report.
