### ISSUE TITLE
XmlUnit 2.6.1 is not compatible with AssertJ-Core 3.9.1

### ISSUE THREAD

**Issue by mindhaq** [xmlunit/xmlunit#135]
The AssertJ dependency for XmlUnit 2.6.1 is on 2.9.0. Latest version is 3.9.11. Using a later version explicitly is not working, because AssertJ introduced a binary incompatibility in 3.9.1 - which leads to `NoSuchMethodError`.

See https://github.com/joel-costigliola/assertj-core/issues/1194

This is probably fixable simply by upgrading to the latest version of AssertJ.

**Comment by bodewig** [comment]
From what I understand AssertJ 3.x requires Java8 at runtime. I think @krystiankaluzny chose 2.9.0 as he wanted to stick with the Java7 (given that XMLUnit Core is supposed to work with Java6).

**Comment by krystiankaluzny** [comment]
@mindhaq upgrading AssertJ will fix the binary incompatibility problem but it also break Java 7 compatibility.
To handle both I'm thinking about another solution eg direct call ObjectAssert.

**Comment by mindhaq** [comment]
Compatibility would really be nice. As of right now, XmlUnit requires a manual downgrade of AssertJ when using the latest version of Spring Boot.

**Comment by bodewig** [comment]
I've just published a 2.6.2-SNAPSHOT to

```
<repository>
  <id>snapshots-repo</id>
  <url>https://oss.sonatype.org/content/repositories/snapshots</url>
  <releases><enabled>false</enabled></releases>
  <snapshots><enabled>true</enabled></snapshots>
</repository>
```

This is supposed to work without the downgrade.

**Comment by krystiankaluzny** [comment]
I also notice that in assertj-core 3.11.0 binary incompatibility was introduced too.
`AbstractCharSequenceAssert<?, String> assertThat(String actual)` was changed to `AbstractStringAssert<?> assertThat(String actual)`

To prevent similar issues I change all invocation of `org.assertj.core.api.Assertions.assertThat` to direct creation of assertion classes.

**Comment by bodewig** [comment]
I'm just publishing a new 2.6.2-SNAPSHOT.

**Comment by PascalSchumacher** [comment]
I can confirm that the latest `2.6.2-SNAPSHOT` works with assertj-core `3.9.1`, `3.10.0` and `3.11.0`.

Thank you for fixing this! 👍 

A release with this fix would be great.

**Comment by bodewig** [comment]
2.6.2 is on its way to Maven Central

**Comment by PascalSchumacher** [comment]
Thank you very much! 😃
