### ISSUE TITLE
Comparing XML files ignoring elements attribute Order

### ISSUE THREAD

**Issue by vramsprsk** [xmlunit/xmlunit#139]
HI All,

Iam new to this field and has been assigned with a challenging task. 
I have 2 XML files (namely Test1 & Test 2 as mentioned below). And i need to compare these xml files using java and return boolean value as true if there are no differences.
And the challenge here is the Second Xml file (Test2.xml) the elements order is always jumbled
 I tried XMLUnit2 for comparing the 2 xml strings but it is failing if there are multiple parent nodes or large xml.
  
```
Test1.Xml:

<PACKINGS>
    <PACKING>
      <TYPE>CCST</TYPE>
      <ORDERNUM>810000510</ORDERNUM>
      <SVCTAGS>
        <SVCTAG>
          <SVCTAGTYPE>DRAGON</SVCTAGTYPE>
          <SVCTAGNUMBER>768100005105001</SVCTAGNUMBER>
          <TIENUMBER>1</TIENUMBER>
          <BOXID>768100005105001</BOXID>
          <LENGTH>4</LENGTH>
          <WIDTH>5</WIDTH>
          <HEIGHT>10</HEIGHT>
          <PARTS>
            <PART>
              <PARTNUMBER>RKH5D</PARTNUMBER>
              <PARTQTY>10</PARTQTY>
            </PART>
          </PARTS>
        </SVCTAG>
        <SVCTAG>
          <SVCTAGTYPE>DRAGON</SVCTAGTYPE>
          <SVCTAGNUMBER>768100005105002</SVCTAGNUMBER>
          <TIENUMBER>2</TIENUMBER>
          <BOXID>768100005105002</BOXID>
          <LENGTH>4</LENGTH>
          <WIDTH>5</WIDTH>
          <HEIGHT>10</HEIGHT>
          <PARTS>
            <PART>
              <PARTNUMBER>FHMTN</PARTNUMBER>
              <PARTQTY>10</PARTQTY>
            </PART>
          </PARTS>
        </SVCTAG>
      </SVCTAGS>
    </PACKING>
  </PACKINGS>

```
```
Test2.Xml:

  <PACKINGS>
      <PACKING>
        <TYPE>CCST</TYPE>
        <ORDERNUM>810000510</ORDERNUM>
        <SVCTAGS>
        <SVCTAG>
        <SVCTAGTYPE>DRAGON</SVCTAGTYPE>
        <SVCTAGNUMBER>768100005105002</SVCTAGNUMBER>
        <TIENUMBER>2</TIENUMBER>
        <BOXID>768100005105002</BOXID>
        <LENGTH>4</LENGTH>
        <WIDTH>5</WIDTH>
        <HEIGHT>10</HEIGHT>
      <PARTS>
        <PART>
         <PARTNUMBER>FHMTN</PARTNUMBER>
         <PARTQTY>10</PARTQTY>
         </PART>
       </PARTS>
      </SVCTAG>
      <SVCTAG>
        <SVCTAGTYPE>DRAGON</SVCTAGTYPE>
        <SVCTAGNUMBER>768100005105001</SVCTAGNUMBER>
        <TIENUMBER>1</TIENUMBER>
        <BOXID>768100005105001</BOXID>
        <LENGTH>4</LENGTH>
        <WIDTH>5</WIDTH>
        <HEIGHT>10</HEIGHT>
      <PARTS>
       <PART>
        <PARTNUMBER>RKH5D</PARTNUMBER>
        <PARTQTY>10</PARTQTY>
        </PART>
      </PARTS>
     </SVCTAG>
    </SVCTAGS>
   </PACKING>
  </PACKINGS>

```
package com.com.java;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.*;

import org.custommonkey.xmlunit.Diff;
import org.custommonkey.xmlunit.XMLAssert;
import org.testng.annotations.Test;
import org.xmlunit.builder.DiffBuilder;
import org.xmlunit.builder.Input;
import org.xmlunit.diff.DefaultNodeMatcher;
import org.xmlunit.diff.ElementSelectors;
import org.xmlunit.matchers.CompareMatcher;	

public class TestNg  {
	@Test
	public void testXmlUnit() {
  String ControlXML = "<PACKINGS><PACKING><TYPE>CCST</TYPE><ORDERNUM>810000510</ORDERNUM><SVCTAGS><SVCTAG><SVCTAGTYPE>DRAGON</SVCTAGTYPE><SVCTAGNUMBER>768100005105002</SVCTAGNUMBER><TIENUMBER>2</TIENUMBER><BOXID>768100005105002</BOXID><LENGTH>4</LENGTH><WIDTH>5</WIDTH><HEIGHT>10</HEIGHT></SVCTAG><SVCTAG><SVCTAGTYPE>DRAGON</SVCTAGTYPE><SVCTAGNUMBER>768100005105001</SVCTAGNUMBER><TIENUMBER>1</TIENUMBER><BOXID>768100005105001</BOXID><LENGTH>4</LENGTH><WIDTH>5</WIDTH><HEIGHT>10</HEIGHT><PARTS><PART><PARTNUMBER>RKH5D</PARTNUMBER><PARTQTY>10</PARTQTY></PART></PARTS></SVCTAG></SVCTAGS></PACKING></PACKINGS>";
	    String testXml = "<PACKINGS><PACKING><TYPE>CCST</TYPE><ORDERNUM>810000510</ORDERNUM><SVCTAGS><SVCTAG><SVCTAGTYPE>DRAGON</SVCTAGTYPE><SVCTAGNUMBER>768100005105001</SVCTAGNUMBER><TIENUMBER>1</TIENUMBER><BOXID>768100005105001</BOXID><LENGTH>4</LENGTH><WIDTH>5</WIDTH><HEIGHT>10</HEIGHT></SVCTAG><SVCTAG><SVCTAGTYPE>DRAGON</SVCTAGTYPE><SVCTAGNUMBER>768100005105002</SVCTAGNUMBER><TIENUMBER>2</TIENUMBER><BOXID>768100005105002</BOXID><LENGTH>4</LENGTH><WIDTH>5</WIDTH><HEIGHT>10</HEIGHT><PARTS><PART><PARTNUMBER>FHMTN</PARTNUMBER><PARTQTY>10</PARTQTY></PART></PARTS></SVCTAG></SVCTAGS></PACKING></PACKINGS>";
	    assertThat(testXml, CompareMatcher.isSimilarTo(ControlXML).ignoreWhitespace().normalizeWhitespace().withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText, ElementSelectors.byName)));

}  
	}

**Comment by krystiankaluzny** [comment]
I don't know what you mean saying _multiple parent nodes_, but jumbled SVCTAG elements can be handled using ElementSelectors.byXPath:

```java
assertThat(test1, CompareMatcher.isSimilarTo(test2)
    .ignoreWhitespace()
    .normalizeWhitespace()
    .withNodeMatcher(new DefaultNodeMatcher(
        ElementSelectors.conditionalBuilder()
            .whenElementIsNamed("SVCTAG")
            .thenUse(ElementSelectors.byXPath("./SVCTAGNUMBER", ElementSelectors.byNameAndText))
            .elseUse(ElementSelectors.byName)
            .build()
    )));
```

I also suggest using only xmlunit 2.x - don't mixing with xmunit 1.x (org.custommonkey package)

**Comment by vramsprsk** [comment]
First of all thanks a lot for your reply Krystian. SInce I would like to compare all the Tags inside the Packings section could you please guide me on the same so that i can compare and display the boolean value as true if the comparision was succesfull.

**Comment by vramsprsk** [comment]
Thanks a ton for your reply Krystian. I will try the same and one quick question suppose if i wanted to compare large xml files where my second xml will be always unordered child element and i need to do end to end validation i would like to know if that is possible for presenting the bollean value and if there are any examples to refer. kindly awaiting your response.

**Comment by krystiankaluzny** [comment]
I don't have experience with procesing large xml so I don't have any example.
You can provide xmls as java.io.InputStream, but th xmlunit doesn't have special implementation for streamin processing. Even if underlying JAXP implementation use lazyloading, caching etc, I assume that eventualy all Nodes will be loaded into memory.
So the only danger I can see is OutOfMemoryError. But if there will be no memory problems comparison result should be valid.

**Comment by vramsprsk** [comment]
Thanks once again for your reply Krystian. Here iam briefing the exact scenario where i want to compare and Validate only the Item Section from the below 2 xml files and the elements order is different in my Order2.xml file. Kindly guide me on the same:

```
Order1.xml 
<ORDERS>
    <ORDER>
      <CUSID>5439</CUSID>
      <CUSADDRESS>Unit A , 21/F , Phase III, YKK Building,No.7, San Ping Circuit, Tuen Mun, New Territories, Hong KongXMHK</CUSADDRESS>
      <CUSCOUNTRY>HK</CUSCOUNTRY>
      <CUSNAME>5439</CUSNAME>
      <ORDERNUM>810000510</ORDERNUM>
      <CITY>XMHK</CITY>
      <SHIPDATE>2017-09-06 02:58:35</SHIPDATE>
      <CARTONQTYPERORDER>4</CARTONQTYPERORDER>
      <SYSTEMQTYPERORDER>2</SYSTEMQTYPERORDER>
      <GROSSWTPERORDER>20</GROSSWTPERORDER>
      <VOLWTPERORDER>16</VOLWTPERORDER>
      <CARRIERCODE>D</CARRIERCODE>
      <DIRECT>N</DIRECT>
      <TIES>
        <TIE>
          <TIENUMBER>1</TIENUMBER>
          <LOBCODE>4ST</LOBCODE>
          <RetailFlag>N</RetailFlag>
          <ACTDES>PowerVault (Storage)</ACTDES>
          <SYSTEMQTYPERTIE>0</SYSTEMQTYPERTIE>
          <CARTONQTYPERTIE>2</CARTONQTYPERTIE>
          <GROSSWTPERTIE>10</GROSSWTPERTIE>
          <VOLWTPERTIE>8</VOLWTPERTIE>
          <TIEQTY>1</TIEQTY>
          <TIEATTRIBS>
            <Attrib Name="PT_ORDER" Value="Y" />
          </TIEATTRIBS>
          <ITEMS>
            <ITEM>
              <ITEMNUMBER>RKH5D</ITEMNUMBER>
              <ITEMQTY>10</ITEMQTY>
              <MOD>NDRC0</MOD>
              <ITEMDES>MOD,TAPE,MGNTC,LTO7,5PK</ITEMDES>
              <ENMARKETINGDESC>Dell(TM) Media Tape Cartridge (50-Pack) for LTO7</ENMARKETINGDESC>
              <TYPE>INVOICE</TYPE>
              <PRICE>0</PRICE>
            </ITEM>
            <ITEM>
              <ITEMNUMBER>NDRC0</ITEMNUMBER>
              <ITEMQTY>10</ITEMQTY>
              <ITEMDES>MOD,TAPE,MGNTC,LTO7,5PK</ITEMDES>
              <ENMARKETINGDESC>Dell(TM) Media Tape Cartridge (50-Pack) for LTO7</ENMARKETINGDESC>
              <TYPE>BASE</TYPE>
              <PRICE>0</PRICE>
            </ITEM>
          </ITEMS>
        </TIE>
        <TIE>
          <TIENUMBER>2</TIENUMBER>
          <LOBCODE>4ST</LOBCODE>
          <RetailFlag>N</RetailFlag>
          <ACTDES>PowerVault (Storage)</ACTDES>
          <SYSTEMQTYPERTIE>0</SYSTEMQTYPERTIE>
          <CARTONQTYPERTIE>2</CARTONQTYPERTIE>
          <GROSSWTPERTIE>10</GROSSWTPERTIE>
          <VOLWTPERTIE>8</VOLWTPERTIE>
          <TIEQTY>1</TIEQTY>
          <TIEATTRIBS>
            <Attrib Name="PT_ORDER" Value="Y" />
          </TIEATTRIBS>
          <ITEMS>
            <ITEM>
              <ITEMNUMBER>5Y6RT</ITEMNUMBER>
              <ITEMQTY>10</ITEMQTY>
              <ITEMDES>MOD,TAPE,MGNTC,LTO5,5PK</ITEMDES>
              <ENMARKETINGDESC>Dell(TM) Media Tape Cartridge (50-Pack) for LTO5</ENMARKETINGDESC>
              <TYPE>BASE</TYPE>
              <PRICE>0</PRICE>
            </ITEM>
            <ITEM>
              <ITEMNUMBER>FHMTN</ITEMNUMBER>
              <ITEMQTY>10</ITEMQTY>
              <MOD>5Y6RT</MOD>
              <ITEMDES>MOD,TAPE,MGNTC,LTO5,5PK</ITEMDES>
              <ENMARKETINGDESC>Dell(TM) Media Tape Cartridge (50-Pack) for LTO5</ENMARKETINGDESC>
              <TYPE>INVOICE</TYPE>
              <PRICE>0</PRICE>
            </ITEM>
          </ITEMS>
        </TIE>
      </TIES>
    </ORDER>
  </ORDERS>
```
```
Order2.Xml
<ORDERS>
      <ORDER>
      <CUSID>0</CUSID>
      <CUSADDRESS>Unit A , 21/F , Phase III, YKK Building,No.7, San Ping Circuit, Tuen Mun, New Territories, Hong Kong</CUSADDRESS>
      <CUSCOUNTRY>HK</CUSCOUNTRY>
      <CUSNAME>5439</CUSNAME>
      <ORDERNUM>810000510</ORDERNUM>
      <CITY>XMHK</CITY>
      <SHIPDATE>2017-09-06 02:58:35</SHIPDATE>
      <CARTONQTYPERORDER>4</CARTONQTYPERORDER>
      <SYSTEMQTYPERORDER>0</SYSTEMQTYPERORDER>
      <GROSSWTPERORDER>20</GROSSWTPERORDER>
      <VOLWTPERORDER>16</VOLWTPERORDER>
      <CARRIERCODE>D</CARRIERCODE>
      <DIRECT>N</DIRECT>
      <TIES>
      <TIE>
      <TIENUMBER>2</TIENUMBER>
      <LOBCODE>4ST</LOBCODE>
      <RetailFlag>N</RetailFlag>
      <ACTDES>DELL STORAGE OEM</ACTDES>
      <SYSTEMQTYPERTIE>0</SYSTEMQTYPERTIE>
      <CARTONQTYPERTIE>2</CARTONQTYPERTIE>
      <GROSSWTPERTIE>10</GROSSWTPERTIE>
      <VOLWTPERTIE>8</VOLWTPERTIE>
      <TIEQTY>1</TIEQTY>
      <TIEATTRIBS>
      <Attrib Name="PT_ORDER" Value="Y" />
      </TIEATTRIBS>
      <ITEMS>
      <ITEM>
      <ITEMNUMBER>FHMTN</ITEMNUMBER>
      <ITEMQTY>10</ITEMQTY>
      <ITEMDES>MOD,TAPE,MGNTC,LTO5,5PK</ITEMDES>
      <ENMARKETINGDESC>Dell(TM) Media Tape Cartridge (50-Pack) for LTO5</ENMARKETINGDESC>
      <TYPE>INVOICE</TYPE>
      <PRICE>0</PRICE>
      </ITEM>
      <ITEM>
      <ITEMNUMBER>5Y6RT</ITEMNUMBER>
      <ITEMQTY>10</ITEMQTY>
      <ITEMDES>MOD,TAPE,MGNTC,LTO5,5PK</ITEMDES>
      <ENMARKETINGDESC>Dell(TM) Media Tape Cartridge (50-Pack) for LTO5</ENMARKETINGDESC>
      <TYPE>BASE</TYPE>
      <PRICE>0</PRICE>
      </ITEM>
      <ITEM>
      <ITEMNUMBER>FHMTN</ITEMNUMBER>
      <ITEMQTY>10</ITEMQTY>
      <MOD>5Y6RT</MOD>
      <ITEMDES>MOD,TAPE,MGNTC,LTO5,5PK</ITEMDES>
      <TYPE>INVOICE</TYPE>
      <PRICE>0</PRICE>
      </ITEM>
      </ITEMS>
      <DEVIATIONS>
      <ITEMS />
      </DEVIATIONS>
      </TIE>
      <TIE>
      <TIENUMBER>1</TIENUMBER>
      <LOBCODE>4ST</LOBCODE>
      <RetailFlag>N</RetailFlag>
      <ACTDES>DELL STORAGE OEM</ACTDES>
      <SYSTEMQTYPERTIE>0</SYSTEMQTYPERTIE>
      <CARTONQTYPERTIE>2</CARTONQTYPERTIE>
      <GROSSWTPERTIE>10</GROSSWTPERTIE>
      <VOLWTPERTIE>8</VOLWTPERTIE>
      <TIEQTY>1</TIEQTY>
      <TIEATTRIBS>
      <Attrib Name="PT_ORDER" Value="Y" />
      </TIEATTRIBS>
      <ITEMS>
      <ITEM>
      <ITEMNUMBER>RKH5D</ITEMNUMBER>
      <ITEMQTY>10</ITEMQTY>
      <ITEMDES>MOD,TAPE,MGNTC,LTO7,5PK</ITEMDES>
      <ENMARKETINGDESC>Dell(TM) Media Tape Cartridge (50-Pack) for LTO7</ENMARKETINGDESC>
      <TYPE>INVOICE</TYPE>
      <PRICE>0</PRICE>
      </ITEM>
      <ITEM>
      <ITEMNUMBER>NDRC0</ITEMNUMBER>
      <ITEMQTY>10</ITEMQTY>
      <ITEMDES>MOD,TAPE,MGNTC,LTO7,5PK</ITEMDES>
      <ENMARKETINGDESC>Dell(TM) Media Tape Cartridge (50-Pack) for LTO7</ENMARKETINGDESC>
      <TYPE>BASE</TYPE>
      <PRICE>0</PRICE>
      </ITEM>
      <ITEM>
      <ITEMNUMBER>RKH5D</ITEMNUMBER>
      <ITEMQTY>10</ITEMQTY>
      <MOD>NDRC0</MOD>
      <ITEMDES>MOD,TAPE,MGNTC,LTO7,5PK</ITEMDES>
      <TYPE>INVOICE</TYPE>
      <PRICE>0</PRICE>
      </ITEM>
      </ITEMS>
      <DEVIATIONS>
      <ITEMS />
      </DEVIATIONS>
      </TIE>
      </TIES>
      </ORDER>
      </ORDERS>
```
Thanks,
Ram

**Comment by bodewig** [comment]
XMLUnit 2.x is based on a DOM tree of the whole document so it will read the whole document into memory which may or may not be a problem if the document is big. You will have to try. DOM is known to require a lot more memory than the on disk file size of a document.

Using a streaming API makes things like dealing with out of order elements extremely difficult, that's why it hasn't been implemented.

@vramsprsk please read the full User Guide section: https://github.com/xmlunit/user-guide/wiki/SelectingNodes - you really need to thing from the root of your document and help XMLUnit picking the correct pair of nodes. Which pairs are correct is something we can not decide for you, you will have to encode the decision logic yourself.

Assume you are looking at the `ORDERS` element of your documents? How do you know which `ORDER` elements to compare? It may be the textual content of the `ORDERNUM`, in which case you can use a similar approach to what @krystiankaluzny showed in https://github.com/xmlunit/xmlunit/issues/139#issuecomment-417863005 - you only need to replace the element names, for example

```
    .whenElementIsNamed("ORDER")
        .thenUse(ElementSelectors.byXPath("./ORDERNUM", ElementSelectors.byNameAndText))
```

and so on. You really have to figure this out for each type of element that might appear out of order and have to solve it as far up inside of your try as is necessary. And again, only you know enough about your XML documents to do that.

**Comment by vramsprsk** [comment]
Thanks for your inputs @bodewig . As @krystiankaluzny suggested i can work on Scenario 2 and as iam new to this field and started my career recently could you please guide me on End to End Validations of both the order xml files with code if possible. That could be a great favour just how Krystian guiding me.

Regards,
Ram

**Comment by bodewig** [comment]
As I've tried to say, we can't. We don't know what identifies and order element in your domain, you do. Is it the nested text in `ORDERNUM`?

Also, please take the time and try to understand the documentation I've linked to, how it related to Krystian's answer and experiment yourself. You won't be able to solve the next problem if you don't understand why the answers you get work.

**Comment by vramsprsk** [comment]
So just wanted to be more specific on my question @bodewig what i wanted to do is i wanted to validate all the tags and values comparing both the Order xml files and do return a boolean value as true if all the elements and values of Source Xml (Order1.xml)exists in the expected file (Order2.xml). SO Could you please let me know if that is possible or not. Kindly awaiting your response @bodewig

**Comment by bodewig** [comment]
Yes, it is possible.

XMLUnit gives you all the tools you need, but it doesn't give you any simple solution that just works without you having to understand how XMLUnit works.

Krystian has already shown you how to do it for a specific example. You need to understand why Krystian's suggestion works and then adapt it to your other concrete documents.

You still haven't answered what it is that makes you as a human know which `ORDER` elements are those that you consider the same but rather ask us to give you a complete solution - which is not possible for us to do.

**Comment by bilouro** [comment]
For unordered element matching in XMLUnit itself:
  Diff d = DiffBuilder.compare(expected).withTest(actual)
      .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))
      .checkForSimilar().ignoreWhitespace().build();
  boolean equal = !d.hasDifferences();
If what you actually want is a human-readable *report* of what changed across two
(or more) files — keyed by a stable identity, with volatile attributes ignored —
xmldiffreport does that as a CLI/Python lib: https://github.com/bilouro/xmldiffreport
(Disclosure: I'm the author.)
