### ISSUE TITLE
Comparing Xml files using C# and XmlUnit2.0

### ISSUE THREAD

**Issue by vramsprsk** [xmlunit/xmlunit#140]
Hello experts,
i am kinda new to thisstuff, i wanted to know how to compare two xml files using  C#/xmlunit2.0 and display  only with the differences : 

Xml 1: 
`  <?xml version="1.0" encoding="utf-8"?>
    <ASNNUM>SXMSEO180814001D</ASNNUM>
      <ORDERS>
         <ORDER>
          <CUSNAME>743828553</CUSNAME>
          <ORDERNUM>979793524</ORDERNUM>
          <CITY />
          <TIES>
            <TIE>
              <TIENUMBER>1</TIENUMBER>
              <TIEQTY>1</TIEQTY>
              <ITEMS>
                 <ITEM>
                  <ITEMNUMBER>KF3P2</ITEMNUMBER>
                  <ITEMQTY>1</ITEMQTY>
                  <PRICE>8.27</PRICE>
                </ITEM>
                <ITEM>
                  <ITEMNUMBER>60RD2</ITEMNUMBER>
                  <ITEMQTY>1</ITEMQTY>
                  <PRICE>8.27</PRICE>
                </ITEM>
              </ITEMS>
            </TIE>
          </TIES>
    	</ORDER>
    	<ORDER>
          <CUSNAME>743828552</CUSNAME>
          <ORDERNUM>979794834</ORDERNUM>
          <CITY />
          <TIES>
            <TIE>
              <TIENUMBER>1</TIENUMBER>
              <TIEQTY>1</TIEQTY>
              <ITEMS>
                <ITEM>
                  <ITEMNUMBER>K850M</ITEMNUMBER>
                  <ITEMQTY>1</ITEMQTY>
                  <PRICE>1.54</PRICE>
                </ITEM>
                <ITEM>
                  <ITEMNUMBER>T732H</ITEMNUMBER>
                  <ITEMQTY>1</ITEMQTY>
                  <PRICE>1.54</PRICE>
                </ITEM>
              </ITEMS>
            </TIE>
          </TIES>
        </ORDER>
      </ORDERS>`

XML 2:

`<?xml version="1.0" encoding="utf-8"?>
      <ASNNUM>SXMSEO180814001D</ASNNUM>
       <ORDERS>
         <ORDER>
          <CUSID>744400014</CUSID>
          <ORDERNUM>979794834</ORDERNUM>
          <TIES>
            <TIE>
              <TIENUMBER>1</TIENUMBER>
              <TIEQTY>1</TIEQTY>
              <ITEMS>
                <ITEM>
                  <ITEMNUMBER>T732H</ITEMNUMBER>
                  <ITEMQTY>1</ITEMQTY>
                  <PRICE>1.54</PRICE>
                </ITEM>
                <ITEM>
                  <ITEMNUMBER>K850M</ITEMNUMBER>
                  <ITEMQTY>1</ITEMQTY>
                  <PRICE>1.54</PRICE>
                </ITEM>
              </ITEMS>
            </TIE>
          </TIES>
        </ORDER>
    	<ORDER>
          <CUSID>743138972</CUSID>
          <CUSADDRESS>KLS Tokyo Terminal3-2-31 Yashio, Shinagawa, TokyoJapan</CUSADDRESS>
          <ORDERNUM>979793524</ORDERNUM>
          <TIES>
            <TIE>
              <TIENUMBER>1</TIENUMBER>
              <TIEQTY>1</TIEQTY>
              <ITEMS>
                <ITEM>
                  <ITEMNUMBER>60RD2</ITEMNUMBER>
                  <ITEMQTY>1</ITEMQTY>
                  <PRICE>8.27</PRICE>
                </ITEM>
    	        <ITEM>
                  <ITEMNUMBER>KF3P2</ITEMNUMBER>
                  <ITEMQTY>25</ITEMQTY>
                  <PRICE>8.27</PRICE>
                </ITEM>
              </ITEMS>
            </TIE>
          </TIES>
        </ORDER>
      </ORDERS>`

Thanks,
Ram

**Comment by krystiankaluzny** [comment]
First of all, this issue relates to .net version of xmlunit so it should be opened in https://github.com/xmlunit/xmlunit.net  project.
It doesn't look like a complicated issue and I think the User Guid should help https://github.com/xmlunit/user-guide/wiki especially DiffBuilder page where there is an C# example.
XMLUnit for .NET and for Java have similar API so java related examples will be helpful too

**Comment by vramsprsk** [comment]
Thanks a lot @krystiankaluzny  for your reply could you please help me if i could even ignore the child attributes order while comparing the xml and could you share me some code too.
Thanks,
Ram

**Comment by bodewig** [comment]
@vramsprsk you can do so by using the correct `ElementSelector`, please see https://github.com/xmlunit/xmlunit.net/#comparing-two-documents and  https://github.com/xmlunit/user-guide/wiki/SelectingNodes this should give you a start.
