### ISSUE TITLE
Issue when comparing XML files using XMLUnit 2/ Java eclipse

### ISSUE THREAD

**Issue by vramsprsk** [xmlunit/xmlunit#141]
Greetings Everyone,

Iam trying to compare XML files in which the child attribute order is in jumbled order and iam using XMLUnit 2 to compare the xml files but iam not able to get the appropriate results. Iam sharing you the code and xml files below so that could you please guide me on the same:

```java
package com.java;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.custommonkey.xmlunit.Diff;
import org.custommonkey.xmlunit.DifferenceConstants;
import org.custommonkey.xmlunit.DifferenceListener;
import org.custommonkey.xmlunit.ElementNameAndAttributeQualifier;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;
//import org.xmlunit.diff.Difference;
import org.custommonkey.xmlunit.Difference;

import junit.framework.Assert;

public class XmlProviderAssertions extends Assert {    
	
    public static void assertEquivalentXml(String expectedXML, String testXML, String[] nodesWithOrderedChildren, String[] attributesToIgnore) {
        Set<String> setOfNodesWithOrderedChildren = new HashSet<String>();
        if(nodesWithOrderedChildren != null ) {
            Collections.addAll(setOfNodesWithOrderedChildren, nodesWithOrderedChildren);
        }

        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        dbf.setCoalescing(true);
        dbf.setIgnoringElementContentWhitespace(true);
        dbf.setIgnoringComments(true);
        DocumentBuilder db = null;
        try {
            db = dbf.newDocumentBuilder();
        } catch (ParserConfigurationException e) {
            fail("Error testing XML");
        }

        Document expectedXMLDoc = null;
        Document testXMLDoc = null;
        try {
            expectedXMLDoc = db.parse(new ByteArrayInputStream(expectedXML.getBytes()));
            expectedXMLDoc.normalizeDocument();

            testXMLDoc = db.parse(new ByteArrayInputStream(testXML.getBytes()));
            testXMLDoc.normalizeDocument();
        } catch (SAXException e) {
            fail("Could not parse testXML");
        } catch (IOException e) {
            fail("Could not read testXML");
        }
        NodeList expectedChildNodes = expectedXMLDoc.getLastChild().getChildNodes();
        NodeList testChildNodes = testXMLDoc.getLastChild().getChildNodes();

        assertEquals("Test XML does not have expected amount of child nodes", expectedChildNodes.getLength(), testChildNodes.getLength());

        //compare parent nodes        
        Document expectedDEDoc = getNodeAsDocument(expectedXMLDoc.getDocumentElement(), db, false);        
        Document testDEDoc = getNodeAsDocument(testXMLDoc.getDocumentElement(), db, false);
        Diff diff = new Diff(expectedDEDoc, testDEDoc);
        assertTrue("Test XML parent node doesn't match expected XML parent node. " + diff.toString(), diff.similar());

        // compare child nodes
        for(int i=0; i < expectedChildNodes.getLength(); i++) {
            // expected child node
            Node expectedChildNode = expectedChildNodes.item(i);
            // skip text nodes
            if( expectedChildNode.getNodeType() == Node.TEXT_NODE ) {
                continue;
            }
            // convert to document to use in Diff
            Document expectedChildDoc = getNodeAsDocument(expectedChildNode, db, true);

            boolean hasSimilar = false;
            StringBuilder  messages = new StringBuilder();

            for(int j=0; j < testChildNodes.getLength(); j++) {
                // find child node in test xml
                Node testChildNode = testChildNodes.item(j);
                // skip text nodes
                if( testChildNode.getNodeType() == Node.TEXT_NODE ) {
                    continue;
                }
                // create doc from node
                Document testChildDoc = getNodeAsDocument(testChildNode, db, true);

                diff = new Diff(expectedChildDoc, testChildDoc);
                // if it doesn't contain order specific nodes, then use the elem and attribute qualifier, otherwise use the default
                if( !setOfNodesWithOrderedChildren.contains( expectedChildDoc.getDocumentElement().getNodeName() ) ) {
                    diff.overrideElementQualifier(new ElementNameAndAttributeQualifier());
                }
                if(attributesToIgnore != null) {
                    diff.overrideDifferenceListener(new IgnoreNamedAttributesDifferenceListener(attributesToIgnore));
                }
                messages.append(diff.toString());
                boolean similar = diff.similar();
                if(similar) {
                	System.out.println("success::"+similar);
                    hasSimilar = true;
                }
            }
            assertTrue("Test XML does not match expected XML. " + messages, hasSimilar);
           
        }
    }

    private static Document getNodeAsDocument(Node node, DocumentBuilder db, boolean deep) {
        // create doc from node
        Document nodeDoc = db.newDocument();
        Node importedNode = nodeDoc.importNode(node, deep);
        nodeDoc.appendChild(importedNode);
        return nodeDoc;
    }

}

 class IgnoreNamedAttributesDifferenceListener implements DifferenceListener {
    Set<String> attributeBlackList;

    public IgnoreNamedAttributesDifferenceListener(String[] attributeNames) {        
        attributeBlackList = new HashSet<String>();
        Collections.addAll(attributeBlackList, attributeNames);
    }

    public int differenceFound(Difference difference) {
        int differenceId = difference.getId();
        if (differenceId == DifferenceConstants.ATTR_VALUE_ID) {
            if(attributeBlackList.contains(difference.getControlNodeDetail().getNode().getNodeName())) {
                return DifferenceListener.RETURN_IGNORE_DIFFERENCE_NODES_IDENTICAL;
            }
        }

        return DifferenceListener.RETURN_ACCEPT_DIFFERENCE;
    }

    public void skippedComparison(Node node, Node node1) {
        // left empty
    }
}
```
XML 1:
`  <ORDERS>
     <ORDER>
	 <ORDERNUM>979793524</ORDERNUM>
      <TIES>
        <TIE>
          <TIENUMBER>1</TIENUMBER>
          <TIEQTY>1</TIEQTY>
          <ITEMS>
             <ITEM>
              <ITEMNUMBER>60RD2</ITEMNUMBER>
              <ITEMQTY>1</ITEMQTY>
            </ITEM>
            <ITEM>
              <ITEMNUMBER>KF3P2</ITEMNUMBER>
              <ITEMQTY>1</ITEMQTY>
            </ITEM>
          </ITEMS>
        </TIE>
      </TIES>
	</ORDER>
  </ORDERS>`

XML 2:
`  <ORDERS>
     <ORDER>
	 <ORDERNUM>979793524</ORDERNUM>
      <TIES>
        <TIE>
          <TIENUMBER>1</TIENUMBER>
          <TIEQTY>1</TIEQTY>
          <ITEMS>
             <ITEM>
              <ITEMNUMBER>KF3P2</ITEMNUMBER>
              <ITEMQTY>1</ITEMQTY>
            </ITEM>
            <ITEM>
              <ITEMNUMBER>60RD2</ITEMNUMBER>
              <ITEMQTY>1</ITEMQTY>
            </ITEM>
          </ITEMS>
        </TIE>
      </TIES>
	</ORDER>
  </ORDERS>`

**Comment by bodewig** [comment]
You are using XMLUnit 1.x or the legacy module of XMLUnit 2.x, I strongly recommend you avoid either of them.

You need to tell XMLUnit which `ORDER` node has to be matched against which other `ORDER` node. I have to guess but most likely your `ORDER`s are identified by the text nested into the `ORDERNUM` child. This is exactly the example of https://github.com/xmlunit/user-guide/wiki/SelectingNodes just replace `tr` with `ORDER` and `th` with `ORDERNUM`.

So one possible answer is you need to use XMLUnit 2.x (looking at the boilerplate code you have written you may like `DiffBuilder`) and hand it an `ElementSelector` like

```
ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("ORDER").thenUse(ElementSelectors.byXPath("./ORDERNUM", ElementSelectors.byNameAndText))
    .elseUse(ElementSelectors.byName)
    .build();
```

**Comment by vramsprsk** [comment]
Thanks a lot @bodewig for your reply i will try as suggested by you get back to you soon on the update.

**Comment by mohannune** [comment]
Hi Sir,

I need to compare two xmls.I am using XMl Unit. I have 5 nodes in Control Xml and I removed Node 2 in Test Xml.  While Comparing Node 2 in control Xml is compared with Node 3 in Test Xml and it goes Node3 in control Xml with Node 4 in Test Xml... it goes till end with multiple mismatches. 

I need to compare show only Which Node is missing and Which Node is added. Please provide the code to my required behavior.

Here is my Java Code.

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Iterator;
import java.util.LinkedHashSet;

import org.xmlunit.builder.DiffBuilder;
import org.xmlunit.diff.DefaultNodeMatcher;
import org.xmlunit.diff.Diff;
import org.xmlunit.diff.Difference;
import org.xmlunit.diff.ElementSelectors;

public class XMLDifference {
public static void main(String[] args) {
File actual = new File("D:\\workspace\\XMLUnitCompare\\src\\source.xml");
File expected = new File("D:\\workspace\\XMLUnitCompare\\src\\target.xml");
String control = null;
String test = null;
try {
control = new String(Files.readAllBytes(Paths.get(actual.toString())));
test = new String(Files.readAllBytes(Paths.get(expected.toString())));
} catch (IOException e) {
e.printStackTrace();
}


Diff documentDiff = DiffBuilder.compare(control).ignoreWhitespace().ignoreComments().normalizeWhitespace().withTest(test).withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))
.checkForSimilar().build();

int i = 0;
Iterator d = documentDiff.getDifferences().iterator();
LinkedHashSet set = new LinkedHashSet();
if (documentDiff.hasDifferences()) {
while(d.hasNext()) {
System.out.println((++i) + ") " + d.next());
}
}
}
}

Here are my XMLs

Control Xml :

<?xml version="1.0"?>
<catalog>
   <book name="bk101">
      <author>Gambardella, Matthew</author>
      <title>XML Developer's Guide</title>
      <genre>Computer</genre>
      <price>44.95</price>
      <publish_date>2000-10-01</publish_date>
      <description>An in-depth look at creating applications 
      with XML.</description>
   </book>
   <book name="bk102">
      <author>Ralls, Kim</author>
      <title>Midnight Rain</title>
      <genre>Fantasy</genre>
      <price>5.95</price>
      <publish_date>2000-12-16</publish_date>
      <description>A former architect battles corporate zombies, 
      an evil sorceress, and her own childhood to become queen 
      of the world.</description>
   </book>
   <book name="bk103">
      <author>Corets, Eva</author>
      <title>Maeve Ascendant</title>
      <genre>Fantasy</genre>
      <price>5.95</price>
      <publish_date>2000-11-17</publish_date>
      <description>After the collapse of a nanotechnology 
      society in England, the young survivors lay the 
      foundation for a new society.</description>
   </book>
   <book name="bk104">
      <author>Corets, Eva</author>
      <title>Oberon's Legacy</title>
      <genre>Fantasy</genre>
      <price>5.95</price>
      <publish_date>2001-03-10</publish_date>
      <description>In post-apocalypse England, the mysterious 
      agent known only as Oberon helps to create a new life 
      for the inhabitants of London. Sequel to Maeve 
      Ascendant.</description>
   </book>
  
</catalog>


Test Xml   :                                                                                                                                                               

<?xml version="1.0"?>
<catalog>
   <book name="bk101">
      <author>Gambardella, Matthew</author>
      <title>XML Developer's Guide</title>
      <genre>Computer</genre>
      <price>44.95</price>
      <publish_date>2000-10-01</publish_date>
      <description>An in-depth look at creating applications 
      with XML.</description>
   </book>
   <book name="bk1021">
      <author>Ralls, Kim</author>
      <title>Midnight Rain</title>
      <genre>Fantasy</genre>
      <price>5.95</price>
      <publish_date>2000-12-16</publish_date>
      <description>A former architect battles corporate zombies, 
      an evil sorceress, and her own childhood to become queen 
      of the world.</description>
   </book>   
   <book name="bk104">
      <author>Corets, Eva</author>
      <title>Oberon's Legacy</title>
      <genre>Fantasy</genre>
      <price>5.95</price>
      <publish_date>2001-03-10</publish_date>
      <description>In post-apocalypse England, the mysterious 
      agent known only as Oberon helps to create a new life 
      for the inhabitants of London. Sequel to Maeve 
      Ascendant.</description>
   </book>
   <book name="bk105">
      <author>Corets, Eva</author>
      <title>The Sundered Grail</title>
      <genre>Fantasy</genre>
      <price>5.95</price>
      <publish_date>2001-09-10</publish_date>
      <description>The two daughters of Maeve, half-sisters, 
      battle one another for control of England. Sequel to 
      Oberon's Legacy.</description>
   </book>
 </catalog>

**Comment by bodewig** [comment]
@mohannune your comment i not related to this issue, please create a new issue if you've got a new question.
