### ISSUE TITLE
Complex XML comparison fails when namespace included

### ISSUE THREAD

**Issue by LuckyMik** [xmlunit/xmlunit#143]
I am attempting to use XMLUnit for the first time to compare two somewhat complex XML documents.  I am facing an issue matching two "similar" documents.  I noticed behavior that I could not explain.  The XML matches when comparing if I strip all namespaces, but fails to match when the namespace is present even though the relevant portions of both documents are contained entirely within a single namespace.  I started attempting purely byXPath and byNameAndText/byName ElementSelectors due to the complex nature of the match and fell back to also using ByNameAndTextRecSelector, but neither are providing the desired result.  I acknowledge that XMLUnit is still new for me, and I may be missing a basic function, but could not explain why my "comparison logic" was matching without namespaces and failing when they are introduced.  Sample below:

Base Document:
```
<z>
  <a>
    <b>
      <ca>1</ca>
      <cb>1</cb>
      <cc>1</cc>
    </b>
    <d>
      <e>
        <ca>99</ca>
        <cb>99</cb>
        <cc>99</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>98</ca>
        <cb>98</cb>
        <cc>98</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>97</ca>
        <cb>97</cb>
        <cc>97</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>96</ca>
        <cb>96</cb>
        <cc>96</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>95</ca>
        <cb>95</cb>
        <cc>95</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>94</ca>
        <cb>94</cb>
        <cc>94</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>93</ca>
        <cb>93</cb>
        <cc>93</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>92</ca>
        <cb>92</cb>
        <cc>92</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>91</ca>
        <cb>91</cb>
        <cc>91</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>90</ca>
        <cb>90</cb>
        <cc>90</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>89</ca>
        <cb>89</cb>
        <cc>89</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>88</ca>
        <cb>88</cb>
        <cc>88</cc>
      </e>
    </d>
  </a>
  <a>
    <b>
      <ca>2</ca>
      <cb>2</cb>
      <cc>2</cc>
    </b>
    <d>
      <e>
        <ca>87</ca>
        <cb>87</cb>
        <cc>87</cc>
      </e>
    </d>
  </a>
  <a>
    <b>
      <ca>3</ca>
      <cb>3</cb>
      <cc>3</cc>
    </b>
    <d>
      <e>
        <ca>86</ca>
        <cb>86</cb>
        <cc>86</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>85</ca>
        <cb>85</cb>
        <cc>85</cc>
      </e>
    </d>
  </a>
  <a>
    <b>
      <ca>4</ca>
      <cb>4</cb>
      <cc>4</cc>
    </b>
    <d>
      <e>
        <ca>84</ca>
        <cb>84</cb>
        <cc>84</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>83</ca>
        <cb>83</cb>
        <cc>83</cc>
      </e>
    </d>
  </a>
</z>
```
Test Document:
```
<z>
  <a>
    <b>
      <ca>1</ca>
      <cb>1</cb>
      <cc>1</cc>
    </b>
    <d>
      <e>
        <ca>99</ca>
        <cb>99</cb>
        <cc>99</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>98</ca>
        <cb>98</cb>
        <cc>98</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>97</ca>
        <cb>97</cb>
        <cc>97</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>96</ca>
        <cb>96</cb>
        <cc>96</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>95</ca>
        <cb>95</cb>
        <cc>95</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>94</ca>
        <cb>94</cb>
        <cc>94</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>93</ca>
        <cb>93</cb>
        <cc>93</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>92</ca>
        <cb>92</cb>
        <cc>92</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>91</ca>
        <cb>91</cb>
        <cc>91</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>90</ca>
        <cb>90</cb>
        <cc>90</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>89</ca>
        <cb>89</cb>
        <cc>89</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>88</ca>
        <cb>88</cb>
        <cc>88</cc>
      </e>
    </d>
  </a>
  <a>
    <b>
      <ca>2</ca>
      <cb>2</cb>
      <cc>2</cc>
    </b>
    <d>
      <e>
        <ca>87</ca>
        <cb>87</cb>
        <cc>87</cc>
      </e>
    </d>
  </a>
  <a>
    <b>
      <ca>4</ca>
      <cb>4</cb>
      <cc>4</cc>
    </b>
    <d>
      <e>
        <ca>83</ca>
        <cb>83</cb>
        <cc>83</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>84</ca>
        <cb>84</cb>
        <cc>84</cc>
      </e>
    </d>
  </a>
  <a>
    <b>
      <ca>3</ca>
      <cb>3</cb>
      <cc>3</cc>
    </b>
    <d>
      <e>
        <ca>85</ca>
        <cb>85</cb>
        <cc>85</cc>
      </e>
    </d>
    <d>
      <e>
        <ca>86</ca>
        <cb>86</cb>
        <cc>86</cc>
      </e>
    </d>
  </a>
</z>
```
With these documents, the following comparison logic works:
```
DiffBuilder.compare(Input.fromString(baseDocument))
                   .withTest(Input.fromString(testDocument))
                   .checkForSimilar()
                   .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.selectorForElementNamed("a",ElementSelectors.byXPath("./b",new ByNameAndTextRecSelector())),new ByNameAndTextRecSelector(),ElementSelectors.byName))
                   .build()
```
However, when adding a namespace (any single namespace) to every element such as:
```
<ns2:z xmlns:ns2="http://test.xml">
  <ns2:a>
...
   </ns2:a>
</ns2:z>
```
the comparison fails, never matching the XPath and the subsequent ElementSelectors are not enough to match the documents.

**Comment by LuckyMik** [comment]
Krystian,
     Thank you, that is likely the basic piece that I was missing.  I tried
with the namespace map but then naively failed to add the namespace prefix
back to the xpath even though I had it there in earlier iterations.  I will
attempt and advise.

Thanks,
Mark

On Friday, September 21, 2018, krystiankaluzny <notifications@github.com>
wrote:

> The byXPath method have overloaded version with *prefix2Uri* map as
> second parameter.
> Provide Uri for *ns2* prefix/namespace as well with using the namespace
> in your xpath and everything should work.
>
> Map<String, String> prefix2Uri = Collections.singletonMap("ns2", "http://test.xml");ElementSelectors.byXPath("./ns2:b", prefix2Uri, new ByNameAndTextRecSelector())
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_xmlunit_xmlunit_issues_143-23issuecomment-2D423695737&d=DwMFaQ&c=pLULRYW__RtkwsQUPxJVDGboCTdgji3AcHNJU0BpTJE&r=D369TO2UQDM30REgjJyH_5LbT2M7fq9TPfi7V6RQeyA&m=vp7XpLeDJKzY8vQoSBpzL7Vtz0wBIlpytP5pZBzozwk&s=ECUjlzd2jUss4JACDi0BnLtQeOk8T2YVB50x7_PNEuY&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbzOsLIknevGG-2DLif2n38fr8jF3dgODiks5udXVfgaJpZM4W00p-2D&d=DwMFaQ&c=pLULRYW__RtkwsQUPxJVDGboCTdgji3AcHNJU0BpTJE&r=D369TO2UQDM30REgjJyH_5LbT2M7fq9TPfi7V6RQeyA&m=vp7XpLeDJKzY8vQoSBpzL7Vtz0wBIlpytP5pZBzozwk&s=HkelmaHybAo2Me3kc_x9GvzNf2eTZVmABjTxTjBLCPE&e=>
> .
>


-- 

*Mark Mikkelson*

*Master Software Engineer, Manager / DigiTech*

804.393.1542 (cell)

Mark.Mikkelson@capitalone.com <Firstname.Lastname@capitalone.com>
________________________________________________________

The information contained in this e-mail is confidential and/or proprietary to Capital One and/or its affiliates and may only be used solely in performance of work or services for Capital One. The information transmitted herewith is intended only for use by the individual or entity to which it is addressed. If the reader of this message is not the intended recipient, you are hereby notified that any review, retransmission, dissemination, distribution, copying or other use of, or taking of any action in reliance upon this information is strictly prohibited. If you have received this communication in error, please contact the sender and delete the material from your computer.

**Comment by LuckyMik** [comment]
Krystian,
    That was it.  It worked like a charm.  The overloaded method is
referenced in the javadoc and also in the SelectingNodes wiki page in he
xmlunit user-guide but I do not feel like a good example is shown.  I was
also not able to find a good reference through considerable internet
searching.  Maybe most have not hit this issue as I should have namespaced
my xpath after including the declaration in the map, but I still feel that
it would be a worthwhile addition to that SelectingNodes wiki page.  Either
way, thanks again and sorry for raising such a trivial issue, but I greatly
appreciate the quick and informative response.

Sincerely,
Mark

On Friday, September 21, 2018, Mark Mikkelson <mark.mikkelson@capitalone.com>
wrote:

> Krystian,
>      Thank you, that is likely the basic piece that I was missing.  I
> tried with the namespace map but then naively failed to add the namespace
> prefix back to the xpath even though I had it there in earlier iterations.
> I will attempt and advise.
>
> Thanks,
> Mark
>
> On Friday, September 21, 2018, krystiankaluzny <notifications@github.com>
> wrote:
>
>> The byXPath method have overloaded version with *prefix2Uri* map as
>> second parameter.
>> Provide Uri for *ns2* prefix/namespace as well with using the namespace
>> in your xpath and everything should work.
>>
>> Map<String, String> prefix2Uri = Collections.singletonMap("ns2", "http://test.xml");ElementSelectors.byXPath("./ns2:b", prefix2Uri, new ByNameAndTextRecSelector())
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_xmlunit_xmlunit_issues_143-23issuecomment-2D423695737&d=DwMFaQ&c=pLULRYW__RtkwsQUPxJVDGboCTdgji3AcHNJU0BpTJE&r=D369TO2UQDM30REgjJyH_5LbT2M7fq9TPfi7V6RQeyA&m=vp7XpLeDJKzY8vQoSBpzL7Vtz0wBIlpytP5pZBzozwk&s=ECUjlzd2jUss4JACDi0BnLtQeOk8T2YVB50x7_PNEuY&e=>,
>> or mute the thread
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbzOsLIknevGG-2DLif2n38fr8jF3dgODiks5udXVfgaJpZM4W00p-2D&d=DwMFaQ&c=pLULRYW__RtkwsQUPxJVDGboCTdgji3AcHNJU0BpTJE&r=D369TO2UQDM30REgjJyH_5LbT2M7fq9TPfi7V6RQeyA&m=vp7XpLeDJKzY8vQoSBpzL7Vtz0wBIlpytP5pZBzozwk&s=HkelmaHybAo2Me3kc_x9GvzNf2eTZVmABjTxTjBLCPE&e=>
>> .
>>
>
>
> --
>
> *Mark Mikkelson*
>
> *Master Software Engineer, Manager / DigiTech*
>
> 804.393.1542 (cell)
>
> Mark.Mikkelson@capitalone.com <Firstname.Lastname@capitalone.com>
>
>

-- 

*Mark Mikkelson*

*Master Software Engineer, Manager / DigiTech*

804.393.1542 (cell)

Mark.Mikkelson@capitalone.com <Firstname.Lastname@capitalone.com>
________________________________________________________

The information contained in this e-mail is confidential and/or proprietary to Capital One and/or its affiliates and may only be used solely in performance of work or services for Capital One. The information transmitted herewith is intended only for use by the individual or entity to which it is addressed. If the reader of this message is not the intended recipient, you are hereby notified that any review, retransmission, dissemination, distribution, copying or other use of, or taking of any action in reliance upon this information is strictly prohibited. If you have received this communication in error, please contact the sender and delete the material from your computer.

**Comment by krystiankaluzny** [comment]
I added small example of using byXPath with namespace context to SelectingNodes page.
