### ISSUE TITLE
Ignore sequence difference in Assert

### ISSUE THREAD

**Issue by rahuldeepak** [xmlunit/xmlunit#144]
I am getting the following output for my XML comparison.

Expected child nodelist sequence '0' but was '1' - comparing <docElement...> at /document[1]/docElement[1] to <docElement...> at /document[1]/docElement[2] (DIFFERENT)
Expected child nodelist sequence '1' but was '0' - comparing <docElement...> at /document[1]/docElement[2] to <docElement...> at /document[1]/docElement[1] (DIFFERENT)

What I understand from this difference is "The sequence of the elements is different else XML are same".
In assert, I want both the XML are same ignoring this difference. How can I do that?

**Comment by krystiankaluzny** [comment]
Normally to ignore nodelist sequence it's enought to use 'check for similarity' instead 'check for identical'. Default DifferenceEvaluator treats difference in nodelist sequence as similarity. But **(DIFFERENT)** in your log shows that you probably dont't use basic configuration, so the solution may be different. If you provide your Diff configuration, I will probably say more about ignore nodelist sequence.
