### ISSUE TITLE
Unable to resolve one case with attribute order

### ISSUE THREAD

**Issue by nikolakurtic** [xmlunit/xmlunit#146]
Hi, I have a trouble testing equality of two xml-s:

control:
`<result>
   <node>
      <label lang="de">Label</label>
      <label lang="en">Label</label>
      <node>
         <label lang="de">Label</label>
         <label lang="en">Label</label>
      </node>
   </node>
</result>`

test:
`<result>
   <node>
      <label lang="en">Label</label>
      <label lang="de">Label</label>
      <node>
         <label lang="en">Label</label>
         <label lang="de">Label</label>
      </node>
   </node>
</result>`

Notice that order of label element is reversed by the lang attribute, and that there can be nested nodes in side a node.

I tried:
`Diff d = DiffBuilder.compare(control)..withTest(test)
.withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))
                .checkForSimilar()
                .build()`

and also:
`Diff d = DiffBuilder.compare(control)..withTest(test)
.checkForSimilar()
                .withNodeMatcher(new DefaultNodeMatcher(
                ElementSelectors.conditionalBuilder()
                        .whenElementIsNamed("label").thenUse(ElementSelectors.byXPath("./lang", ElementSelectors.byNameAndText))
                        .elseUse(ElementSelectors.byNameAndText).build())).build()`

but without success...

**Comment by bodewig** [comment]
`byNameAndText` uses the elements name and its nested text to determine which elements to compare. As your `label` elements are supposed to be matched by their `lang` attribute rather than their nested text it would seem that `byNameAndAttribute("lang")` is the better choice.

Maybe you want to only compare elements with the same `lang` attribute and nested text, in that case you could use `and(byNameAndAttribute("lang"), byNameAndText())`.

**Comment by nikolakurtic** [comment]
I did not get it how to combine two selectors.

**Comment by bodewig** [comment]
Sorry, I'm not sure whether I understand your response.

You *did not* get how to combine selectors but now do after I mentioned `ElementSelectors.and` or you still don't and need more details?

In you example you don't need a conditional matcher or XPath at all, but your real XML may be more complex than what you've shown.

**Comment by bodewig** [comment]
I'll assume the question has been answered.
