### ISSUE TITLE
Contribute placeholder documentation

### ISSUE THREAD

**Issue by zheng-wang** [xmlunit/xmlunit#147]
I am seeking to add documentation for the placeholder feature introduced since XMLUnit 2.6.0.

I created one wiki page [Placeholders](https://github.com/zheng-wang/xmlunit/wiki/Placeholders). Could @bodewig please review/modify and indicate how to add the content to the XMLUnit doc system?

**Comment by bodewig** [comment]
Thank you @zheng-wang the best place for this would be the Wiki inside of the [User Guide](https://github.com/xmlunit/user-guide/wiki) repository - which is open to be edited by anyone.

I have just quickly glanced over what you've written and not looked into it in detail, but being a wiki, we can easily go from there with incremental improvements. Feel free to add the page and add a link to it inside of the sidebar wherever you think it fits best (I'd go for either putting it under Utilities or adding a new top level section).

**Comment by zheng-wang** [comment]
This is easy and cool. I have moved the content to [User Guide](https://github.com/xmlunit/user-guide/wiki), under Utilities. Hopefully we and anyone else could improve it over time.

**Comment by bodewig** [comment]
many thanks
