### ISSUE TITLE
Make XmlAssert constructor non-private to allow SoftAssertions for XmlAssert

### ISSUE THREAD

**Issue by ava1ar** [xmlunit/xmlunit#148]
I am trying to integration XmlAssert with the SoftAssertion feature of AssertJ. To achieve this I am creating following class:

```java
public class XmlSoftAssertions extends SoftAssertions {

    public XmlAssert assertXml(String xmlBody) {
        return proxy(XmlAssert.class, Object.class, xmlBody);
    }
}
```

But this is not working, since SoftAssetion proxy creation internally trying to access the constructor and instantiate the actual instance of `XmlAssert`:

```java
...
Class<? extends V> proxyClass = createSoftAssertionProxyClass(assertClass);
Constructor<? extends V> constructor = proxyClass.getConstructor(actualClass);
V proxiedAssert = constructor.newInstance(actual);
...
```

This is failing because right now `XmlAssert` has private constructor. Is there any reason keeping it private? Can we make it public or at least package-private to allow SoftAssertions integration?

I will write the wiki page about the SoftAssetion ntegration with xmlunit-assertj, if we make it work.

**Comment by krystiankaluzny** [comment]
Hi @ava1ar 
Constructors are private because there was no reason to make them more visible :) 
So you can make it package-private or public, if it's necessary.

Probably changes in `XmlAssert` may not be enough. If you look at XmlAssert implementation, then you find out that some methods return different types of assert class, eg public `nodesByXPath` return `MultipleNodeAssert`

In following example `AssertionError` will be thrown from **haveAttribute** not form **assertAll**.
```java
XmlSoftAssertions softly = new XmlSoftAssertions();
softly.assertXml(xml)
      .nodesByXPath("/feed/entry")
      .haveAttribute("attr");
softly.assertAll();
```

**Comment by krystiankaluzny** [comment]
Making xmlunit-assertj module compatible with the SoftAssertion feature requires deep code changing. The reason for that is that the xmlunit-assertj doesn't have only one an Assertion class. It has one entry class `XmlAssert` but depending on called method current assertions class changed to provide specific functionalities.
To make the SoftAssertion work properly is require to provide proxy for `CompareAssert`, `MultipleNodeAssert`, `SingleNodeAssert`, `ValidationAssert`, `ValueAssert`.
Currently, I don't see the need to make such a big change.
