### ISSUE TITLE
Make Placeholder Difference Evaluator Bidirectional

### ISSUE THREAD

**Issue by slackerjack1943** [xmlunit/xmlunit#150]
The XML tests I'm working on rely upon using expected XML from the old system that is being replaced with a new one and doing a like for like comparison with actual XML being generated by the new system.  Only certain fields are relevant to the comparison, and we would like to ignore element text differences for most nodes.

When writing tests which assert on XML content and structure, it would be nice to leave the "expected" XML from the legacy system untouched and mark fields in the "actual" XML being generated by the new system as ${xmlunit.ignore} when they are not relevant to the comparison.

This would involve switching the role of controlText and testText in the evaluateConsideringPlaceholders method.    

Perhaps another distinct difference evaluator?  InvertedPlaceholderDifferenceEvaluator?

**Comment by bodewig** [comment]
In my view the control document is the thing that describes how the output is supposed to look like and the test document is what your code creates and what you want to test. Adding `${xmlunit.ignore}` to the test document means you are testing something that is not the document generated by your production code but something else.

I understand your use case but feel making placeholders symmetric that way would blur the distinction between control and test too much. A different `DifferenceEvaluator` would be possible but honestly doesn't feel right to me. Including it with the XMLUnit distribution, that is, if you want to use it for your own tests you can easily implement it and configure XMLUnit to use it.

**Comment by bodewig** [comment]
Coming back to this before I close it as WONTFIX.

Wouldn't `NodeFilter` be a more natural approach to your use case? What I mean is you could trim down the legacy document to the parts you really are trying to recreate by throwing out all the other nodes that you would ignore in your approach.

**Comment by bodewig** [comment]
I think there are better approaches to the problem and the idea of bidirectional placeholders doesn't feel right to me.
