### ISSUE TITLE
How to ignore set of elements while comparing two XML files

### ISSUE THREAD

**Issue by KiranBolaj1** [xmlunit/xmlunit#151]
Hi,
Lets consider, file1.xml - 

`<Employee id = 1>
       <name  initial="A">Ana</name>
       <salary>10000</salary>
       <designation>SDE<designation>
       <role>Developer</role>
       <team>ABC</team>
</Employee>
<Employee id = 2>
       <name  initial="P">Paul</name>
       <salary>30000</salary>
       <designation>SDET<designation>
       <role>Developer</role>
       <team>BCD</team>
</Employee>`

and file2.xml

`<Employee id = 1>
       <name  initial="A">Ana</name>
       <salary>60000</salary>
       <designation>SDET<designation>
       <role>Component Engineer</role>
       <team>BCD</team>
</Employee>
<Employee id = 2>
       <name  initial="P">Paul</name>
       <salary>20000</salary>
       <designation>SDET<designation>
       <role>Automation Developer</role>
       <team>CBD</team>
</Employee>`

I want to ignore `<salary>, <role> and <team>` elements, while comparing the above two XML files. After comparing the above files, I should not get any differences if I ignore the  `<salary>, <role> and <team>` elements.
How can I achieve this?

**Comment by bodewig** [comment]
`NodeFilter` would be the piece of XMLUnit to use for something like this. In its most trivial form (assuming Java8 for now)

```java
.withNodeFilter(n -> !"salary".equals(n.getNodeName()) && !"role".equals(n.getNodeName()) && !"team".equals(n.getNodeName()))
```

might work. The predicate becomes more complex if you use XML namespaces (see `Nodes.getQName` for something that might help you) or want to not ignore `salary` in different context (you may need to look at the parent node of `n` to ensure it is an `Employee` element).
