### ISSUE TITLE
Implement isNumber placeholder

### ISSUE THREAD

**Issue by NathanAtClarity** [xmlunit/xmlunit#153]
The page about placeholders on the wiki (https://github.com/xmlunit/user-guide/wiki/Placeholders) describes an example placeholder `isNumber`

The implementation of this placeholder should:
* work on attribute and element values (in the same way that `ignore` does) 
* allow the diff engine to identify differences if the attribute or element value cannot be parsed as a number
* acceptable numbers include positive and negative integers, positive and negative floating point numbers, and positive and negative floating point numbers in engineering notation

**Comment by NathanAtClarity** [comment]
I have already written some code that provisionally supports the above (to support another project that uses `xmlunit`) so I would be happy to productionize my code and submit it as a PR

**Comment by bodewig** [comment]
A PR would be wonderful, thank you.

**Comment by bodewig** [comment]
fixed via #154
