### ISSUE TITLE
Comparing XMLs with unordered nodes as well as unorderd attributes.

### ISSUE THREAD

**Issue by CKUser123** [xmlunit/xmlunit#155]
**XML1**
```

<Values>
	<Match Code="ABC" ItemCode="NONE" PreferenceMatchIndicator="true"/>
	<Match Code="JLM" ItemCode="1" PreferenceMatchIndicator="true"/>
	<Data Name="XCTBest-3" Type="UNAVAILABLE">
		<DataValue Key="AA" Value="3"/>
		<DataValue Key="BB" Value="ZZZ"/>
		<DataValue Key="CC" Value="1O"/>
	</Data>
	<Data Name="XCTBest-1" Type="ADDITIONAL_OFFER_DATA">
		<DataValue Key="DD" Value="1"/>
		<DataValue Key="CC" Value="QQ"/>
		<DataValue Key="AA" Value="Best"/>
	</Data>
</Values>

```
**XML2**

```
<Values>
	<Match Code="JLM" ItemCode="1" PreferenceMatchIndicator="true"/>
	<Match Code="ABC" ItemCode="NONE"> PreferenceMatchIndicator="true"/>
<Data Name="XCTBest-3" Type="UNAVAILABLE">
		<DataValue Key="CC" Value="1O"/>
		<DataValue Key="AA" Value="3"/>
		<DataValue Key="BB" Value="ZZZ"/>
	</Data>
	<Data Name="XCTBest-1" Type="ADDITIONAL_OFFER_DATA">
		<DataValue Key="CC" Value="QQ"/>		
		<DataValue Key="DD" Value="1"/>
		<DataValue Key="AA" Value="***_Different_***"/>
	</Data>
</Values>
```

Both the XMLS are the same, except 
1 )The order of "Match " is different
2)The order of "DataValue " is different.
3) Value of on DataValue tag in Data[2] is different.

on using .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndAllAttributes))

Im getting the below differences.

Difference 1: Expected child nodelist sequence '0' but was '1' - comparing at /Values[1]/Match[1] to at /Values[1]/Match[2] (DIFFERENT)
Difference 2: Expected child nodelist sequence '1' but was '0' - comparing at /Values[1]/Match[2] to at /Values[1]/Match[1] (DIFFERENT)
Difference 3: Expected child nodelist sequence '0' but was '1' - comparing at /Values[1]/Data[1]/DataValue[1] to at /Values[1]/Data[1]/DataValue[2] (DIFFERENT)
Difference 4: Expected child nodelist sequence '1' but was '2' - comparing at /Values[1]/Data[1]/DataValue[2] to at /Values[1]/Data[1]/DataValue[3] (DIFFERENT)
Difference 5: Expected child nodelist sequence '2' but was '0' - comparing at /Values[1]/Data[1]/DataValue[3] to at /Values[1]/Data[1]/DataValue[1] (DIFFERENT)
Difference 6: Expected child nodelist sequence '0' but was '1' - comparing at /Values[1]/Data[2]/DataValue[1] to at /Values[1]/Data[2]/DataValue[2] (DIFFERENT)
Difference 7: Expected child nodelist sequence '1' but was '0' - comparing at /Values[1]/Data[2]/DataValue[2] to at /Values[1]/Data[2]/DataValue[1] (DIFFERENT)

This makes sense but i don't want any difference to be thrown. The only error i want thrown is where the Value(***Different***)  is different in the DataValue tag in Data[2].

Can you please help me on how to write the ElementSelectors for this?
Thank you.

**Comment by bodewig** [comment]
You can see your `ElementSelector` is working as it figures out your `Math` elements are swapped. If it didn't pick the correct pair you'd see differences about the attribute values of `Match[1]` being different and so on.

Even if you configure `ElementSelector` correctly the difference in element order remains and is considered a `SIMILAR` difference by the `Default` `DifferenceEvaluator`. To me it looks as if you were overriding the `DifferenceEvaluator` with one that turns the sequence difference into a `DIFFERENT` difference. Can you show more of your configuration?

Finally as you are using `ElementSelectors.byNameAndAllAttributes` any difference in attribute values will not manifest as such but rather as a difference of the `CHILD_LOOKUP` type. As there is a mismatch in attribute values the selector will not find a matching pair at all. I am surprised to not see them in your example. Here a different approach would be to configure the `ElementSelector` more fine grained using a conditional builder, something like

```
ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("Match").thenUse(ElementSelectors.byNameAndAttributes("Code", "ItemCode"))
    .whenElementIsNamed("DataValue").thenUse(ElementSelectors.byNameAndAttributes("Key",))
    .elseUse(ElementSelectors.byName)
    .build()
```

but this may be too simplistic for your full case.

**Comment by CKUser123** [comment]
@bodewig This is what i am using in my script
```

Diff myDiff = DiffBuilder.compare(eai).withTest(coreApi).ignoreWhitespace().normalizeWhitespace()
					.withDifferenceEvaluator(
							DifferenceEvaluators.chain((new IgnoreAttributeDifferenceEvaluator(attributes[0])),
									(new IgnoreAttributeDifferenceEvaluator(attributes[1])),
									(new IgnoreAttributeDifferenceEvaluator(attributes[2]))))
					.withNodeFilter(node -> (!node.getNodeName().equals(nodes[0]))
							&& (!node.getNodeName().equals(nodes[1])) && (!node.getNodeName().equals(nodes[2])))
					.withNodeMatcher((new DefaultNodeMatcher(ElementSelectors.byNameAndAllAttributes)))
					.checkForSimilar().build();


```

I'm using the difference elevator to ignore node and attributes in both XML (the header tags)

**Comment by bodewig** [comment]
You probably need to add `DifferenceEvaluators.Default` as the first argument into your chain.

**Comment by CKUser123** [comment]
I modified it as below and now i am getting the expected differences in value but now i am also getting these errors

Expected child nodelist sequence '1' but was '7' - 
 Expected child nodelist sequence '3' but was '4' -

Is there anyway not to get these errors?
 ```

Diff myDiff = DiffBuilder.compare(eai).withTest(coreApi).ignoreWhitespace().normalizeWhitespace()
					.withDifferenceEvaluator(
							DifferenceEvaluators.chain(DifferenceEvaluators.Default,(new IgnoreAttributeDifferenceEvaluator(attributes[0])),
									(new IgnoreAttributeDifferenceEvaluator(attributes[1])),
									(new IgnoreAttributeDifferenceEvaluator(attributes[2]))))
					.withNodeFilter(node -> (!node.getNodeName().equals(nodes[0]))
							&& (!node.getNodeName().equals(nodes[1])) && (!node.getNodeName().equals(nodes[2])))
					.withNodeMatcher((new DefaultNodeMatcher(ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("Match").thenUse(ElementSelectors.byNameAndAttributes("Code", "ItemCode"))
    .whenElementIsNamed("DataValue").thenUse(ElementSelectors.byNameAndAttributes("Key"))
    .elseUse(ElementSelectors.byName)
    .build())))
							.build();

```

**Comment by bodewig** [comment]
Most likely your `ElementSelectors.byNameAndAllAttributes` also helped matching the correct siblings of a different kind of element somewhere else in your document in an area you didn't show. You could add cases for them as well (that's the "too simplistic" part of my initial answer :-).

Or there might be only a handful of attributes that uniquely identify elements that are supposed to be matched and you can use that one without any conditional builder. `ElementSelectors.byNameAndAttributes("Code", "ItemCode", "Key")` would work for `Match` and `DataValue` as they either have the same value for each of those attributes or no value at all.

It really depends on your XML and there is no way to magically determine the "correct" `ElementSelector` - apart from #45 , maybe, which would be pretty demanding on CPU and memory - and the only one who knows what makes two elements in your XML "match" are you.

**Comment by CKUser123** [comment]
Thank you @bodewig for your help. I will keep trying to get it to work :)

**Comment by bodewig** [comment]
you're welcome.
