### ISSUE TITLE
How can get only particular elements mismatched along with parent element while comparing two xmls

### ISSUE THREAD

**Issue by KiranBolaj1** [xmlunit/xmlunit#157]
Hi,

After comparing the two xmls how can I fetch the mismatch elements along with parent element in xmls instead of getting long error message.

**Comment by bodewig** [comment]
You don't really say how you compare the XMLs. When using `DiffBuilder`'s `build` method, you receive a `Diff` instance which provides you with an `Iterable` of `Difference` instances. Each of these `Difference`s holds a reference to the DOM nodes that have been compared.

**Comment by bodewig** [comment]
I assume I've provided all the information you needed, otherwise please reopen this issue.
