### ISSUE TITLE
Comparing nodes with children

### ISSUE THREAD

**Issue by michailangelo** [xmlunit/xmlunit#158]
Lets say I have these strings for comparison:

String xml1 = `<persons><person><id>1</id><name><firstName>Johnny</firstName></name></person><person><id>2</id><name><firstName>John</firstName></name></person></persons>`

String xml2 = `<persons><person><id>2</id><name><firstName>John</firstName></name></person><person><id>1</id><name><firstName>John</firstName></name></person></persons>`

How can I compare them ignoring the element order?

**Comment by bodewig** [comment]
Please have a look at https://github.com/xmlunit/user-guide/wiki/SelectingNodes for what I hope to be a useful discussion of how XMLUnit decides which nodes to compare.

For a human reader the `person` elements ought to be compared that share the same text inside of the `id` child element. At least this is what I'd expect. This is what you need to tell XMLUnit when it looks at the `person` elements, and you do so by using an `ElementSelector` that matches what I've described above.

For the snippet alone

```java
ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("person").thenUse(ElementSelectors.byXPath("./id", ElementSelectors.byNameAndText))
    .elseUse(ElementSelectors.byName)
    .build();
```

will work. For a complete document you may need to specify more complex rules.

**Comment by michailangelo** [comment]
If 'id' didnt uniquely identify each 'person' element then I guess I would need multiple selectors. How could I achieve this?

Something like this : 
```
ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("person").thenUse(ElementSelectors.byXPath("./id", ElementSelectors.byNameAndText))
.whenElementIsNamed("person").thenUse(ElementSelectors.byXPath("./name/firstName", ElementSelectors.byNameAndText))
    .elseUse(ElementSelectors.byName)
    .build();
```
 didnt work :(

**Comment by bodewig** [comment]
You have to combine the selectors you need for a single condition. [and](https://github.com/xmlunit/user-guide/wiki/SelectingNodes#elementselectorsnot-and-or-and-xor) probably is what you want.

untested:

```java
ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("person")
    .thenUse(ElementSelectors.and(
        ElementSelectors.byXPath("./id", ElementSelectors.byNameAndText),
        ElementSelectors.byXPath("./name/firstName", ElementSelectors.byNameAndText)))
```

**Comment by michailangelo** [comment]
Apparently it runs successfully with only:```
 ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("person").thenUse(ElementSelectors.byXPath("./id", ElementSelectors.byNameAndText))
    .build();
```
even if I duplicate the nodes in the XML.

Anyway, my issue now is to make comparisons with name space inside an element. I guess I should open  a new issue.

Thanks for all the help bodewig!
