### ISSUE TITLE
Comparing nodes with namespace 

### ISSUE THREAD

**Issue by michailangelo** [xmlunit/xmlunit#159]
I have these Strings in xml format:

     `   String xml1 ="<Document xsi:schemaLocation=\"filename.xsd\" xmlns=\"namespace\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><Header><Subheader>subheader</Subheader></Header><persons><person><Id>1</Id><name><firstName>george</firstName><lastName>White</lastName></name></person><person><Id>2</Id><name><firstName>John</firstName><lastName>Black</lastName></name></person></persons></Document>";
`

    `   String xml2 ="<Document xsi:schemaLocation=\"filename.xsd\" xmlns=\"namespace\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><Header><Subheader>subheader</Subheader></Header><persons><person><Id>2</Id><name><firstName>John</firstName><lastName>Black</lastName></name></person><person><Id>1</Id><name><firstName>george</firstName><lastName>White</lastName></name></person></persons></Document>";
`

I am trying this snippet:

```
ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("person").thenUse(ElementSelectors.byXPath("./Id", ElementSelectors.byNameAndText))
    .elseUse(ElementSelectors.byNameAndText)
    .build();
```

but it finds differences. If I remove the namespace attibutes from 'Document' element then it finds no diffences, as expected. 

How can I make it compare the node with namespace attributes?

**Comment by bodewig** [comment]
Both `whenElementIsNamed` and `byXpath` also exist in namespace-aware variants, in your case likely something like `whenElementIsNamed(new QName("namespace", "person"))` and `byXPath("./ns:Id", Collections.singletonMap("ns", "namespace"), ElementSelectors.byNameAndText)`.

**Comment by michailangelo** [comment]
That solves the problem. Many many thanks!!

**Comment by bodewig** [comment]
great
