### ISSUE TITLE
Missing runtime dependencies in Java 9+

### ISSUE THREAD

**Issue by swismer** [xmlunit/xmlunit#162]
The following additional JAXB dependencies are required to run e.g. `Input.fromJaxb(...)` in Java 9+:
- `jaxb-core`
- `jaxb-impl`
- `activation`

In xmlunit-core/pom.xml, these are already listed, but are only available for the xmlunit internal tests.
External Maven projects adding a dependency on xmlunit therefore miss these libraries, because `test` scoped dependencies are not transitive. I would appreciate, if
- they could be either declared as `runtime` scoped dependencies (for Java 9+)
- or marked as `optional`, including some documentation that the JAXB features require adding these additional dependencies manually

**Comment by bodewig** [comment]
You are certainly right in that JAXB becomes an optional dependency of core in Java9+. So far I assumed that anybody who wants to test the XML serialization of an object - this is what `fromJaxb` does would be testing code that already depended on JAXB anyway - so didn't really think about making the dependency explicit.

**Comment by bodewig** [comment]
fixed in master, will be fixed for the next release.

Thank you for the report.
