### ISSUE TITLE
Matching Key/Value sibling XML pairs

### ISSUE THREAD

**Issue by beirtipol** [xmlunit/xmlunit#163]
I 'think' that this nodematcher should serve me, and it works for out-of-order elements, but is noisy when elements have a different 'Value/text()'

Am I missing something obvious?

Here is the matcher I use:
`new DefaultNodeMatcher( ElementSelectors.selectorForElementNamed("CustomData",
				ElementSelectors.byXPath("./Name", ElementSelectors.byNameAndText)),ElementSelectors.byNameAndText)`

I expect that Object1 and Object2 are identical and they are
Object1:
```xml
	<SomeObject>
		<CustomDataList>
			<CustomData>
				<Name>SettlementFXRate</Name>
				<Value>1234</Value>
			</CustomData>
			<CustomData>
				<Name>SettlementCurrency</Name>
				<Value>USD</Value>
			</CustomData>
		</CustomDataList>
                <SomeEasilyMatchedXML />
        </SomeObject>
```

Object2:
```xml
	<SomeObject>
		<CustomDataList>
			<CustomData>
				<Name>SettlementCurrency</Name>
				<Value>USD</Value>
			</CustomData>
			<CustomData>
				<Name>SettlementFXRate</Name>
				<Value>1234</Value>
			</CustomData>
		</CustomDataList>
                <SomeEasilyMatchedXML />
        </SomeObject>
```

I expect that Object3 and Object4 have 1 difference, which is the 'Value' node of CustomData[2]. However, I get 2 differences, 1 for 'null' test at and 1 for 'null' control.

In a debugger, I see the following in one difference, and the opposite in the next difference

controlDetail:
parentXPath: /SomeObject[1]/CustomDataList[1]/CustomData[2]
target: ElementNSImpl
value: QName
xpath: parentXPath: /SomeObject[1]/CustomDataList[1]/CustomData[2]/Value[1]

testDetail:
parentXPath: /SomeObject[1]/CustomDataList[1]/CustomData[2]
target: null
value: null
xpath: null

Object3:
```xml
	<SomeObject>
		<CustomDataList>
			<CustomData>
				<Name>SettlementFXRate</Name>
				<Value>1234</Value>
			</CustomData>
			<CustomData>
				<Name>SettlementCurrency</Name>
				<Value>USD</Value>
			</CustomData>
		</CustomDataList>
                <SomeEasilyMatchedXML />
        </SomeObject>
```

Object4:
```xml
	<SomeObject>
		<CustomDataList>
			<CustomData>
				<Name>SettlementFXRate</Name>
				<Value>1234</Value>
			</CustomData>
			<CustomData>
				<Name>SettlementCurrency</Name>
				<Value>EUR</Value>
			</CustomData>
		</CustomDataList>
                <SomeEasilyMatchedXML />
        </SomeObject>
```

**Comment by bodewig** [comment]
In general you should use a single `ElementSelector` with a conditional builder rather than multiple `ElementSelector`s to avoid strange side effects, see https://github.com/xmlunit/user-guide/wiki/SelectingNodes#using-more-than-one-elementselector-at-the-same-time

That would be

```java
new DefaultNodeMatcher(ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("CustomData")
    .thenUse(ElementSelectors.byXPath("./Name", ElementSelectors.byNameAndText))
    .elseUse(ElementSelectors.byNameAndText));
```

But on first glance I don't see why you don't get matches on Objects 3 and 4 and will have to try it myself.

**Comment by bodewig** [comment]
This is my test case

```java
import org.xmlunit.builder.*;
import org.xmlunit.diff.*;

public class XMLUnit163 {

    private static final String object3 = "<SomeObject>\n"
        + "		<CustomDataList>\n"
        + "			<CustomData>\n"
        + "				<Name>SettlementFXRate</Name>\n"
        + "				<Value>1234</Value>\n"
        + "			</CustomData>\n"
        + "			<CustomData>\n"
        + "				<Name>SettlementCurrency</Name>\n"
        + "				<Value>USD</Value>\n"
        + "			</CustomData>\n"
        + "		</CustomDataList>\n"
        + "                <SomeEasilyMatchedXML />\n"
        + "        </SomeObject>";
    private static final String object4 = "<SomeObject>\n"
        + "		<CustomDataList>\n"
        + "			<CustomData>\n"
        + "				<Name>SettlementFXRate</Name>\n"
        + "				<Value>1234</Value>\n"
        + "			</CustomData>\n"
        + "			<CustomData>\n"
        + "				<Name>SettlementCurrency</Name>\n"
        + "				<Value>EUR</Value>\n"
        + "			</CustomData>\n"
        + "		</CustomDataList>\n"
        + "                <SomeEasilyMatchedXML />\n"
        + "        </SomeObject>";
    
    public static void main(String[] args) {
        Diff myDiff = DiffBuilder.compare(object3).withTest(object4)
            .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.selectorForElementNamed("CustomData", ElementSelectors.byXPath("./Name", ElementSelectors.byNameAndText)),
                                                    ElementSelectors.byNameAndText))
            .build();
        for (Difference d : myDiff.getDifferences()) {
            System.err.println(d);
        }
    }
}
```

an I get

```
Expected child 'Value' but was 'null' - comparing <Value...> at /SomeObject[1]/CustomDataList[1]/CustomData[2]/Value[1] to <NULL> (DIFFERENT)
Expected child 'null' but was 'Value' - comparing <NULL> to <Value...> at /SomeObject[1]/CustomDataList[1]/CustomData[2]/Value[1] (DIFFERENT)
```

This is to be expected.

For everything that is not named `CustomData` you tell XMLUnit to select elements to compare by their tag names **and their nested text**.

XMLUnit has decided to compare `/SomeObject[1]/CustomDataList[1]/CustomData[2]` in Object 3 to `/SomeObject[1]/CustomDataList[1]/CustomData[1]` in Object 4 - this is what you want and expect.

Now when looking at the children of the respective `CustomData` elements it first finds `Name` elements that match in element name and in nested text. Then it looks at the `Value` elements and since their nested texts differ, it doesn't find partners to compare them with - and reacts with `CHILD_LOOKUP` differences.

If you change the second `ElementSelector` to be `ElementSelects.byName` then the result becomes

```
Expected text value 'USD' but was 'EUR' - comparing <Value ...>USD</Value> at /SomeObject[1]/CustomDataList[1]/CustomData[2]/Value[1]/text()[1] to <Value ...>EUR</Value> at /SomeObject[1]/CustomDataList[1]/CustomData[2]/Value[1]/text()[1] (DIFFERENT)
```

which may be closer to what you expect.

There is a certain balance to aim for when specifying `ElementSelector`s. If you make them too specific then differences will lead to missed matches and `CHILD_LOOKUP` differences that are more difficult to understand.

**Comment by beirtipol** [comment]
Thank you very much for the detailed explanation Stefan, very much appreciated. I'll implement that tomorrow and see how it goes. 

If I also have something like <otherCustomData><keyname>some name</keyname><keyvalue>somevalue</keyvalue></otherCustomData> in the same document, can I just chain a suitable xpath selector with the ones above? And does the order of selectors matter?

**Comment by bodewig** [comment]
Yes, you can use multiple selectors using the conditional builder. The conditional builder also provides you with explicit control over the order of selectors that are attempted - they are applied in the order specified.

**Comment by beirtipol** [comment]
Excellent thank you. I'll post a simple example with more detail of the actual document I'm comparing in case it's useful to others.

**Comment by beirtipol** [comment]
For those that might come across this, here's what I've used, and it works a treat. ( @bodewig - is there a cleaner way to construct the selectors? )

Here is the document structure I'm trying to diff
```xml
	<SomeObject>
		<CustomDataList>
			<CustomData>
				<Name>SettlementFXRate</Name>
				<Value>1234</Value>
			</CustomData>
			<CustomData>
				<Name>SettlementCurrency</Name>
				<Value>USD</Value>
			</CustomData>
		</CustomDataList>
                <SomeSimpleElement>
                                <SomeElement>A Value</SomeElement>
                                <SomeElement2>Another Value</SomeElement2>
                <SomeSimpleElement>
		<Keywords>
			<Keyword>
				<KeywordName>key-value-pairs-are-great</KeywordName>
				<KeywordValue>no they're not</KeywordValue>
			</Keyword>
			<Keyword>
				<KeywordName>but-where-should-we-put-the-crap</KeywordName>
				<KeywordValue>Just don't put crap in here</KeywordValue>
			</Keyword>
		</Keywords>
        </SomeObject>
```

And here is the selector that produces the fewest differences when I have out of order keywords or customData, or indeed new tags in either custom data or keywords


```
	private ElementSelector buildSelectors() {
		return ElementSelectors.conditionalBuilder()//
				.whenElementIsNamed("CustomData")
				.thenUse(ElementSelectors.byXPath("./Name", ElementSelectors.byNameAndText))
				.elseUse(ElementSelectors.conditionalBuilder()//
						.whenElementIsNamed("Keyword")//
						.thenUse(ElementSelectors.byXPath("./KeywordName", ElementSelectors.byNameAndText))//
						.elseUse(ElementSelectors.byName)//
						.build())//
				.build();
	}
```

**Comment by bodewig** [comment]
You can chain `whenElementIsNamed` directly on `thenUse`, i.e.

```java
 ElementSelectors.conditionalBuilder()//
			.whenElementIsNamed("CustomData")
			.thenUse(ElementSelectors.byXPath("./Name", ElementSelectors.byNameAndText))
			.whenElementIsNamed("Keyword")//
			.thenUse(ElementSelectors.byXPath("./KeywordName", ElementSelectors.byNameAndText))
			.elseUse(ElementSelectors.byName)
			.build();
```

**Comment by beirtipol** [comment]
Much cleaner, thank you again. (And thank you very much for providing the library!)
