### ISSUE TITLE
Sorting is not working 

### ISSUE THREAD

**Issue by sergiodaguru** [xmlunit/xmlunit#164]
I have an XML like:

`<connector ...>
  <configuration ...>
     <dispatcher name="Z">
        <url>www.test.com</url>
     </dispatcher>
     <dispatcher name="A">
        <url>www.test2.com</url>
     </dispatcher>
  </configuration>
</connector>
`

when I compare it with this sample

`<connector ...>
  <configuration ...>
     <dispatcher name="A">
        <url>www.test2.com</url>
     </dispatcher>
     <dispatcher name="Z">
        <url>www.test.com</url>
     </dispatcher>
  </configuration>
</connector>`

I then do:

`Diff myDiff = DiffBuilder.compare(srcStream).ignoreComments().ignoreWhitespace()
							.ignoreElementContentWhitespace().withTest(
									trgStream)
.withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.and(
									ElementSelectors.conditionalBuilder().whenElementIsNamed("dispatcher")
											.thenUse(ElementSelectors.byXPath("./name",
													ElementSelectors.byName))
											.elseUse(ElementSelectors.byNameAndAllAttributes).build())))
							.checkForSimilar().build();
`

I get that they differ:

Expected attribute   value 'Z' but was 'A' - comparing   <dispatcher name="A"...> at   /connector[1]/configuration[1]/dispatcher[1]/@name   to <dispatcher name="A"...> at   /connector[1]/configuration[1]/dispatcher[1]/@name   (DIFFERENT)
--
I expected XML Unit to sort the XML elements and consequently tell me they are equal.
What am I doing wrong?

**Comment by bodewig** [comment]
If you really want to use XPath, then you need to correct it. `./name` would select a child element named `name` of your `dispatcher` element - which doesn't exist in your documents.

The good news is you don't need to use XPath at all, which is pretty expensive when compared to the alternatives `byNameAndAttributes("name")` should work just fine.

And you also don't need the `ElementSelectors.and` at all as you are only using a single `ElementSelector`.

I just wanted to write down a complete solution like

```java
.withNodeMatcher(new DefaultNodeMatcher(
    ElementSelectors.conditionalBuilder()
    .whenElementIsNamed("dispatcher") 
    .thenUse(ElementSelectors.byXPath(ElementSelectors.byNameAndAttributes("name"))
    .elseUse(ElementSelectors.byNameAndAllAttributes).build()))
```

when I stumbled over you `elseUse`. If you really want to only match elements of their name is the same and all attributes match exactly then it will work for your `dispatcher` elements anyway and

```java
.withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndAllAttributes))
```

should work.

Note that `byNameAndAllAttributes` is a pretty strong requirements. If you apply it to 

```
<test foo="bar"/>
```

and

```
<test foo="baz"/>
```

is will not tell you the attribute values are different but rather give you to `CHILD_NODE_LOOKUP` differences as XMLUnit will not compare the elements at all.

**Comment by sergiodaguru** [comment]
Well, my scenario is simple but complex at the same time, I have hundreds of XML files with different schemas let's call this set as NEW files, I must compare these files with files with the same schema but having different values, let's call this OLD files.
I want to compare OLD to NEW and highlight the differences (ideally there should be none). However  there is a catch, some of the XML elements in NEW are in a different order:
`NEW
<listeners>
  <alias name="AliasC">
      <sub1>xxx</sub1>
      <sub2>yyy</sub2>
  </alias>
  <alias name="AliasA">
      <sub1>zzz</sub1>
      <sub2>www</sub2>
  </alias>
  <alias name="AliasX">
      <sub1>ppp</sub1>
      <sub2>rrr</sub2>
  </alias>
` 
Now when I use the code:
`Diff myDiff = DiffBuilder.compare(srcStream).ignoreComments().ignoreWhitespace()
							.ignoreElementContentWhitespace().withTest(
									trgStream);
.withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.and(									ElementSelectors.conditionalBuilder().whenElementIsNamed("alias")											.thenUse(ElementSelectors.byXPath("./@name",										ElementSelectors.byName))							.elseUse(ElementSelectors.byName).build())))
.checkForSimilar().build();
' 
Things don't go as planned, because if OLD looks like this:
`<listeners>
  <alias name="AliasD">
      <sub1>ddd</sub1>
      <sub2>eee</sub2>
  </alias>
  <alias name="AliasX">
      <sub1>ppp</sub1>
      <sub2>rrr</sub2>
  </alias>
  <alias name="AliasA">
      <sub1>zzz</sub1>
      <sub2>www</sub2>
  </alias>
`
XML Unit when comparing says:
Expected attribute value 'AliasD' but was 'AliasC' 
and then also says all child elements of 'AliasC' differ:
Expected attribute value 'ddd' but was 'xxx'
Expected attribute value 'eee' but was 'yyy'

What I was expecting was for XML Unit to say 
Expected attribute value 'AliasD' but was null

Can I achieve this with XML Unit? Do I need customized selectors for every XML which has a different schema?

Thanks for all your help

**Comment by bodewig** [comment]
You XPath selects an attribute, which is not an element so no `ElementSelector` at all will ever work. If you want to match on attributes, use `byNameAndAttributes`. You want `ElementSelectors.byNameAndAttributes("name")` instead of `ElementSelectors.byXPath("./@name", ElementSelectors.byName)`.
 
And I still don't understand waht you want to do with `and` - but it least it shouldn't do any harm :-)

**Comment by bodewig** [comment]
I forgot to answer

> Can I achieve this with XML Unit? Do I need customized selectors for every XML which has a different schema?

Absolutely, you "only" need to use a setup of `ElementSelector`s that matches your documents. Please read https://github.com/xmlunit/user-guide/wiki/SelectingNodes for a writeup that is as good as I can express it. Picking the correct `ElementSelector` is crucial and is the most difficult part - and there is no "one size fits it all" approach, you always need to adapt it to your documents.
