### ISSUE TITLE
Fails to compare unordered elements of XML files

### ISSUE THREAD

**Issue by xMagiciaNx** [xmlunit/xmlunit#169]
I am trying to use XMLUNIT DiffBuilder to ignore XML elements order when comparing two .xml files but it fails everytime. I have tried every possible combination and read many articles before posting this issue. I think something is broken here.

For example:

```
<Data:Keys>
<Data:Value Key="1" Name="Example1" />
<Data:Value Key="2" Name="Example2" />
<Data:Value Key="3" Name="Example3" />
</Data:Keys>

<Data:Keys>
 <Data:Value Key="2" Name="Example2" />
 <Data:Value Key="1" Name="Example1" />
 <Data:Value Key="3" Name="Example3" />
</Data:Keys>
```

I want these two treated as same XML. Notice that elements are empty, they have only attributes. What I did so far:

```
def diff = DiffBuilder.compare(Input.fromString(xmlIN))
           .withTest(Input.fromString(xmlOUT))
           .ignoreComments()
           .ignoreWhitespace()
           .checkForSimilar()
           .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.conditionalBuilder()
           .whenElementIsNamed("Data:Keys").thenUse(ElementSelectors.byXPath("./Data:Value", 
            ElementSelectors.byNameAndText))
           .elseUse(ElementSelectors.byName)
           .build()))
```

But it fails every time. I don't know if the issue is the namespace, or that the elements are empty.

**Comment by bodewig** [comment]
There are a few things wrong with your example - and I most probably don't fully understand it.

First of all `whenElementIsNamed("Data:Keys")` simply won't work as the String-arg version only looks at the local names of the elements (the part after the colon). You need to use the `QName`-arg version or `whenElementIsNamed("Keys")` instead. But this is only a side-problem.

Is there only one `<Data:Keys>` element inside of your document or are there more of them that you have not shown?

If there is only one, then you don't need to use a special `ElementSelector` for `Data:Keys` at all, or rather `byName` will do if there are more siblings of `Data:Keys`.

You will need an ElementSelector for your `Data:Value` elements but from your example `byNameAndAttributes("Key")` could be what you need. Is the `Key` attribute the one that selects the proper `Data:Value`?

If my guesses are correct then

```java
    .whenElementIsNamed("Value").thenUse(ElementSelectors.byNameAndAttributes("Key"))
    .elseUse(ElementSelectors.byName)
```

should work.

**Comment by xMagiciaNx** [comment]
I modified the Data:Keys -> Keys but still won't do any progress.
Yes under Keys, there are only "Data:Value" but for a quick example:

File1
```
<Data:Keys>
<Data:Value Key="1" Name="Example1" />
<Data:Value Key="2" Name="Example2" />
<Data:Value Key="3" Name="Example3" />
</Data:Keys>
```

File2
```
<Data:Keys>
 <Data:Value Key="2" Name="Example2" />
 <Data:Value Key="1" Name="Example1" />
 <Data:Value Key="3" Name="Example3" />
</Data:Keys>
```

The method is as follow:
```
Diff diff = DiffBuilder.compare(Input.fromFile(actualFile))
   	.withTest(Input.fromFile(expectedFile))
   	.ignoreComments()
   	.ignoreWhitespace()
   	.normalizeWhitespace()
   	.checkForSimilar()
   	.withNodeMatcher(new DefaultNodeMatcher(
	ElementSelectors.conditionalBuilder()
		.whenElementIsNamed("Keys")
		.thenUse(ElementSelectors.byNameAndAttributes("Value"))
		.elseUse(ElementSelectors.byName)
		.build()
    	)).build()
   	
   log.info diff
```

Simple doesn't work.
I think it is a simple example but don't know exactly what's going wrong.

**Comment by bodewig** [comment]
Your `Keys` element has no `Value` attribute, so what you have written can not work.

`ElementSelector`s job is to select the correct element when looking at a set of siblings. You have told it 

* if you are currently looking at a `Keys` element, then look through all `Keys` in the current set of siblings and compare the ones who have the same `Value` attribute.
* if you are looking at anything else, then compare the same named siblings in order

What I guess you want (you haven't said so explicitly) is

* If you are currently looking at a `Value` element, then look through all `Value`s in the current set of siblings and compare the ones who have the same `Key` attribute
* if you are looking at anything else, then compare the same named siblings in order

which is the snippet I suggested in my last response.

**Comment by bodewig** [comment]
https://gist.github.com/bodewig/573c4d9c3bb692028d1013c9ce74f8fd prints `[identical}`.

**Comment by xMagiciaNx** [comment]
Thanks a million.

**Comment by bodewig** [comment]
you're welcome
