### ISSUE TITLE
Ignore namespace while implementing own DifferenceEvaluator

### ISSUE THREAD

**Issue by AlexPeshkov** [xmlunit/xmlunit#177]
Dear Team
I need to get the clarification how to use both DEFAULT and my own DifferenceEvaluator to ignore namespace prefix
There are two xml:
--source
`<Product>
<Name>Audi Q3</Name>
</Product>`

--target
`<Product>
<ns1:Name>Audi Q3</ns1:Name>
</Product>`

I would like to ignore ns1 while compare xmls. So my builder looks like

`Diff myDiff = DiffBuilder.compare(target)
.withTest(source)
.withDifferentEvaluator(new MyDifferenceEvaluator(nameOfField))
.build();`

Difference number is 110

If builder looks like:
`Diff myDiff = DiffBuilder.compare(target)
.withTest(source)
.withDifferentEvaluator(
DifferenceEvaluators.chain(DifferenceEvaluators.Default,
new MyDifferenceEvaluator(nameOfField))
.checkForSimilar()
.build();`

Difference number is 55, and still 'ns1' is not ignored.

Would you please advise how to avoid that problem!?

Many thanks in advance!

**Comment by bodewig** [comment]
Without looking at the code of your `DifferenceEvaluator` it is difficult to say why it doesn't work.

Are you sure it is only the prefix of the namespace that is different? `NAMESPACE_PREFIX` differences will lead to `SIMILAR` results by using the `Default` `DifferenceEvaluator` anyway.

You don't show the namespace definitions in your example, but if the default namespace in source and the URI of the namespace with prefix `ns1` in target are different, then a lot more than just the prefix are different.

**Comment by AlexPeshkov** [comment]
Hi Stefan

Yes, you're right, namespace prefix is not the only difference, but the rest of difference i can sort out by DifferenceEvaluator. 

So here is an example of DifferenceEvaluator to handle IsoDateTime in my case.

```
@Override
public ComparisonResult evaluate(Comparison comparison, ComparisonResult outcome) {
  if (outcome == ComparisonResult.EQUAL) return outcome;
  final Node controlNode = comparison.getControlDetails().getTarget();
  if (controlNode.getParentNode() instanceOf Element) {
         Element controlElement = (Element) controlNode.getParentNode();
        if (controlElement.getNodeName().equals(elementName)) {
              final  String controlValue = coontrolElement.getFirstChild().getNodeValue();
              final String isoDateTime = controlValue.substring(0,10);
             if (isoDateTime.equals(LocalDate.now().toString())) {
                    return Comparison.SIMILAR;
                 }
         } 
     }
  return outcome;
}
```
However this DifferenceEvaluator has not got anything with handling of namespace prefix (to ignore it throghout the whole xml doc) and 'comparison' (type NAMESPACE_URI) object is defined already with `'Expected namespace uri 'http://.... ' but was 'null' - comparing <ns1:Name...> at /Product/Name  to <Name...> at /Product/Name`

Namespaces definition is the same between two xml like

<productX xmlns:ns1="http://..."   xmlns:ns2="http://....">

**Comment by bodewig** [comment]
First of all: two elements that have the same local name (`Name` in your example) but different namespace URIs simply don't have the same name. I'm sure you know that, but I need to stress this nevertheless.

For the reason above I suspect you see more differences than you'd like to because your `ElementSelector` ends up not comparing the elements you want to compare. In addition to the `DifferenceEvaluator` you most likely need an additional `ElementQualifier` that ignores namespace URIs.

There is no built-in version that would ignore namespace URIs, because it would simply be wrong from an XML point of view.

**Comment by AlexPeshkov** [comment]
Thank you for your help! I managed to resolved my issue by that [example](https://stackoverflow.com/questions/26524286/xmlunit-ignore-xmlns) 
a bit extended.

**Comment by bodewig** [comment]
Great.
