### ISSUE TITLE
XmlUnit 2.6.[3,4] is not compatible with AssertJ-Core 3.15.0

### ISSUE THREAD

**Issue by jwalter** [xmlunit/xmlunit#181]
The following test:
```
@Test
  fun `assertThatXml_valueByXPath should work`() {
    val xml = """
      <fruit>
        <color>yellow</color>
      </fruit>
    """
    assertThatXml(xml).valueByXPath("//color").isEqualTo("yellow")
  }
```
will throw an error when trying to run with assertj 3.15.0 on the classpath:
```
java.lang.NoSuchMethodError: org.xmlunit.assertj.ValueAssert.describedAs(Ljava/lang/String;[Ljava/lang/Object;)Lorg/assertj/core/api/AbstractAssert;

	at org.xmlunit.assertj.ValueAssert.create(ValueAssert.java:68)
	at org.xmlunit.assertj.XmlAssert.valueByXPath(XmlAssert.java:202)
```
The cause is that assertj 3.15.0 moved the `describedAs´method from AbstractAssert to Descriptable and due to type erasure the method return type changed on the byte code level from AbstractAssert to Object.

This currently affects all Spring Boot projects using the milestone M2, M3 or M4 builds of Spring Boot 2.3.0.

**Comment by bodewig** [comment]
I'm not an AssertJ user myself. I wonder whether the AssertJ devs realize they are breaking binary compatibility repeatedly and make people who provide custom assertions unhappy. This is not the first time, see #135 and #166 

I'll try to see whether there is a way to adapt without breaking support for older versions - unless @krystiankaluzny beats me to it.

**Comment by bodewig** [comment]
I've simply overridden the method and duplicated the implementation -which hasn't changed since at least 2.9.0. Calling `super` would - of course - not work because of the same `NoSuchMethod` exception.

I've also added an easier setup for compatibility tests in Travis.

**Comment by bodewig** [comment]
I've just published a 2.7.0-SNAPSHOT version. @jwalter it would be good if yo could confirm this version works for you.

**Comment by jwalter** [comment]
2.7.0-SNAPSHOT solves the reported issue for me. Thanks!

**Comment by snicoll** [comment]
@jwalter thanks for testing!

@bodewig for the record we are releasing Spring Boot 2.3 GA this Thursday if that makes sense (and if you have time) to squeeze a release of XMLUnit in the meantime.

**Comment by bodewig** [comment]
will do tonight (CEST :-) )

Thanks for testing.

**Comment by bodewig** [comment]
2.7.0 should show up in maven central soonish, I've just released the Nexus repo.
