### ISSUE TITLE
Reuse Transformer for CommentLessSource

### ISSUE THREAD

**Issue by tutufool** [xmlunit/xmlunit#183]
My LnP test indicates that below code in Transformation takes time when create a new transformer:

```
            Transformer t;
            if (styleSheet != null) {
                t = fac.newTransformer(styleSheet); // usually go this way
            } else {
                t = fac.newTransformer();
            }
```

Currently, I can bypass this issue by providing a "comment less document" instead of calling ignoreComments() on builder :

```
  private Document ignoreComments(String xml) {

    try {
      Source source = Input.from(xml).build();
      DOMResult result = new DOMResult();
      Transformer t = cachedTransformer.get(); // get from threadlocal
      t.transform(source, result);
      t.reset();
      return (Document) result.getNode();
    } catch (javax.xml.transform.TransformerConfigurationException e) {
      throw new ConfigurationException(e);
    } catch (javax.xml.transform.TransformerException e) {
      throw new XMLUnitException(e);
    }

  }

DiffBuilder.compare(ignoreComments(controlXml))...

```

I'm not sure whether we should allow user to optionally provide a Transformer via builder API like:

`DiffBuilder...ignoreComments(myTransformer)...`

**Comment by bodewig** [comment]
I'm not quite sure how you get there in the first place. `DiffBuilder.ignoreComments` creates a new `CommentLessSource´ internally, so passing in one would achieve the same, wouldn't it? `CommentLessSource` probably needs a constructor that allows the factory to be passed in in the first place.

`ignoreComments` really only is a convenience API, I wouldn't want to overload it but would prefer users to provide proper `Source`s in edge cases like this. In most scenarios I don't believe XMLUnit runtime will be critical, and in cases where it is, people will probably not use XSLT to strip comments.

BTW "LnP test"?

**Comment by tutufool** [comment]
"LnP" means Load and Performance :)

I'm OK with your idea that let user make the call rather than make the builder API more complex.

And you reminds me that I can probably use regex to remove comments before feeding to builder like xmlFileContent.replaceAll("", "");

Thanks for your feedback!

**Comment by bodewig** [comment]
as long as you've got control over the documents, regexes may work. Otherwise trying to use regexes on XML may become a step on the path to insanity. Beware, there may be dragons :-)
