### ISSUE TITLE
How to ignore namespace when compare xml

### ISSUE THREAD

**Issue by tutufool** [xmlunit/xmlunit#184]
This might be a question rather than an issue.

control:

`xmlns="http://www.mydomain.com/services/v1"`

test:

`xmlns="http://www.mydomain.com/services/v2"`

Assuming that control and test have exactly same xml structure, how to make it EQUAL?

**Comment by bodewig** [comment]
First of all, you don't don't :-)

From an XML purist's point of view `<a xmlns="a"/>` and `<a xmlns="b"/>` are completely different things.

If you really really want to ignore XML namespace URIs then you need to provide a `DifferenceEvaluator` that downgrades differences and an `ElementSelector` that ignores namespace URIs as well - `byName` will take it into account.

**Comment by tutufool** [comment]
Thanks, let me give it a try
