### ISSUE TITLE
Matching node by its content fails in some cases

### ISSUE THREAD

**Issue by prlourenco** [xmlunit/xmlunit#185]
Hi,

I'm having an issue of inconsistent behaviors depending on the XML siblings present in the Test source.

Consider the following Control source:

> <root>

	<EntityData>
		<m>
			<field_0>A</field_0>
			<field_1>B</field_1>
		</m>
		<m>
			<field_0>C</field_0>
			<field_1>D</field_1>
		</m>
	</EntityData>
</root>

The "EntityData" can contain multiple "m" nodes. As the child of the "m" node may vary, I cannot use the ElementSelectors.byXPath, so I'm using ByNameAndTextRecSelector to try to match the correct element.

If I compare it with the following Test source:

> <root>

	<EntityData>
		<m>
			<field_0>C</field_0>
			<field_1>D</field_1>
		</m>
		<m>
			<field_0>A</field_0>
			<field_1>B</field_1>
		</m>
	</EntityData>
</root>

It matches Source/EntityData/m[1] with Test/EntityData/m[2] and Source/EntityData/m[2] with Test/EntityData/m[1] and outputs the correct 2 CHILD_NODELIST_SEQUENCE differences.

However, with the following Test source: 

> <root>

	<EntityData>
		<m>
			<field_0>C</field_0>
			<field_1>D</field_1>
		</m>
		<m>
			<field_0>E</field_0>
			<field_1>F</field_1>
		</m>
	</EntityData>
</root>

It fails to match Source/EntityData/m[2] with Test/EntityData/m[1], and matches Source/EntityData/m[1] with Test/EntityData/m[1] and Source/EntityData/m[2] with Test/EntityData/m[2] and therefore outputs 4 TEXT_VALUE differences.

I was expecting 2 CHILD_LOOKUP in this case.

Here's my code:
`ElementSelector e1 = ElementSelectors.conditionalBuilder().whenElementIsNamed("m").thenUse(new ByNameAndTextRecSelector()).build();`

`ElementSelector e2 = ElementSelectors.conditionalBuilder().whenElementIsNamed("s").thenUse(ElementSelectors.byNameAndText).build();`

`DiffBuilder.compare(source).withTest(target).checkForSimilar().ignoreWhitespace().normalizeWhitespace().withNodeMatcher(new DefaultNodeMatcher(e1, e2, ElementSelectors.byName)).build();`

How can I instruct the Matcher to analyze all the possible siblings before trying to match by name and position?

**Comment by bodewig** [comment]
`ByNameAndTextRec` really is more of a kludge an I'm not sure it will always do what you want and not return false positives in some cases. If you don't know the children, you could just try to match the very first child `./*[1]`. This may or may not be good enough.

In either case, this is not the cause for the strange behaviour you see. :-)

You are using multiple `ElementSelector`s and the behaviour is not always what one would expect, see https://github.com/xmlunit/user-guide/wiki/SelectingNodes#using-more-than-one-elementselector-at-the-same-time . What you probably want is

```
    ElementSelector e = ElementSelectors.conditionalBuilder()
        .whenElementIsNamed("m").thenUse(new ByNameAndTextRecSelector())
        .whenElementIsNamed("s").thenUse(ElementSelectors.byNameAndText)
        .elseUse(ElementSelectors.byName).build();

    DiffBuilder.compare(source).withTest(target)
        .checkForSimilar().ignoreWhitespace().normalizeWhitespace()
        .withNodeMatcher(new DefaultNodeMatcher(e)).build();
```

**Comment by prlourenco** [comment]
Yes, you are right. My mistake was letting "m" elements fallback to the ElementSelectors.byName matcher. Your suggestion solved my problem.

Only now I understand the processing logic: each element is matched (testing the full list of matchers) before moving on the next element. I was expecting that each Matcher would handle first the matches only moving to the next Matcher in case of any unmatched element. Something like a Breadth-first instead of a Depth-first algorithm.

Thanks for your help.

**Comment by bodewig** [comment]
The breadth-first behaviour you are looking for is provided by `or`, so people have the choice to pick whatever works best for them.
