### ISSUE TITLE
Good first issues is empty now

### ISSUE THREAD

**Issue by harkue** [xmlunit/xmlunit#191]
Is there any good issue for new guys who want to contribute?

    If you're ready to tackle some open issues, we've collected some **good first issues** for you .

**Comment by bodewig** [comment]
Right now there don't seem to be any, sorry.

The problem with "good first issues" is that eventually somebody has to resolve them, even if it hasn't been the first issue. Things you can leave open forever are rare.

In addition I believe XMLUnit is in a state where it probably does most of the things people want and it is pretty stable, so if things pop up they tend to be either urgent or not-so-easy.

**Comment by bodewig** [comment]
there are two issues labelled "good first issue" right now
