### ISSUE TITLE
MultipleNodeAssert: asserting node text of all nodes

### ISSUE THREAD

**Issue by keesvandieren** [xmlunit/xmlunit#192]
Given a list of DOM nodes with texts, we'd like to assert that the texts of the elements matches an array of strings we have in Java.

For attributes, there is [extractingAttribute](https://github.com/xmlunit/xmlunit/blob/master/xmlunit-assertj/src/main/java/org/xmlunit/assertj/MultipleNodeAssert.java#L229) which makes this easy for attributes.

We'd like to have an `extractingText` there to do the same for element texts.

We would like to write the following test (we are testing an XSL-FO document):

```java
        assertThat(letterDocument)
                .withNamespaceContext(XSL_FO_NAMESPACE_CONTEXT)
                .nodesByXPath("//fo:block[@id='recipient-address']/fo:block")
                .extractingText()
                .containsExactly("John Doo",
                        "Street 213423",
                        "2944 AA Amsterdam",
                        "The Netherlands");
```

So far I am unable to write well-written assertions to test this.

Maybe I am missing something?

Would you accept a PR for such an extractingText() method?

**Comment by bodewig** [comment]
That would be the content of nested `Text` nodes? One probably needs to be careful with the parser normalizing things even when one doesn't expect it.

> Would you accept a PR for such an extractingText() method?

Sure. Thank you,
