### ISSUE TITLE
Support java.nio.file.Path as input source

### ISSUE THREAD

**Issue by gastaldi** [xmlunit/xmlunit#196]
It would be nice if `XmlAssert.assertThat()` worked with `java.nio.file.Path` objects

**Comment by bodewig** [comment]
Even though you mention it as an enhancement for the AssertJ module, it would probably be good to have NIO support in core's `InputBuilder`. Apart from `Path` we should probably support readable `Channel`s as well.

The biggest hurdle here is that core currently wants to be Java 6 compatible. Maybe it is about time to change that.
