### ISSUE TITLE
xmlns ignores ElementSelector

### ISSUE THREAD

**Issue by Vishal-Joshi** [xmlunit/xmlunit#204]
Hi,
I have this xml
**XML-1**
```
<foo>
  <bar>
    <type>1</type>
    <value>value1</value>
  </bar>
  <bar>
    <type>2</type>
    <value>value2</value>
  </bar>
  <bar>
    <type>3</type>
    <value>value3</value>
  </bar>
</foo>
```
which I comparing against following xml irrespective of order of child nodes 
**XML-2**
```
<foo >
  <bar>
    <type>1</type>
    <value>value1</value>
  </bar>
  <bar>
    <type>3</type>
    <value>value3</value>
  </bar>
  <bar>
    <type>2</type>
    <value>value2</value>
  </bar>
</foo>
```

I am using this configuration of difference builder
```
ElementSelector elementSelector = ElementSelectors.conditionalBuilder().whenElementIsNamed("bar")
                .thenUse(ElementSelectors.byXPath("./type", ElementSelectors.byNameAndText))
                .elseUse(ElementSelectors.byName)
                .build();
        Diff diff = DiffBuilder.compare(Input.fromFile(expectedOutputFilePath))
                .withTest(Input.fromFile(outputPath))
                .checkForSimilar()
                .ignoreWhitespace()
                .normalizeWhitespace()
                .withNodeMatcher(new DefaultNodeMatcher(elementSelector))
                .build();
```
Everything is fine till here.

However, when I add "xmlns" attribute to parent node i.e. "foo", the `elementSelector` seems to be not working and fails by citing differences which seems to be occurring because it tends to compare "bar" elements in order they appear in the xml.

**XML-1**
```
<foo xmlns="https://www.w3schools.com/furniture">
  <bar>
    <type>1</type>
    <value>value1</value>
  </bar>
  <bar>
    <type>2</type>
    <value>value2</value>
  </bar>
  <bar>
    <type>3</type>
    <value>value3</value>
  </bar>
</foo>
```
**XML-2**
```
<foo xmlns="https://www.w3schools.com/furniture">
  <bar>
    <type>1</type>
    <value>value1</value>
  </bar>
  <bar>
    <type>3</type>
    <value>value3</value>
  </bar>
  <bar>
    <type>2</type>
    <value>value2</value>
  </bar>
</foo>
```
**Differences reported**
```
Expected text value '2' but was '3' - comparing <type ...>2</type> at /foo[1]/bar[2]/type[1]/text()[1] to <type ...>3</type> at /foo[1]/bar[2]/type[1]/text()[1] (DIFFERENT)
Expected text value 'value2' but was 'value3' - comparing <value ...>value2</value> at /foo[1]/bar[2]/value[1]/text()[1] to <value ...>value3</value> at /foo[1]/bar[2]/value[1]/text()[1] (DIFFERENT)
Expected text value '3' but was '2' - comparing <type ...>3</type> at /foo[1]/bar[3]/type[1]/text()[1] to <type ...>2</type> at /foo[1]/bar[3]/type[1]/text()[1] (DIFFERENT)
Expected text value 'value3' but was 'value2' - comparing <value ...>value3</value> at /foo[1]/bar[3]/value[1]/text()[1] to <value ...>value2</value> at /foo[1]/bar[3]/value[1]/text()[1] (DIFFERENT)


java.lang.AssertionError: Expected text value '2' but was '3' - comparing <type ...>2</type> at /foo[1]/bar[2]/type[1]/text()[1] to <type ...>3</type> at /foo[1]/bar[2]/type[1]/text()[1]
```

**Comment by bodewig** [comment]
XPath and XML namespaces interact in strange ways. In your case you want to select namespaced elements and selecting by local name only doesn't seem to work. I must admit that I would have expected it to work just the way you are using it.

In my tests

```
.byXPath("./x:type", Collections.singletonMap("x", "https://www.w3schools.com/furniture"), ElementSelectors.byNameAndText)
```

makes the comparison result in "identical" again.

**Comment by bodewig** [comment]
looks as if JAXP's behavior surprised me just the same two years ago (I knew I've seen something similar before :-) ) -> #128

**Comment by Vishal-Joshi** [comment]
Thank you @bodewig , your suggestion works for me which is good. However, I don't understand how did you come up with that Xpath?
`.byXPath("./x:type", Collections.singletonMap("x", "https://www.w3schools.com/furniture")....`

If I try to understand it, are your qualifying the namespace  "https://www.w3schools.com/furniture" with "x" prefix?

Why does it not work with no prefix considering the default namespace like a general rule in XML? Referring from here https://www.w3schools.com/xml/xml_namespaces.asp

**Comment by bodewig** [comment]
The article you point at doesn't talk about XPath at all - and the XPath tutorial at w3school doesn't mention namespaces. The relation is, errm, complicated. :-)

XPath expressions don't know about the prefixes you use in your document. Prefixes you use in your XPath expression need to be mapped to URIs explicitly using the map that is the second argument to `byXPath`. Microsoft's docs over at https://docs.microsoft.com/en-us/dotnet/standard/data/xml/xpath-queries-and-namespaces also apply to the Java version of XMLUnit as what they say there is true for XPath in general

> This means that if you want to query against a namespace in an XML document, even if it is the default namespace, you need to define a prefix for it.
https://docs.microsoft.com/en-us/dotnet/standard/data/xml/xpath-queries-and-namespaces#the-default-namespace
