### ISSUE TITLE
Assertj3 (SNAPSHOT) throws UnknownFormatConversionException

### ISSUE THREAD

**Issue by Zegveld** [xmlunit/xmlunit#205]
If you use files that contains a space then it gets replaced by %20, which ends up in the message. Assertj then tries to format this and throws an java.util.UnknownFormatConversionException because %20 -> Conversion = '2' is unknown.

by duplicating the '%' signs after formatting it in the CompareAssert class this error goes away and the failure becomes as expected.

Pull request incoming to fix this issue.

**Comment by bodewig** [comment]
closed by #206
