### ISSUE TITLE
Enforce/Ingore order at array level

### ISSUE THREAD

**Issue by klgopal13** [xmlunit/xmlunit#207]
Hello,

I'm using XMLUnit 2.7.0 and I'm facing an issue with ignoring the order. 

Control:
`<StatusUpdate>
    <Subscriptions>
        <type>base</type>
        <Offering>
            <code>code1</code>
            <status>active</status>
        </Offering>
    </Subscriptions>
    <Subscriptions>
        <type>optional</type>
        <Offering>
            <code>optional-1</code>
            <status>active</status>
        </Offering>
        <Offering>
            <code>optional-2</code>
            <status>active</status>
        </Offering>
        <Offering>
            <code>optional-3</code>
            <status>active</status>
        </Offering>
    </Subscriptions>
</StatusUpdate>`

My use cases:

1. Is there anyway in XMLUnit to validate that Subscriptions.type = base will always be prior to Subscriptions.type = optional. In the below case, comparison should fail.

Test XML eg:
`<StatusUpdate>
    <Subscriptions>
        <type>optional</type>
        <Offering>
            <code>optional-1</code>
            <status>active</status>
        </Offering>
        <Offering>
            <code>optional-2</code>
            <status>active</status>
        </Offering>
        <Offering>
            <code>optional-3</code>
            <status>active</status>
        </Offering>
    </Subscriptions>
    <Subscriptions>
        <type>base</type>
        <Offering>
            <code>code1</code>
            <status>active</status>
        </Offering>
    </Subscriptions>
</StatusUpdate>`

2. Inside the Subscriptions array, Offering order does not matter. So below test xml, offering-3 is before offering-2, this should be passed.
`<StatusUpdate>
    <Subscriptions>
        <type>base</type>
        <Offering>
            <code>code1</code>
            <status>active</status>
        </Offering>
    </Subscriptions>
    <Subscriptions>
        <type>optional</type>
        <Offering>
            <code>optional-1</code>
            <status>active</status>
        </Offering>
        <Offering>
            <code>optional-3</code>
            <status>active</status>
        </Offering>
        <Offering>
            <code>optional-2</code>
            <status>active</status>
        </Offering>
    </Subscriptions>
</StatusUpdate>`

Appreciate your help and time!

Thanks

**Comment by bodewig** [comment]
First of all you need to ensure the correct elements are compared to each other. You will likely need a conditional `ElementSelector` that chooses `Subscription` elements based on the text value of the nested `./Offering/code` - see https://github.com/xmlunit/user-guide/wiki/SelectingNodes#elementselectorsbyxpath

XMLUnit will detect `CHILD_NODELIST_SEQUENCE` differences and it is up to the `DifferenceEvaluator` whether the difference can be ignored or is significant. There is no built-in `DifferenceEvaluator` that would do what you ask for, but I think you should be able to provide one of your own that does.
