### ISSUE TITLE
maven artifact for com.springsource.org.custommonkey.xmlunit/1.2.0 is unavailable/missing.

### ISSUE THREAD

**Issue by jeacott1** [xmlunit/xmlunit#209]
the legacy artifact here
https://mvnrepository.com/artifact/org.custommonkey.xmlunit/com.springsource.org.custommonkey.xmlunit/1.2.0

is unavailable, now returns 401 or 404 depending on resource

https://repo.spring.io/plugins-release/org/custommonkey/xmlunit/com.springsource.org.custommonkey.xmlunit/1.2.0/com.springsource.org.custommonkey.xmlunit-1.2.0.jar

https://repo.spring.io/plugins-release/org/custommonkey/xmlunit/com.springsource.org.custommonkey.xmlunit/1.2.0

**Comment by bodewig** [comment]
We have never published an artifact by that name, as far as I can tell it has never existed. Most likely it is a repackaged version that somebody else has published - and I hope Sonatype has never been allowed anybody but us to publish to our groupId.

**Comment by jeacott1** [comment]
@bodewig is there a public version of org.custommonkey.xmlunit 1.2.0 anywhere?
this has been working for years afaik, but is recently toast. I thought since you have code with this package name and project name it must belong to you.

**Comment by bodewig** [comment]
I must admit I was a bit surprised I was close to opening an issue with Sonatype but things are "good" from our side.

The 1.x XMLUnit releases used the "xmlunit" groupId, we've never published to the "org.custommonkey" groupId and have never "owned" it. You can find all 1.x artifacts there: https://mvnrepository.com/artifact/xmlunit/xmlunit

With 2.x I purchased the xmlunit.org domain and we switched the groupId to org.xmlunit. For most purposes the 2.x xmlunit-legacy artifact (https://mvnrepository.com/artifact/org.xmlunit/xmlunit-legacy ) is supposed to be compatible with XMLUnit 1.x.

**Comment by bodewig** [comment]
Somebody (likely the SpringSource folks) have decided to publish artifacts under the coordinates you mention. I don't know whether these artifacts have been identical to XMLUnit 1.2 - and why they even did so in the first place as all XMLUnit artifacts have been in Maven Central for a long time. My best guess is this is (has been?) a patched version of XMLUnit 1.2.

**Comment by jeacott1** [comment]
@bodewig , thanks - legacy project I'm dealing with and idk anything about this particular library except that its ancient, and now disappeared.
.
