### ISSUE TITLE
What's the equivalent of overrideDifferenceListener(Legacy module) in xml unit 2.0 

### ISSUE THREAD

**Issue by kvsarath** [xmlunit/xmlunit#214]
Hi, 

I want to ignore certain elements (it can be either attributes or text values or nodes) using xpath. 
In Legacy jar, we can implement overrideDifferenceListener to handle the differences. 
I want to know which class is the equivalent of this in the xml unit  core 2.0 so that I can explore the option and move to new version

**Comment by bodewig** [comment]
https://github.com/xmlunit/user-guide/wiki/Migrating-from-XMLUnit-1.x-to-2.x may be helpful.

Also, if you are currently using `DifferenceListener` just to suppress differences for certain elements, you may benefit from using a `NodeFilter` (see https://github.com/xmlunit/user-guide/wiki/SelectingNodes#nodefilter-and-attributefilter) instead. This way you can speed up the whole comparison in addition to ignoring elements you are not interested in - here I assume you want to ignore whole subtrees and not an element bit still compare the children.

**Comment by kvsarath** [comment]
Hi Stefan, 

Thanks for the response. In some scenarios, I just want to ignore certain attributes and compare the child elements 

My XML looks something like this. I just want to ignore comparison of attribute "Timestamp" and attr4 in XMLHeader Node and compare remaining elements and child nodes. 

Also my below xml contains multiple item elements and i want to ignore the difference found in  item/Model field value. Is there a way to tell diff engine to ignore difference found using xpath  "//item/itemHeader/Model" ?

<?xml version="1.0" encoding="UTF-8"?>
<XMLHeader Timestamp="04/19/2021 11:05:01" attr1="AAA" attr2="BBB"
	attr4="123456" xmlns="XXX">
	<group IncludedMessages="1" attr4="123456">
		<detail attr4="123456">
			<item>
				<itemHeader>
					<Quantity>1</Quantity>
					<price>20</price>
					<Model>123</Model>
				</itemHeader>
			</item>
			<item>
				<itemHeader>
					<Quantity>1</Quantity>
					<price>20</price>
					<Model>12345</Model>
				</itemHeader>
			</item>
		</detail>
	</group>
</XMLHeader>

**Comment by bodewig** [comment]
github is not displaying your example, but I've seen it in the email I received, so something seems wrong with your markup.

Anyway, I'm pretty sure you don't want me to just answer the question of whether it is possible with "yes". :-)

It should be straight forward to translate what you've done with your `DifferenceListener` to the new `DifferenceEvaluator`. Please try that and if things don't work as you expect please report the problems you face so we can improve the documentation.

**Comment by kvsarath** [comment]
sure. Will try it out.

**Comment by kvsarath** [comment]
I am closing this question.I will try out the approach using DifferenceEvaluator. Will raise separate issue if i need help
Thank you :)
