### ISSUE TITLE
DiffBuilder.compare() hangs on large files

### ISSUE THREAD

**Issue by mslepak1** [xmlunit/xmlunit#215]
I am trying to compare moderately large XML files (about 150MB) using DiffBuilder.compare(). It works fine on smaller files, but the execution hangs when I attempt to compare large files. Here is my code:

    public static void main(String[] args) {
         String fileName = "my-large-file.xml";
         // compare it to itself
         Diff diff = DiffBuilder.compare(Input.fromFile(fileName)).withTest(Input.fromFile(fileName)).build();
         for (Difference diffDetail : diff.getDifferences()) {
             System.out.println(diffDetail.toString());
	}
    }

I also tried to use standard Java SDK API comparing the same files, and I can see that it builds DOMs successfully, but then hangs on doc.normalizeDocument(). Of course, the issue may or may not have to do with the file size. It is possible that there is something specific in my file's content, but I can't figure it out.
Any help is appreciated.
Thank you.

**Comment by mslepak1** [comment]
It looks like there is nothing really wrong. It just takes time to compare large files. Eventually, after about 15 - 20 minutes it would end with OutOfMemoryError. I tried to increase heap memory, but it didn't help.

**Comment by bodewig** [comment]
Java's DOM is slow and bloated and it is known to consume insane amounts of memory for big XML documents.

Having said that, XMLUnit needs an API where it can freely move backwards and forwards through the tree if it wants to be able to deal with documents where the order of sibling elements has changed. If I want to compare

```xml
<x>
  <a/>
  <b/>
</x>
```

and

```xml
<x>
  <b/>
  <a/>
</x>
```

then I either need an API that allows me to go back to the `b` on the second document once I'm done comparing the `a`s or I have to cache the whole subtree below that second `b`, using my home-grown representation of a tree.

Of the APIs provided JAXP only DOM can do that. It would be possible to create a "sort-order must be the same on both sided" `DifferenceEngine` on top of StAX (or SAX) but its use seemed to be too limited so I've never implemented it. Also so far I've shyed away from building my own tree model on top of S(t)AX as I wanted to avoid the complexity. I'd be open to adopting alternative `DifferenceEngine` implementations that used either idea but wouldn't want to pollute `DOMDifferenceEngine` with it.

**Comment by mslepak1** [comment]
Thank you so much for your explanation. No wonder it is extremely slow on my particular files. One of the elements in the files I am trying to compare has over a million children with no ID attribute whatsoever. It's pretty much like this:

<x>
   <a attr1=... attr2=.../a>
   <a attr1=... attr2=.../a>
   ...
</x>

Sub-elements <a> are identical, they only differ by multiple attributes. As a result, the engine has no way of knowing which sub-element of the first file should be compared to which sub-element of the second file. My guess is it just compares them all to all until it finds a match. It literally creates sort of like a cartesian product of 1,000,000x1,000,000. As you mentioned, I need to sort my sub-elements. So, most likely, I will add an ID attribute for each sub-element based on values of its attributes. Then if I use SAX parser, I should be able to sort NodeList as I am building the DOM. Once the DOM is built, then comparing would be easy. Do you think I am on the right track?

**Comment by bodewig** [comment]
When you say `normalize` already never comes back, chances are your approach will not really improve things enough to get into a tolerable time/memory range. Unless you've specified an `ElementSelector` of your own (which is a way to tell XMLUnit which siblings to compare with each other) XMLUnit will automatically compare them in document order. It does not try all possible permutations by itself, even though this is a feature people have asked for.

What you describe sounds as if you wanted to use `ElementSelectors.byNameAndAllAttributes` - see https://github.com/xmlunit/user-guide/wiki/SelectingNodes - but I'm not convinced it is going to improve the situation enough to move you forward. As things stand I'm afraid there are practical limits in document sizes XMLUnit is able to deal with.

You might give XMLUnit.NET a try if that's an option. It is possible the DOM implementation of .NET (Core) consumes less resources than the Java one - but I haven't run any comparisons and it may just turn out to not help at all.
