### ISSUE TITLE
PlaceholderDifferenceEvaluator breaks similar result comparison

### ISSUE THREAD

**Issue by KaiStapel** [xmlunit/xmlunit#217]
### Steps to reproduce
```
public class XmlUnitTest {

  @Test
  public void shouldHaveNoDifferences() {
    String xml1 = "<b:some xmlns:b=\"A\"><b:element>text</b:element></b:some>";
    String xml2 = "<a:some xmlns:a=\"A\"><a:element>text</a:element></a:some>";

    Diff diffWorking = DiffBuilder.compare(Input.fromString(xml1))
        .withTest(Input.fromString(xml2))
        .checkForSimilar()
        .build();

    assertFalse(diffWorking.toString(), diffWorking.hasDifferences());

    Diff diffBroken = DiffBuilder.compare(Input.fromString(xml1))
        .withTest(Input.fromString(xml2))
        .checkForSimilar()
        .withDifferenceEvaluator(new PlaceholderDifferenceEvaluator())
        .build();

    assertFalse(diffBroken.toString(), diffBroken.hasDifferences());
  }

}
```

### Expected behavior
Independent of the usage of `PlaceholderDifferenceEvaluator` the `.checkForSimilar()` setting should be respected.

### Context
Currently, this is blocking me from using [https://github.com/mock-server/mockserver](https://github.com/mock-server/mockserver/blob/master/mockserver-core/src/main/java/org/mockserver/matchers/XmlStringMatcher.java#L57) for testing XML requests, as there are random namespace prefix differences which result in flaky tests if the `.checkForSimilar()` setting is not working as expected.

**Comment by bodewig** [comment]
You are replacing the default difference evaluator with your own, which contains some rules about which difference is `SIMILAR` and which is not. The way to go here is to chain the default evaluator after `PlaceholderDifferenceEvaluator` so it can downgrade some differences.

```
    .withDifferenceEvaluator(DifferenceEvaluators.chain(new PlaceholderDifferenceEvaluator(), DifferenceEvaluators.Default))
```

could work. It may downgrade differences you do not want to downgrade, though. An alternative might be to explicitly just downgrade the random differences you see by chaining a [downgradeDifferencesToSimilar](https://www.xmlunit.org/api/java/main/org/xmlunit/diff/DifferenceEvaluators.html#downgradeDifferencesToSimilar-org.xmlunit.diff.ComparisonType...-) to `PlaceholderDifferenceEvaluator` .

**Comment by KaiStapel** [comment]
Both work!
```
        .withDifferenceEvaluator(DifferenceEvaluators.chain(new PlaceholderDifferenceEvaluator(), DifferenceEvaluators.Default))
```
and
```
        .withDifferenceEvaluator(DifferenceEvaluators.chain(new PlaceholderDifferenceEvaluator(), DifferenceEvaluators.downgradeDifferencesToSimilar(NAMESPACE_PREFIX)))
```

Now I only have to create a pull request for Mock Server.

Thank you very much.

**Comment by bodewig** [comment]
glad I could help.

**Comment by KaiStapel** [comment]
FYI: https://github.com/mock-server/mockserver/pull/1028
