### ISSUE TITLE
Can XMLUnit ignore character case?

### ISSUE THREAD

**Issue by TheEnjoy** [xmlunit/xmlunit#218]
Hello everyone, thanks for the awesome development and support, it helps a lot. I have a question that was already open, but I could not find an answer to it.
How can I ignore letters of different sizes (cases)?

String xml1 = "<code><lang name= 'java'>object oriented</lang></code>";
String xml2 = "<code><lang name= 'java'>ObJeCt OrIeNtEd</lang></code>";
        Diff diff = new Diff(xml1, xml2);
        assertTrue(diff.similar());

https://sourceforge.net/p/xmlunit/discussion/73274/thread/83787a94/

**Comment by TheEnjoy** [comment]
For example, I can do something like
if(
comparison
.getControlDetails()
.getTarget()
.getTextContent()
.equalsisIgnoreCase(
comparison
.getTestDetails()
.getTarget()
.getTextContent())
)
return EQUAL/Simular

but it not good solution for me

**Comment by bodewig** [comment]
The same answer I gave 13 years ago still is valid :-)

A case insensitive comparison is rare enough that it has never been added to XMLUnit. In XMLUnit 2.x you want to implement `DifferenceListener` and its implementation would be very similar to the 1.x `DifferenceListener` that now lives in https://github.com/xmlunit/xmlunit/blob/main/xmlunit-legacy/src/main/java/org/custommonkey/xmlunit/examples/CaseInsensitiveDifferenceListener.java

**Comment by TheEnjoy** [comment]
It’s a pity, I don’t want to add this to every test (more than 200). I will come up with a solution) Thank you!
