### ISSUE TITLE
Can i use checkForSimilar and check value by xpath?

### ISSUE THREAD

**Issue by TheEnjoy** [xmlunit/xmlunit#219]
Hello, I have for example next XML expected result:
```
<com:Message>1234</>
<ns2:text>xml</>
```
and actual result:

```
<com:Message>34221</>
<ns2:text>xml</>
```

I use
  ```
  Diff myDiff = DiffBuilder.compare(Input.fromString(expected))
            .withTest(Input.fromString(actual))
            .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndAllAttributes,ElementSelectors.byNameAndText))
            .checkForSimilar()
            .build();
```

With this use (checkForSimilar), my comparison goes without errors and this is wrong. I cannot change it to checkForIdentity.

How can you check for the value of this parameter? Without changing checks for other elements? I tried through filters and xpath but couldn't

So, my task is to check the Message values for identity and not similarity, and only this parameter, not others

**Comment by bodewig** [comment]
I don't think checkForIdentical/Similar is what you want to be looking at. If I correctly understand what you want to do then you should be looking at is to provide a `DifferenceEvaluator`of your own, see https://github.com/xmlunit/user-guide/wiki/DifferenceEvaluator . You want to say "a difference in text content can be ignored if it happens on an element with a certain XPath, which would be something like

```
    @Override
    public ComparisonResult evaluate(Comparison comparison, ComparisonResult outcome) {
        if (ComparisonType.TEXT_VALUE == comparison.getType()
            && outcome !=  ComparisonResult.EQUAL
            && SOME_XPATH.equals(comparison.getControlDetails().getXPath())) {
            return ComparisonResult.EQUAL;
        }
        return outcome;
    }
```

if you set `DifferenceEvaluators.chain(DifferenceEvaluators.Default, YOUR_IMPLEMENTATION)` then you should be able to suppress the specific difference.

**Comment by TheEnjoy** [comment]
@bodewig The problem is that I always have different DifferenceEvaluators, in which case I can use a combination?
That is, I have N tests and each one uses its own DifferenceEvaluators

**Comment by bodewig** [comment]
Well, in some way you will have to tell XMLUnit which XPath' differences are not relevant to you. My example code above can certainly be made more flexible than that if you know ho to identify the element to ignore.

Another approach may be to use a `NodeFiltter` and remove the element from the document completely, or just the nested text if you still want to ensure the element itself is present. But even in this case you will need a way to identify the element in question for your tests as well.

**Comment by TheEnjoy** [comment]
Thanks!
