### ISSUE TITLE
Can I use xmlunit to compare html content?

### ISSUE THREAD

**Issue by tutufool** [xmlunit/xmlunit#221]
I tried, but it seems the default behavior will expect a standard xml, for example:

[Fatal Error] :86:5: The element type "link" must be terminated by the matching end-tag "</link>".

Just curious whether there's some setting can allow the comparator runs in a "non-strict" mode that can compare html

**Comment by phbenisc** [comment]
Actually interesting question. 

I am reasonably sure, that xmlunit was not designed with that use case in mind.
In most cases you will hit a XML Parser, which will reject your input, when your html is not xml compliant .

That being said `Input` allows to add a `org.w3c.dom.Document` which could also represent a html doc.
Also the `DOMDifferenceEngine` also works with the `org.w3c.dom` classes.
I would have expected that the implementation is more incompatible with your use case, but I think you might be able to trick xmlunit to processing your html.  

But I have not tested any of that. Maybe @bodewig knows more.

**Comment by bodewig** [comment]
@phbenisc is correct, if you somehow manage to create a valid DOM `Document` or `Node` from your HTML, then XMLUnit will work, as it only relies on the Java DOM API. If you use any of the other supported `Input` variants like a string or a stream, XMLUnit will throw it unchanged at an XML parser.

Many many moons ago I used something called tagsoup to parse HTML into a SAX event stream, but that seems to have fallen off the internet. JTidy and NekoHTML are about the same age and could be options (I haen't worked with either and not checked they'd actually work for your case). 

The xmlunit-legacy module contains a `HtmlDocumentBuilder` that predates me getting involved with XMLUnit. It depends on Swing.

**Comment by tutufool** [comment]
Thanks a lot! I'll give it a try

**Comment by bodewig** [comment]
It would be good if you could report back any success (or no success) story here so people who stumble over this issue can benefit from your experience. Thank you.

**Comment by tutufool** [comment]
I just tried with below code: (leverage https://jsoup.org/)


    org.w3c.dom.Document primary = W3CDom.convert(Jsoup.parse(html1));
    org.w3c.dom.Document candidate = W3CDom.convert(Jsoup.parse(html2));
    Diff diff = DiffBuilder.compare(primary).withTest(candidate).ignoreComments().ignoreWhitespace().checkForSimilar()
        .build();

    diff.getDifferences().forEach(System.out::println);


Looks like it works with my sample html :)

**Comment by bodewig** [comment]
great, thank you very much @tutufool
