### ISSUE TITLE
showing differences when element order changed

### ISSUE THREAD

**Issue by ashu3654** [xmlunit/xmlunit#237]
Hello,

XML Unit should not show any differences when element order changed. But test case is failing and it's showing differences.

Please check below test, If it is an issue then please fix that. Please suggest if there is any workaround. 
```

@Test
    public void shouldNotGetDifferencesWithSimilarCellColumnsData() {
        String xml1 = "<Cells><Cell><Column><Data Code=\"D100A\" /><Data Code=\"D100B\" /></Column></Cell><Cell><Column><Data Code=\"D101A\" /><Data Code=\"D101B\" /></Column></Cell></Cells>";
        String xml2 = "<Cells><Cell><Column><Data Code=\"D101A\" /><Data Code=\"D101B\" /></Column></Cell><Cell><Column><Data Code=\"D100A\" /><Data Code=\"D100B\" /></Column></Cell></Cells>";

        Diff diff = DiffBuilder.compare(Input.fromString(xml1))
                .withTest(Input.fromString(xml2))
                .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndAllAttributes))
                .checkForSimilar()
                .build();

        Set<ComparisonResult> comparisonResults = new HashSet<>();
        for (Difference difference : diff.getDifferences()) {
            comparisonResults.add(difference.getResult());
            System.out.println(difference.toString());
        }
        Assertions.assertThat(diff.hasDifferences()).isFalse();
    }
```

**Comment by bodewig** [comment]
In your case the `Cell` nodes are swapped, right? The `Cell` nodes all have the same name and the same attributes (none at all), so `ElementSelectors.byNameAndAllAttributes` has no way of knowing they are in the wrong order.

What you need is a conditional selector that uses `ElementSelectors.byNameAndAllAttributes` by default and some other means when selecting matching `Cell`s. Whether it can be done by something built-in - like an XPath that says compare the first `Data` grandchild and make the nodes match if these nodes match - or you need to implement `ElementSelector` yourself because you cannot rely on the order of `Data` nodes and the logic is even more complex is hard to tell from your example test.

**Comment by Varshaav16** [comment]
code_snippet1
```java

Diff diff = DiffBuilder.compare(xml1)
                .withTest(xml2)
                .ignoreWhitespace()
                .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.conditionalBuilder()
                        .whenElementIsNamed("Column").thenUse(ElementSelectors.byXPath("./Data", ElementSelectors.byNameAndAttributes("Code")))
                        .elseUse(ElementSelectors.byName)
                        .build()))
                        .build();
```
code_snippet2
```java
Diff diff = DiffBuilder.compare(xml1)
                .withTest(xml2)
                .ignoreWhitespace()
                .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.conditionalBuilder()
                        .whenElementIsNamed("Cell").thenUse(ElementSelectors.byXPath("./Column/Data", ElementSelectors.byNameAndAttributes("Code")))
                        .elseUse(ElementSelectors.byName)
                        .build()))
                        .build();
```

How is code_snippet1 different from code_snippet2?
Why is code_snippet1 giving me the following error message?
>Expected child 'Column' but was 'null' - comparing <Column...> at /Cells[1]/Cell[1]/Column[1] to <NULL> (DIFFERENT)  
Expected child 'null' but was 'Column' - comparing <NULL> to <Column...> at /Cells[1]/Cell[1]/Column[1] (DIFFERENT)  
Expected child 'Column' but was 'null' - comparing <Column...> at /Cells[1]/Cell[2]/Column[1] to <NULL> (DIFFERENT)  
Expected child 'null' but was 'Column' - comparing <NULL> to <Column...> at /Cells[1]/Cell[2]/Column[1] (DIFFERENT)

Kindly help me out.
