### ISSUE TITLE
Comparing XML modes within the same String/File

### ISSUE THREAD

**Issue by hirenshah** [xmlunit/xmlunit#238]
Instead of having two XML files (ie `control.xml` and `test.xml`) I have the data in one, like:

```
<data>
	<previousVersion>
		...
	</previousVersion>
	<currentVersion>
		...
	</currentVersion>
</data>
```

The input does have other nodes, but I am interested in comparing just these two.  

Can the `.compare` and `.withTest` use the same source but filter on `<previousVersion>` for `.compare` and `<currentVersion>` for `.withTest`?

**Comment by hirenshah** [comment]
I managed to do this by:
`FileInputStream` > `BufferedReader` > `String`

Then using the XML tag names, `indexOf` and `substring` to create two more `String`.  

Probably not the tidiest or most efficient way though :(

**Comment by bodewig** [comment]
The "most XML" way would be to use XPath to pick the `previous|current` version elements and use the resulting `Node`s as input for `compare` and `withTest`. Or maybe you don't even need XPath at all. Read your original XML file into a DOM `Document` and locate the two `Node`s that you want to compare (here XPath may be handy, or not). `DifferenceEngine` works on DOM `Node`s and they can very well come from the same document.
