### ISSUE TITLE
Difference in the order of the tags in the two xmls 

### ISSUE THREAD

**Issue by marjanovicstefan** [xmlunit/xmlunit#241]
Hi, 

I'm comparing 2 xmls that differ in the order of the tags, but not in the value of those tags. 
Example: 
orgTest1.xml

```
<organization>
  <channels>
    <channel nickname="apitestchannel" channelName="EchoSign API Test Channel">
    </channel>
    <channel nickname="qausers" channelName="QA Users">
    </channel>
  </channels>
</organization>
```

orgTest2.xml
```
<organization>
  <channels>
    <channel nickname="qausers" channelName="QA Users">
    </channel>
    <channel nickname="apitestchannel" channelName="EchoSign API Test Channel">
    </channel>
  </channels>
</organization>
```

And Im executing following block of code: 

ClassLoader classLoader = getClass().getClassLoader();
    InputStream inputStream1 = classLoader.getResourceAsStream("accounts/orgTest1.xml");
    String org1 = new BufferedReader(
        new InputStreamReader(inputStream1, StandardCharsets.UTF_8))
        .lines()
        .collect(Collectors.joining("\n"));
    InputStream inputStream2 = classLoader.getResourceAsStream("accounts/orgTest2.xml");
    String org2 = new BufferedReader(
        new InputStreamReader(inputStream2, StandardCharsets.UTF_8))
        .lines()
        .collect(Collectors.joining("\n"));
    Diff diff = DiffBuilder.compare(Input.fromString(org1))
        .withTest(Input.fromString(org2)).checkForSimilar()
        .ignoreWhitespace()
        .ignoreElementContentWhitespace().withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byName)).build();

Assert.assertFalse(diff.toString(), diff.hasDifferences());

What I get as a output:
java.lang.AssertionError: Expected child nodelist length '2' but was '1' - comparing <channel...> at /organization[1]/channels[1]/channel[1] to <channel...> at /organization[1]/channels[1]/channel[1]

**Comment by bodewig** [comment]
it looks as if the content of attributes is needed to decide which `channel` to compare with which other `channel` element - `ElementSelectors.byName` completely ignores attributes. What you want is `ElementSelectors.byNameAndAttributes("channelName")` or something similar.

Please see https://github.com/xmlunit/user-guide/wiki/SelectingNodes
