### ISSUE TITLE
comparing xml files with namespace

### ISSUE THREAD

**Issue by marjanovicstefan** [xmlunit/xmlunit#242]
Hi,

I'm comparing 2 xml files. One is without namespace, and the other one has namespace. 

Example:

org1.xml

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<organization>
    <channels>
    </channels>
</organization>
```

org2.xml

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:organization xmlns="http://admin.api.echosign" xmlns:ns2="echosign.admin.api">
  <channels>
  </channels>
</ns2:organization>
```

Java code:

ClassLoader classLoader = getClass().getClassLoader();
    InputStream inputStream1 = classLoader.getResourceAsStream("accounts/org1.xml");
    String org1 = new BufferedReader(
        new InputStreamReader(inputStream1, StandardCharsets.UTF_8))
        .lines()
        .collect(Collectors.joining("\n"));
    InputStream inputStream2 = classLoader.getResourceAsStream("accounts/org2xml");
    String org2 = new BufferedReader(
        new InputStreamReader(inputStream2, StandardCharsets.UTF_8))
        .lines()
        .collect(Collectors.joining("\n"));

Diff diff = DiffBuilder
        .compare(Input.fromString(org1))
        .withTest(Input.fromString(org2))
        .checkForSimilar()
        .ignoreWhitespace()
        .ignoreElementContentWhitespace()
        .withAttributeFilter(attr -> !attr.getName().equals("shardName"))
        .withNodeFilter(node ->!node.getNodeName().equals("podMembership"))
        .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors
                                                    .conditionalBuilder().whenElementIsNamed("channel")
                                                    .thenUse(ElementSelectors.byNameAndAttributes("nickname","channelName"))
                                                    .whenElementIsNamed("account")
                                                    .thenUse(ElementSelectors.byNameAndAttributes("nickname"))
                                                    .whenElementIsNamed("user")
                                                    .thenUse(ElementSelectors.byNameAndAttributes("email"))
                                                    .whenElementIsNamed("pod")
                                                    .thenUse(ElementSelectors.byNameAndAttributes("name"))
                                                    .whenElementIsNamed("application")
                                                    .thenUse(ElementSelectors.byNameAndAttributes("name"))
                                                    .elseUse(ElementSelectors.byName).build()))
                                                    .build();

What I get as a output:
java.lang.AssertionError: Expected child 'organization' but was 'null' - comparing <organization...> at /organization[1] to <NULL>

**Comment by bodewig** [comment]
An element without a namespace and one with a namespace are different from an XML point of view. If you insist on considering them the same, you will run into problems with existing XML tools.

Having said that, you will need to provide an `ElementSelector` implementation of your own that ignores the namespace. There is no built-in selector that would. In addition you will need to provide a `DifferenceEvaluator` that ignores the namespaces as well.

**Comment by marjanovicstefan** [comment]
@bodewig can you provide me an example using code that I pasted above?

**Comment by bodewig** [comment]
I'm glad you solved it yourself.
