### ISSUE TITLE
ignoring specific empty tags

### ISSUE THREAD

**Issue by marjanovicstefan** [xmlunit/xmlunit#243]
Hi, 

I want to compare 2 xml files, and to ignore specific tag if he is empty only or if he doesn't have any attribute.

Example:

org1.xml:

```
<organization>
  <channels>
    <channel nickname="qausers" channelName="QA Users">
      <accounts>
        <account nickname="SignImsRESTV6TestAccount1">
          <pods>
            <pod name="Group1">
              <users>
                <user email="signims+ra+acc1group1admin@null.echosignmail.com"/>
              </users>
            </pod>
          </pods>
        </account>
      </accounts>
    </channel>
  </channels>
</organization>
```

org2.xml:

```
<organization>
  <channels>
    <channel nickname="qausers" channelName="QA Users">
      <accounts>
        <account nickname="SignImsRESTV6TestAccount1">
          <pods>
            <pod name="Group1">
              <users>
                <user email="signims+ra+acc1group1admin@null.echosignmail.com"/>
              </users>
            </pod>
            <pod/>
          </pods>
        </account>
      </accounts>
    </channel>
  </channels>
</organization>
```

In code above, I want to ignore empty tag <pod/> in the org2.xml.

Java code:

Diff diff = DiffBuilder
        .compare(Input.fromString(org1))
            .withTest(Input.fromString(org2))
        .checkForSimilar()
        .withNodeFilter(node -> !(node.getChildNodes().getLength()==0))
                    .build();

Code doesn't work, because when I change the value of user, test is passing, but it should not. Can anyone tell me the solution? Thanks!

**Comment by bodewig** [comment]
Unfortunately attributes are not child nodes in XML.

```
n -> n.hasChildNodes() || n.hasAttributes()
```

is probably closer to what you need.

**Comment by bodewig** [comment]
can we close this?
