### ISSUE TITLE
Ignoring namespaces in unordered xml files

### ISSUE THREAD

**Issue by marjanovicstefan** [xmlunit/xmlunit#244]
Hi,

I want to compare two unordered xml files and ignore namespace in them.

Example:

apitestchannelOrg.xml

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:organization xmlns:ns2="echosign.admin.api">
    <channels>
        <channel nickname="apitestchannel" channelName="EchoSign API Test Channel">
            .
            .
            .
        </channel>
    </channels>
</ns2:organization>
```

apitestchannelCreate.xml

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:organization xmlns:ns2="echosign.admin.api">
    <channels>
        <channel nickname="apitestchannel" channelName="EchoSign API Test Channel">
            .
            .
            .
        </channel>
    </channels>
</ns2:organization>
```

Java code:

Diff diff = DiffBuilder
        .compare(Input.fromString(org1))
        .withTest(Input.fromString(org2))
        .checkForSimilar()
        .ignoreWhitespace()
        .ignoreElementContentWhitespace()
        .withAttributeFilter(attr -> !attr.getName().equals("shardName")
            && !attr.getName().equals("displayName"))
        .withDifferenceEvaluator(DifferenceEvaluators.chain(DifferenceEvaluators.Default, new DifferenceEvaluator() {
          @Override
          public ComparisonResult evaluate(Comparison comparison, ComparisonResult comparisonResult) {
            if(comparison.getType() == ComparisonType.NAMESPACE_URI){
              return ComparisonResult.SIMILAR;
            }
            return comparisonResult;
          }
        }))
        .withNodeFilter(node ->
                            !node.getNodeName().equals("settings")
                                && !node.getNodeName().equals("podMembership"))
        .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors
                                                    .conditionalBuilder()
                                                    .whenElementIsNamed("channel")
                                                    .thenUse(ElementSelectors.byNameAndAttributes("nickname","channelName"))
                                                    .whenElementIsNamed("account")
                                                    .thenUse(ElementSelectors.byNameAndAttributes("nickname"))
                                                    .whenElementIsNamed("user")
                                                    .thenUse(ElementSelectors.byNameAndAttributes("email"))
                                                    .whenElementIsNamed("pod")
                                                    .thenUse(ElementSelectors.byNameAndAttributes("name"))
                                                    .whenElementIsNamed("application")
                                                    .thenUse(ElementSelectors.byNameAndAttributes("name"))
                                                    .elseUse(ElementSelectors.byName).build()))
        .build();

What I get as a output:
java.lang.AssertionError: Expected child 'channels' but was 'null' - comparing <channels...> at /organization[1]/channels[1] to <NULL>

I believe I can not use XPath because then I can;t compare 2 unordered files, or at least I could not do it. Can anyone please provide me an solution? Thanks!

**Comment by bodewig** [comment]
I can't see from your example why you think you need to ignore namespaces - both documents have `channel` elements in the default namespace which seems to be the [null namespace](https://docs.oracle.com/javase/7/docs/api/javax/xml/XMLConstants.html#NULL_NS_URI).

If the two `channel` elements really belong to different XML namespaces then `byNameAndAttributes` simply will not work and you need to provide an `ElementSelector` that ignored namespaces URIs -> #242 

If XPath fails for you then the reason most likely is "namespaces" as well. If your elements are not part of the null namespace you must use prefixes inside of your XPath expressions and use the `byXpath` variants that accept a map as context to map from your prefixes to namespace URIs. This will obviously only work if the namespace URIs on either side are the same.

**Comment by marjanovicstefan** [comment]
I accidentally deleted xmlns in the second xml. It would be like:

```
<ns2:organization xmlns="http://admin.api.echosign" xmlns:ns2="echosign.admin.api">
.
.
.
</ns2:organization>
```

**Comment by bodewig** [comment]
no., that's been there. But your ´channel` elements haven't got any prefix, so I assume they are in the default namespace which doesn't seem to be associated with any namespace URI.
