### ISSUE TITLE
Project targets at Java 7, but requires Java 8 deps when runs at Java 9+

### ISSUE THREAD

**Issue by michael-o** [xmlunit/xmlunit#248]
I am working on Maven Doxia and recently upgraded xmlunit-core, the GH action tells me this:
https://github.com/apache/maven-doxia/runs/4827147809?check_suite_focus=true#step:5:1729

The project is still targeted at Java 7, so is xmlunit. We test with multiple JDK versions, as soon as Java 11 is used a Java 8 dependency is sourced. This contradicts the project's target at 7. Enforcer rejects the build. While I could upgrade to Java 8, but for the wrong reasons.

This snippet does not mention that actually Java 8 bytecode level will be required:
```
If you are using Java 9 or later the core also depends on the JAXB API. This used to be part of the standard class library but has been split out of it with Java 9.

If you want to use Input.fromJaxb - i.e. you want to serialize plain Java objects to XML as input - then you also need to add a dependency on the JAXB implementation. Starting with XMLUnit 2.6.4, xmlunit-core optionally depends on the JAXB reference implementation and its transitive dependencies. Starting with XMLUnit 2.8.0 the JAXB dependency requires the JakartaEE version of JAXB.
```

Is GlassFish JAXB from javax namespace in version 2.x not more than enough for this project?

**Comment by bodewig** [comment]
xmlunit-core depends on jakarta.xml.bind-api 2.3.3 and the glassfish implementation of the same version so I'm not sure what you are asking. Sorry.

TBH I also don't understand what enforcer is complaining about. xmlunit-core does require JAXB 2.x - as Oracle decided to remove JAXB from the standard classlib - when run with Java 9+, yes, but this obviously doesn't affect using it on Java 7. :-) Without the dependency the xmlunit-core wouldn't compile on Java 9+.

If the enforcer plugin doesn't support configuring exceptions (never really used it myself) you could try to exclude the dependencies it complains about.

**Comment by michael-o** [comment]
I see two options:
1. Depend on a JAXB version compiled for Java 7
2. Clearly document that you depend on Java 8 under some conditions

**Comment by bodewig** [comment]
We have two issues here, that I may be mixing in my mind.

The first problem is I don't believe the warning by enforcer is correct. You should be able to use xmlunit-core compiled on Java 9 running on Java 7 without any problem. All releases have been built on Java8 so far, so when we talk about binaries obtained from Maven Central the point is moot anyway.

The second problem is I don't believe XMLUnit had any choice but adding the dependencies, so I don't think I could have avoided it. There is no "JAXB version compiled for Java 7" except for the one that is part of the Java class library of Java 7 AFAIK.

I have just re-structured JAXB support a bit with #247 to make things more complicated :-)

If you have an idea of what exactly you'd like to write me at which place I'll be happy to do so. I don't really know what to write as I still fail to understand why anything needs to be documented at all - and I'm sure this is all my fault, don't get me wrong.

**Comment by michael-o** [comment]
There is the crap Oracle did: https://github.com/eclipse-ee4j/jaxb-ri/commit/edaa936848bd03079b2764c6916b86e59e182b5c#diff-bd9506071843e5895e18cf5c1dc694505594a2d55b2c39193307f30b65f2694eR185-R186

Between 2.3.2-RI and 2.3.3-RI they upgraded to Java 8, in a patch release. WTF!
Ideally, as long as xmlunit targets Java 7 byte level compat I would expect you to stick with 2.3.2-RI unless you can explain that you need features/fixes beyond this version.

**Comment by michael-o** [comment]
Let me also look into Enforcer also.

**Comment by michael-o** [comment]
Checked Enforcer, it comes from a parent POM, no surprise, and this is enforced: https://www.mojohaus.org/extra-enforcer-rules/enforceBytecodeVersion.html
Well, I could try to override this execution and either skip `test` scope or a particular dependency.

**Comment by bodewig** [comment]
I'm afraid I can't easily downgrade the dependency without breaking backwards compatibility. Back when JAXB was removed from the classlib I must admit I didn't really look too closely and just wanted to make things work.

Note that the RI is a runtime dependency. The compile time dependency is on the API only and I'd expect that to be identical to the in-classlib version of Java 7 - that's why I believe there is no practical impact on Java 7 users even if you compile XMLUnit on any Java 11+ version that allows to target Java 7 bytecode.

**Comment by bodewig** [comment]
I'm not sure what you are doing with XMLUnit in Doxia, but if you don't use JAXB at all, you could probably exclude the dependency on JAXB completely without impacting your tests.

**Comment by michael-o** [comment]
> 

I will check that....

**Comment by michael-o** [comment]
> I'm not sure what you are doing with XMLUnit in Doxia, but if you don't use JAXB at all, you could probably exclude the dependency on JAXB completely without impacting your tests. XMLUnit only depends on JAXB as a way to provide XML input, it doesn't use it for anything else.

I will check that.

**Comment by michael-o** [comment]
@bodewig You were right, I was able to exclude those deps. The tests don't require them.  I have excluded them: https://github.com/apache/maven-doxia/commit/03e312be1f7d8050a2ff0815ffc8a54d6c00ab8a
Though, the issue remains maybe for others. I am fine with a note in the README.

**Comment by bodewig** [comment]
I still feel I don't understand the problem well enough to put anything into the README.

This is what I understand: When built on Java 9+ xmlunit-core is compiled against Jakarta EE 2.x which itself may use Java8 bytecode depending on the concrete version but the API itself does not use any Java8 thingy and in fact is identical to the one provided by the Java 7 class library. When using xmlunit-core on Java 7 (or 8) the dependency is not required and xmlunit-core works with JAXB no matter which version of Java has been used to build it.

I really don't know hat to document.

**Comment by bodewig** [comment]
@michael-o I've added https://github.com/xmlunit/user-guide/wiki/JAXB#maven-enforcer-complains-about-xmlunit-core-targetting-java-7-but-having-a-java-8-dependency - do you think this is sufficient to close the issue?

**Comment by michael-o** [comment]
Ideal description. Thanks 😊

**Comment by bodewig** [comment]
thank you
