### ISSUE TITLE
withNodeFilter silently overwrites previous set NodeFilter, should throw exception

### ISSUE THREAD

**Issue by geertschuring** [xmlunit/xmlunit#249]
The documentation for `CompareMatcher.withNodeFilter(...)` says `Registers a filter for nodes` so I created two nodefilters and used them like this:

```
assertThat(actualMessage, isSimilarTo(expectedMessage)
	.withNodeFilter(new NodeFilterA())
	.withNodeFilter(new NodeFilterB())
);
```

When this did not work as expected I thought my implementation of the Predicate was incorrect. Only after randomly trying to change things I figured out that only 1 Predicate could be registered as NodeFilter and the documentation was incorrect, or at least incomplete. It should read `Registers the filter for nodes` or `Registers and overwrites the filter for nodes`.
Also, when called multiple times it should throw an exception explaining that a second call would overwrite the previously set filter.

**Comment by bodewig** [comment]
Actually, this is not only true for `withNodeFilter` - the other `with...` .operations overwrite as well without throwing any exceptions.

I'm fine with clarifying the javadocs and the user's guide, but wouldn't want to change the behavior.

Maybe I should add some sort of composition API in `NodeFilters` or `Predicate` to enable your use case - even though I'm not sure whether you expect the result to accept `Nodes` where ate least one filter returns `true` (OR) or only those where both return `true` (AND).

**Comment by bodewig** [comment]
I've updated the docs with eb7cc2c and added `NodeFilters.satisfiesAny|All` methods with 4d9a854

**Comment by geertschuring** [comment]
Thanks!
