### ISSUE TITLE
Handle multiple syntax of empty tag

### ISSUE THREAD

**Issue by Kanti1702** [xmlunit/xmlunit#251]
I have xml comparision requirment in test cases where empty tag can be in 2 different format like below:
`<emptyTag></emptyTag>`  or
`<\empty>`

With the current implementation, it's treating these 2 formats as different nodes, and my assertion getting failed.

**Comment by Boiarshinov** [comment]
I tried to compare two XML's with empty tag and selfclosing tag with XmlUnit and it's find them equals.
```
    @Test
    public void testEmptyTag() {
        String controlXml = "<a><b></b></a>";
        String testXml = "<a><b/></a>";

        Diff myDiff = DiffBuilder.compare(controlXml)
            .withTest(testXml)
            .build();

        assertFalse(myDiff.hasDifferences());
    }
```

May be you use wrong syntax for selfclosing tag.
In your example you used `<\empty>`, but the correct syntax is `<empty/>`.

**Comment by bodewig** [comment]
There shouldn't be any difference. Are you sure there is no linebreak between the opening and closing tag? In that case your document would contain "element content whitespace" and you may need to "normalize" the documents before you can compare them.
