### ISSUE TITLE
Possible to Ignore element by name using XmlAssert of the xmlunit-assertj3 module?

### ISSUE THREAD

**Issue by bensullivan-ag** [xmlunit/xmlunit#254]
Hi

Is it possible to specify elements to ignore when comparing xml using assertj 3?

```
assertThat(createTestDocument())
.and(Input.fromFile("test-data/good.xml"))
.ignoringElements("foo", "bar")
.areIdentical();
```

Thanks

Ben

**Comment by bodewig** [comment]
[`withNodeFilter`](https://www.xmlunit.org/api/java/2.9.0/org/xmlunit/assertj3/CompareAssert.html#withNodeFilter-org.xmlunit.util.Predicate-) is what you are looking for. Something like

```java
.withNodeFilter(n -> !(n instanceof Element && ("foo".equals(n.getLocalName()) || "foo".equals(n.getNodeName())))
```
