### ISSUE TITLE
Determine which elements/attributes were added and which were removed

### ISSUE THREAD

**Issue by stn1slv** [xmlunit/xmlunit#257]
Could you please suggest if it is possible to determine the difference? For example:

- new XML element added (including the name of the element and XPath)
- new XML attribute added (including the name of the element, name of the attribute, and XPath)
- XML element removed (including the name of the element and XPath)
- XML attribute removed (including the name of the element, name of the attribute, and XPath)
- etc.

Something like a human-readable changelog.

**Comment by bodewig** [comment]
every difference you find is returned as a [`Difference`](https://www.xmlunit.org/api/java/2.9.0/org/custommonkey/xmlunit/Difference.html).

Added or removed elements will show up as [`CHILD_NODE_NOT_FOUND`](https://www.xmlunit.org/api/java/2.9.0/org/custommonkey/xmlunit/DifferenceConstants.html#CHILD_NODE_NOT_FOUND_ID) when looking at the `id` of the difference. It is added when the control node detail is null and removed when the test node detail is null. The node details contain the XPath.

For attributes it is the same, only the id is `ATTR_NAME_NOT_FOUND_ID` instead.

You may want to read https://github.com/xmlunit/user-guide/wiki/Comparing-XML

**Comment by stn1slv** [comment]
Thank you a lot for the answer. 

Should I use **xmlunit-legacy:2.9.0** (org.custommonkey.xmlunit.Difference) or is it possible with **XMLUnit 2.x** (org.xmlunit.diff.Difference)?

I tried to implement it in the following way:
```
       Diff d = DiffBuilder.compare(Input.fromString(currentXml)).withTest(Input.fromString(newXml))
                .ignoreComments()
                .ignoreWhitespace()
                .normalizeWhitespace()
                .ignoreElementContentWhitespace()
                .build();

        Iterator<Difference> difItr = d.getDifferences().iterator();
        while (difItr.hasNext()) {
            Difference df = difItr.next();
            System.out.println("Type: " + df.getComparison().getType().name());
            //  System.out.println("Details: " + df.getComparison().toString());
        }
```
where I didn't find some related difference types.

**Comment by bodewig** [comment]
ah, my fault, I linked to the wrong Javadoc and went from there. `org.xmlunit.diff.Difference` is what I intended and with that the https://www.xmlunit.org/api/java/2.9.0/org/xmlunit/diff/ComparisonType.html enum - and not some int constants.

xmlunit-legacy provides an API compatible with XMLUnit 1.x and I've just not taken enough care when I

**Comment by stn1slv** [comment]
Thank you a lot for the help
