### ISSUE TITLE
AttributeFilter with nodematcher

### ISSUE THREAD

**Issue by aceankit99** [xmlunit/xmlunit#259]
Hi Stefan,

I want to find out the difference between 2 xml file, ignoring few attribute of a node.

my XML-`</AssignedContent>
							<AssignedContent ContentClass="FKN" IsRequired="false">
								<ContentAttributes>
									<ContentAttribute AttributeName="PARAMETER-ABHAENGIGKEITe" CommentRequired="N"
										Description="Parameterabhängigkeit der Funktion" Group="FKN" LockedForGUI="R" MultipleValues="false"
										OnlyNormValues="false" Required="false" ShowNulls="true">
										<ContentGrants/>
									</ContentAttribute>
								</ContentAttributes>
							</AssignedContent>`

code which i tried-

`		Diff diffs = DiffBuilder.compare(Source).withTest(Source2).ignoreComments().ignoreWhitespace()
		  .ignoreElementContentWhitespace().checkForSimilar()
		  .withNodeMatcher(new DefaultNodeMatcher(
		    ElementSelectors.conditionalBuilder().whenElementIsNamed("ContentAttributes")
		    .thenUse(ElementSelectors.byXPath("./ContentAttribute/text()",
		      ElementSelectors.byNameAndAttributes("Description")))
		    .elseUse(ElementSelectors.byNameAndAllAttributes).build()))
		  .withAttributeFilter(attr -> (attr.getName().equals("AttributeName"))

		    .withAttributeFilter(attr -> attr.getName().equals("AttributeName"))
		    .build();`

I tried with both withAttributeFilter and withDifferenceEvaluator but its not working. I wanted to ignore the AttributeName attribute of ContentAttribute .

Thanks

**Comment by bodewig** [comment]
Sorry, the formatting of your example makes it almost impossible to see what you are looking for. In particular there is only one XML.

```java
    .withAttributeFilter(attr -> attr.getName().equals("AttributeName"))
```

says: Only look at attributes named `AttributeName`, ignore all other attributes. I can only guess this is the exact opposite of what you want.

Unfortunately you don't say what result you get that you are not expecting - and also not what you tried "withDifferenceEvaluator", so it is hard to help here.

**Comment by aceankit99** [comment]
Hi Stefan,

Thanks for the reply.I got the point, but i want to clear one doubt 

`			Diff diffs = DiffBuilder.compare(control).withTest(test).ignoreComments().ignoreWhitespace()
			  .ignoreElementContentWhitespace().checkForSimilar()

			  .withNodeMatcher(new DefaultNodeMatcher(
			    ElementSelectors.conditionalBuilder().whenElementIsNamed("VersionAttributes")
			    .thenUse(ElementSelectors.byXPath("./VersionAttribute/text()",
			      ElementSelectors.byNameAndAttributes("AttributeName")))
			    .elseUse(ElementSelectors.byNameAndAllAttributes).build()))`

Here what is the use of `ElementSelectors.byNameAndAttributes("AttributeName")`. The code is saying to compare by AttributeName or it has some different meaning.

**Comment by bodewig** [comment]
Please see https://github.com/xmlunit/user-guide/wiki/SelectingNodes for a more comprehensive answer.

Your setup says:

Whenever XMLUnit looks at a list of elements and tries to decide which of the elements in the list that belongs to the control document to compare to which of the elements in the list of the test elements, then

* if the XML element I'm looking at has the name "VersionAttributes" then grab the nested text of the first "VersionAttribute" child and apply the second element selector to it. I could explain what would happen then, but in your case nothing sensible will happen as the nested text is not an XML element at all. The XPath expression must yield an element, not a text. Let's assume for a moment the XPath yielded an element, then the second ElementSelector would be applied to the elements of both lists.
* if the element has any other name then compare it to the element of the test list that has the same name and the same attribute values for all attributes

Say your control doc is

```xml
<root>
  <VersionAttributes>
    <VersionAttribute>1</VersionAttribute>
  <VersionAttributes>
  <a test="1"/>
  <a test="2" foo="bar"/>
  <a test="2"/>
  <VersionAttributes>
    <VersionAttribute>2</VersionAttribute>
  <VersionAttributes>
</root>
```

and your test document

```xml
<root>
  <VersionAttributes>
    <VersionAttribute>2</VersionAttribute>
  <VersionAttributes>
  <a test="2"/>
  <a test="2" foo="bar"/>
  <a test="1"/>
  <VersionAttributes>
    <VersionAttribute>1</VersionAttribute>
  <VersionAttributes>
</root>
```

then

* the VersionAttributes children of either list will not get compared to anything at all as the XPath expression doesn't work.
* the first control "a" will be compared to the last test "a" as this is the only one where all attributes match
* the second control "a" will be compared to the second test "a". Even though the first test "a" matches on the "test" attribute, it doesn't match **all** attributes. `ElementSelectors.byNameAndAttributes("test")` would have picked the first test "a" as it is expected ot grab the first one with the same value in the "test" attribute and only the "test" attribute.

**Comment by aceankit99** [comment]
Hi Stefan..thanks for the reply.

Lets say there is there are other attributes called "test2","test3" but it is not mentioned in the ElementSelectors.byNameAndAttributes("test").

so if i write this code  
                                              `.withNodeMatcher(new DefaultNodeMatcher(
						ElementSelectors.conditionalBuilder().whenElementIsNamed("VersionAttributes")
								.thenUse(ElementSelectors.byXPath("./VersionAttribute",
										ElementSelectors.byNameAndAttributes("test")))
								.elseUse(ElementSelectors.byNameAndAllAttributes).build()))
		                                           .withAttributeFilter(attr->(attr.getName().equals("test")))`

so, here the xmls should be matched using attribute "test" and all other attributes apart from test will be ignored as i have used `.withAttributeFilter(attr->(attr.getName().equals("test")))`,is that correct?

**Comment by bodewig** [comment]
If you use `ElementSelectors.byNameAndAttributes` the only the listed attributes will be used to decide which elements to compare. It does not have any influence on whether differences are reported on the other attributes.

If you set an attribute filter, the attributes filtered out will be completely invisible to the comparison, so you should never see any differences related to these attributes.

I believe this is what you said, so yes, you are correct :-)

While reading your question I realized `ElementSelector`s (all of them) are completely unaware of attribute filters and always see all attributes. This is something I should document. And maybe I should add an `byNameAndAllAttributes(Predicate<Attr>)` that can be used if suppressed attributes might alter the node matching decision.

**Comment by aceankit99** [comment]
Thanks Stefan for the explanation.
