### ISSUE TITLE
Diff comparator doesnt ignore the order of nodes when using ElementSelectors.byNameAndText 

### ISSUE THREAD

**Issue by gitusersv** [xmlunit/xmlunit#262]
I'm comparing 2 xmls using "org.xmlunit.diff" in Java and it returns the differences with the following code.

```
public class XMLComparator {

public static void main(String[] args) {
    // Path to the XML files
    File file1 = new File("test1.xml");
    File file2 = new File("test2..xml");

    // Perform XML comparison
    try {
        Diff diff = DiffBuilder
                .compare(Input.fromFile(file1))
                .withTest(Input.fromFile(file2))
                .ignoreWhitespace()
                .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))
                .checkForSimilar()
                .build();  
        
        if (diff.hasDifferences()) {
            System.out.println("Differences found:");

            for (Difference difference : diff.getDifferences()) {
                System.out.println(difference.toString());
            }
        } else {
            System.out.println("No differences found.");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

```
**test1.xml**
```
<projectAreasWrapper><projectArea>
		<fullName>SSCELL</fullName>
		<id>_6MrXgEx7Ee6GUol3yT5KIw</id>
		<members>
			<AD_ID>yyyyyy</AD_ID>
			<DNG_ID>bbbbb</DNG_ID>
			<roles>
				<name>Author</name>
			</roles>
		</members>
		<members>
			<AD_ID>xxxxxx</AD_ID>
			<DNG_ID>aaaaaa</DNG_ID>
			<roles>
				<name>Author</name>
			</roles>
		</members>
</projectArea></projectAreasWrapper>

```

**test2.xml**

```
<projectAreasWrapper><projectArea>
		<fullName>SSCELL</fullName>
		<id>_6MrXgEx7Ee6GUol3yT5KIw</id>
		<members>
			<AD_ID>xxxxxx</AD_ID>
			<DNG_ID>aaaaaa</DNG_ID>
			<roles>
				<name>default</name>
			</roles>
		</members>
		<members>
			<AD_ID>yyyyyy</AD_ID>
			<DNG_ID>bbbbb</DNG_ID>
			<roles>
				<name>Administrator</name>
			</roles>
			<roles>
				<name>Author</name>
			</roles>
			<roles>
				<name>default</name>
			</roles>
		</members>
</projectArea></projectAreasWrapper>
```

I get the following output when using the xml files 

`Differences found:
Expected child 'name' but was 'null' - comparing <name...> at /projectAreasWrapper[1]/projectArea[1]/members[1]/roles[1]/name[1] to <NULL> (DIFFERENT)
Expected child 'null' but was 'name' - comparing <NULL> to <name...> at /projectAreasWrapper[1]/projectArea[1]/members[1]/roles[1]/name[1] (DIFFERENT)
Expected child 'AD_ID' but was 'null' - comparing <AD_ID...> at /projectAreasWrapper[1]/projectArea[1]/members[1]/AD_ID[1] to <NULL> (DIFFERENT)
Expected child 'DNG_ID' but was 'null' - comparing <DNG_ID...> at /projectAreasWrapper[1]/projectArea[1]/members[1]/DNG_ID[1] to <NULL> (DIFFERENT)
Expected child 'null' but was 'AD_ID' - comparing <NULL> to <AD_ID...> at /projectAreasWrapper[1]/projectArea[1]/members[1]/AD_ID[1] (DIFFERENT)
Expected child 'null' but was 'DNG_ID' - comparing <NULL> to <DNG_ID...> at /projectAreasWrapper[1]/projectArea[1]/members[1]/DNG_ID[1] (DIFFERENT)
Expected child nodelist length '3' but was '5' - comparing <members...> at /projectAreasWrapper[1]/projectArea[1]/members[2] to <members...> at /projectAreasWrapper[1]/projectArea[1]/members[2] (DIFFERENT)
Expected child 'name' but was 'null' - comparing <name...> at /projectAreasWrapper[1]/projectArea[1]/members[2]/roles[1]/name[1] to <NULL> (DIFFERENT)
Expected child 'null' but was 'name' - comparing <NULL> to <name...> at /projectAreasWrapper[1]/projectArea[1]/members[2]/roles[1]/name[1] (DIFFERENT)
Expected child 'AD_ID' but was 'null' - comparing <AD_ID...> at /projectAreasWrapper[1]/projectArea[1]/members[2]/AD_ID[1] to <NULL> (DIFFERENT)
Expected child 'DNG_ID' but was 'null' - comparing <DNG_ID...> at /projectAreasWrapper[1]/projectArea[1]/members[2]/DNG_ID[1] to <NULL> (DIFFERENT)
Expected child 'null' but was 'AD_ID' - comparing <NULL> to <AD_ID...> at /projectAreasWrapper[1]/projectArea[1]/members[2]/AD_ID[1] (DIFFERENT)
Expected child 'null' but was 'DNG_ID' - comparing <NULL> to <DNG_ID...> at /projectAreasWrapper[1]/projectArea[1]/members[2]/DNG_ID[1] (DIFFERENT)
Expected child 'null' but was 'roles' - comparing <NULL> to <roles...> at /projectAreasWrapper[1]/projectArea[1]/members[2]/roles[2] (DIFFERENT)
Expected child 'null' but was 'roles' - comparing <NULL> to <roles...> at /projectAreasWrapper[1]/projectArea[1]/members[2]/roles[3] (DIFFERENT)`

Appreciate input on how to get Comparator to ignore the order of ProjectArea or member or roles elements in the xmls above. Thanks.

**Comment by gitusersv** [comment]
@bodewig 
Appreciate if you have any input on the above. Thanks

**Comment by gitusersv** [comment]
With this condition, I'm able to ignore the order of members element but I need to ignore the order for roles and projectArea as well. Is it possible to ignore the order for multiple elements?
```
.whenElementIsNamed("members")
        			.thenUse(ElementSelectors.and(
        					ElementSelectors.byXPath("./AD_ID", ElementSelectors.byNameAndText),
        					ElementSelectors.byXPath("./DNG_ID", ElementSelectors.byNameAndText)))
        			.elseUse(ElementSelectors.byName)
        			.build();
```

**Comment by bodewig** [comment]
you are on the right track. You must make sure you make XMLUnit pick the correct elements to compare close enough to the root of the tree. So if you want to make sure you pick the correct `members` then `byNameAndText` simply is not good enough for this as there is no nested text in your `members` at all and you really need to decide on the content of nested elements as you do now.

If there are other elements that need to be re-ordered, you can chain more rules into the conditional selector you are already building. For example, you can insert

```
.whenElementIsNamed("roles").thenUse(ElementSelectors.byXPath("./name", ElementSelectors.byNameAndText)
```

right between your existing `thenUse` and the `elseUse` - `elseUse` only provides the default for everything not already matched by a `when` rule.

I was hoping https://github.com/xmlunit/user-guide/wiki/SelectingNodes was helping here, so if anything is missing please help improving that page.

**Comment by gitusersv** [comment]
@bodewig Thanks for your reply. I have come up with the following. This is nicely working for me ignoring the order of the ProjectArea/member/roles and the nested elements inside. But, only the issue is it taking long time about 55 minutes for to get the differences for the xml documents about the size 3.5MB. Appreciate any input on how to optimize it so that it can take less time.

`ElementSelector roleSelector = ElementSelectors.conditionalBuilder()
        			.whenElementIsNamed("roles")
        			.thenUse(ElementSelectors.byXPath("./name", ElementSelectors.byNameAndText))
        			.elseUse(ElementSelectors.byName)
        			.build();
        	
        	ElementSelector memberSelector = ElementSelectors.conditionalBuilder()
        			.whenElementIsNamed("members")
        			.thenUse(ElementSelectors.and(
        					ElementSelectors.byXPath("./AD_ID", ElementSelectors.byNameAndText),
        					ElementSelectors.byXPath("./DNG_ID", ElementSelectors.byNameAndText)))
        			.elseUse(roleSelector)
        			.build();
        	
        	ElementSelector paSelector = ElementSelectors.conditionalBuilder()
        			.whenElementIsNamed("projectArea")
        			.thenUse(ElementSelectors.and(
        					ElementSelectors.byXPath("./fullName", ElementSelectors.byNameAndText),
        					ElementSelectors.byXPath("./id", ElementSelectors.byNameAndText)))
        			.elseUse(memberSelector)
        			.build();
        	
        	
        	
            Diff diff = DiffBuilder
                    .compare(Input.fromFile(file1))
                    .withTest(Input.fromFile(file2))
                    .withNodeMatcher(new DefaultNodeMatcher(paSelector))
                    .ignoreWhitespace()`

**Comment by bodewig** [comment]
repeated XPath evaluation is probably killing performance. The best option probably is to implement `ElementSelector` yourself and implement the logic you need in Java code directly using the DOM API and not using XPath at all.

**Comment by bodewig** [comment]
Also I think

```
        	ElementSelector paSelector = ElementSelectors.conditionalBuilder()
        			.whenElementIsNamed("projectArea")
        			.thenUse(ElementSelectors.and(
        					ElementSelectors.byXPath("./fullName", ElementSelectors.byNameAndText),
        			.whenElementIsNamed("members")
        			.thenUse(ElementSelectors.and(
        					ElementSelectors.byXPath("./AD_ID", ElementSelectors.byNameAndText),
        					ElementSelectors.byXPath("./DNG_ID", ElementSelectors.byNameAndText)))
        					ElementSelectors.byXPath("./id", ElementSelectors.byNameAndText)))
        			.whenElementIsNamed("roles")
        			.thenUse(ElementSelectors.byXPath("./name", ElementSelectors.byNameAndText))
        			.elseUse(ElementSelectors.byName)
        			.build();
```

should work just the same, but I do not expect it to be significantly faster than your chained invocation.

**Comment by gitusersv** [comment]
Thanks for the response @bodewig . Custom implementation is lot of work at this point of time. I was wondering if there anyway to optimize the performance for eg: by changing/adjusting XPath above or by tuning the jvm config?

**Comment by bodewig** [comment]
Creating and using XPaths is slow and the declarative approach above you'll be evaluating three XPaths for each and every `members` element. There may be other issues involved but my best guess is that replacing the multiple XPath approach with a custom `ElementSelector` implementation that uses DOM and only DOM directly will improve the situation significantly.

A while back you said

> Custom implementation is lot of work at this point of time

I believe spending the time should be worth it if the pain is big enough.

**Comment by gitusersv** [comment]
Hi @bodewig 
Do you have any example for custom ElementSelector? Appreciate any input on how to create a custom ElementSelector for this requirement.

**Comment by bodewig** [comment]
All you need to do is to implement the `ElementSelector` interface. There really isn't anything special about "custom" selectors, so you could have a look at the built-in ones.

You need to understand Java's [DOM API](https://docs.oracle.com/javase/8/docs/api/org/w3c/dom/package-summary.html) for things to work.

```
.whenElementIsNamed("projectArea")
.thenUse(ElementSelectors.and(ElementSelectors.byXPath("./fullName", ElementSelectors.byNameAndText)
```

combines https://github.com/xmlunit/xmlunit/blob/main/xmlunit-core/src/main/java/org/xmlunit/diff/ElementSelectors.java#L607 , a lookup of a child element by name and https://github.com/xmlunit/xmlunit/blob/main/xmlunit-core/src/main/java/org/xmlunit/diff/ElementSelectors.java#L75 - which leads to something like

```java
String controlName = controlElement.getLocalName();
if (controlName == null) {
    controlName = controlElement.getNodeName();
}
String testName = testlElement.getLocalName();
if (testName == null) {
    testName = testElement.getNodeName();
}
if ("projectArea".equals(controlName) && "projectArea".equals(testName)) {
    NodeList controlChildren = controlElement.getElementsByTagName("fullName");
    NodeList testChildren = testElement.getElementsByTagName("fullName");
    if (controlChldren.getLength() > 0 && testChldren.getLength()) {
        return ElementSelectors.byNameText((Element) controlChildren.item(0), (Element) testChildren.item(0));
    }
}
```

this deliberately lacks most error handling and should extract repeating code into methods, this is only to give you an idea. TBH this all looks rather obvious.
