### ISSUE TITLE
Ignore Whitespace is trimming the whitespace inside the tag value.

### ISSUE THREAD

**Issue by vip99kr** [xmlunit/xmlunit#266]
When I'm using .ignoreWhitespace() in my DiffBuilder, it strips all the whitespaces inside and outside of the tags. 

For example:
XML1:
`<A>
<B>XXX</B>
</A>`

XML2:
`<A>
<B>   XXX</B>
</A>`

Here, when comparing by ElementSelectors.byNameAndText, it should give the comparison result as DIFFERENT. But since I've used 
`DiffBuilder.compare(beforeElement) 
				.withTest(afterElement)
				.ignoreComments()
				.ignoreWhitespace()
				.withNodeFilter(isTagIgnorable)
				.withNodeMatcher(nodeMatcher)
				.withDifferenceEvaluator(
						//Default implementation can be used in combination with custom impl
						DifferenceEvaluators.chain(
								differenceEvaluator.toArray(new DifferenceEvaluator[0])
								)) 
				.checkForSimilar()
				.build();`
This whitespace inside the tag value is getting trimmed. Is there a way I can remove the whitespaces outside of the tags, but not from the tag values.

When not using the .ignoreWhitespace(), it shows some additional differences which are not present in the actual XML.

**Comment by bodewig** [comment]
What you call "whitespace outside the tags" is called "Element Content Whitespace" in XML lingo. You want to use `ignoreElementContentWhitespace()` rather than `ignoreWhitespace`.

**Comment by vip99kr** [comment]
@bodewig Thank you for your response. I used ignoreElementContentWhitespace() and the comparison result is as per my requirement. Thank you!
