### ISSUE TITLE
Detecting new and missing elements and attributes 

### ISSUE THREAD

**Issue by chris-mcc** [xmlunit/xmlunit#27]
As part of my Testing framework project I am now at the point of having multiple blobs of XML test reports that I need to diff and report back on.

It would be useful if the XmlUnit Library could detect new and missing differences, as far as I can see it just looks for match or a difference.

Perhaps it would be useful to extend ComparisonResult to include the states new and Missing?

**Comment by bodewig** [comment]
I'm not sure I understand what you mean with a new or missing difference.

If XMLUnit detects an element in one of the documents that is not inside the other you'll see a `CHILD_LOOKUP` difference - if the test document has more elements the `ControlDetails` are `null`and vice versa.  For attributes there is a similar `ATTRIBUTE_LOOKUP` difference.  Is this what you are looking for?

**Comment by chris-mcc** [comment]
Sorry for the late reply.

ControlDetails looks like what I'm after, thanks didn't see it when I took a noisy.
