### ISSUE TITLE
Untyped collections mean casting is required

### ISSUE THREAD

**Issue by beresfordt** [xmlunit/xmlunit#34]
Within several classes in xmlunit-legacy there are untyped collections, for example DetailedDiff.

```java
public class DetailedDiff extends Diff {
    private final List allDifferences;
    ...
    public List getAllDifferences() {
    ...
```

This means users of the class will need to cast their uses of `getAllDifferences` - as can be seen in the unit tests in `test_DetailedDiff` eg:

```java
    public void testCompareUnmatched() throws Exception {
        String control = ...;
        String test = ...;
        DetailedDiff d = (DetailedDiff) buildDiff(control, test);
        List l = d.getAllDifferences();
        assertEquals(1, l.size());
        Difference diff = (Difference) l.get(0);
```

As xmlunit-legacy is being compiled to 1.6, which supports generics, the collections can be typed - removing the casting burden from users of the library

(in some places in xmlunit-legacy typed collections are already being used, for example Jaxp13XpathEngine.NodeListForIterable)

**Comment by bodewig** [comment]
Thanks!

I'll need to review #35 to see whether we'd keep compile time compatibility against 1.x this way - which is an implicit goal.  Changing internal fields and return types is fine, but changing method arguments would be problematic.

**Comment by bodewig** [comment]
I just had to restore a single constructor which proved to be trivial.  Thanks a lot.

**Comment by beresfordt** [comment]
No problem, glad to have helped
