### ISSUE TITLE
Provide a way to list child nodelists during a comparison failure of a childe nodelist length

### ISSUE THREAD

**Issue by Thunderforge** [xmlunit/xmlunit#36]
If a comparison failure exists such that `comparison.getType() == ComparisonType.CHILD_NODELIST_LENGTH`, the `toString()` message is as follows:

    Expected child nodelist length '5' but was '7' - comparing <baz...> at /foo[1]/bar[1]/baz[1] to <baz...> at /foo[1]/bar[1]/baz[1]

However, there is no way to programmatically retrieve the child nodelist from the `Comparison` object. This would be helpful for more thorough debugging messages, or for handling edge cases where some nodelist differences are acceptable depending on what that nodelist length is.

I would like to request a way to programmatically retrieve a list of child nodelists, from both `comparison.getControlDetails()` and `comparison.getTestDetails()`

**Comment by bodewig** [comment]
Isn't this `comparison.getControlDetails().getTarget().getChildNodes()`?

**Comment by Thunderforge** [comment]
It looks like this does indeed fit what we are looking for. We were using an outdated version of the library that did not have this. We've upgraded to a more recent version and now can make use of this.

**Comment by bodewig** [comment]
We've changed the type of Target from Object to Node at one point in time.  It's always been a Node, though.
