### ISSUE TITLE
element with namespace problem

### ISSUE THREAD

**Issue by lunevsv** [xmlunit/xmlunit#41]
In the returned result names of elements incorrectly are displayed.
Expected presence of child node '{http://localhost/doc_v01.01}businessContext' but was 'null' - comparing <doc:businessContext...> ...
The problem is {http://localhost/doc_v01.01}businessContext (but expected <doc:businessContext>). Why xmlunit put namespace value?

**Comment by bodewig** [comment]
I'm not sure I fully understand the problem.

Is the problem that XMLUnit is using the QName of the element (namespace-URI plus local name) in one place and the prefixed element name in the other?

**Comment by lunevsv** [comment]
yes.

**Comment by bodewig** [comment]
I see how this may be confusing.

The '{http://localhost/doc_v01.01}businessContext' QName may be better than `doc:businessContext` in cases where the namespace prefixes that are used inside of the documents are different.  In particular when stating what was expected.

OTOH when saying "comparing ..." it is probably better if the text is what you'd actually see inside of the documents - so you can locate the difference more easily.

Given the choices of

* using QNames everywhere and making it more difficult to spot the difference when looking at the documents
* using elements everywhere and hiding namespace details where they may be important
* being inconsistent by using QName here and the serialized XML there

I'd personally opt for the last one.
