### ISSUE TITLE
ignoreNamespacePrefix

### ISSUE THREAD

**Issue by brettbaudin** [xmlunit/xmlunit#42]
Is there some setting that would suppress differences in namespace prefixes?
Expected namespace prefix 'env' but was 'SOAP-ENV' - comparing <env:Envelope...> at /Envelope[1] to <SOAP-ENV:Envelope...> at /Envelope[1]

Brett

**Comment by bodewig** [comment]
When using `DifferenceListeners.Default` the difference in namespace prefix is downgraded to "similar". If that's not enough, you can always implement a `DifferenceListener` yourself.

**Comment by brettbaudin** [comment]
Thanks!

**Comment by koppor** [comment]
This currently does not help when comparing QNAmes:

    <tosca:PropertiesDefinition xmlns:wfrt="http://winery.opentosca.org/test/nodetypes/fruits" type="wfrt:BaobabProperties"/>

is not simpilar to

<tosca:PropertiesDefinition xmlns:wfrt1="http://winery.opentosca.org/test/nodetypes/fruits" type="wfrt1:BaobabProperties"/>

Even if it should, because `type` is declared as `xs:QName`.

     <xs:element name="PropertiesDefinition" minOccurs="0">
      <xs:complexType>
       <xs:attribute name="element" type="xs:QName"/>
       <xs:attribute name="type" type="xs:QName"/>
      </xs:complexType>
     </xs:element>

Is there an easy way to enable support for QName attributes?

**Comment by bodewig** [comment]
XMLUnit doesn't parse the Schema and thus only compares the stringified version of any attribute (or Text) values - with one exception: `xsi:type` from the Schema-Instance namespace.

What could work was a `DifferenceEvaluator` that looked at the target `Node`s (which should be `Attr`s) on `ATTR_VALUE` differences and used something like `DOMDifferenceEngine.valueAsQname` to repeat the comparison. And maybe some kind of conditional builder infrastructure for `DifferenceEvaluator`s similar to the one for `ElementSelector`s.

There is nothing like this currently built into XMLUnit.

If you think it would be a valuable extension, this should probably be a separate issue (and I'd immediately add the "HELP WANTED" tag ;-).
