### ISSUE TITLE
Ignore tree segments in comparison

### ISSUE THREAD

**Issue by brettbaudin** [xmlunit/xmlunit#43]
I am trying to figure out how to ignore segments of the XML structure preferably by defining a list of XPath statements to individual values or entire structures. I tried using withNodeFilter but it seems to only apply the filter to the document being compared. Causing "Expected child nodelist length" errors.
If expected result is:

&lt;a>
    &lt;b>value1&lt;/b>
    &lt;c>value2&lt;/c>
    &lt;d>value3&lt;/d>
&lt;/a>
Ignore paths /a/b (ignore b and any children) and ignore /a/d/text() (ignore the text value of d)
Then the following document would be similar.
&lt;a>
    &lt;c>value2&lt;/c>
    &lt;d>other text&lt;/d>
&lt;/a>
Any thoughts on how to approach this?
Brett

**Comment by bodewig** [comment]
Hmm, `NodeFilter` gets applied on both sides of the comparison.

Do you think you can extract a small testcase that demonstrates what you describe? I'm not sure what your implementation of `NodeFilter` looks like.

**Comment by brettbaudin** [comment]
Comparing XML is complicated. My node filter was comparing with getNodeName however one of the XML inputs had a namespace prefix on the node which caused the comparison to fail.
		 diffBuilder.withNodeFilter(new Predicate<Node>() {
			                         @Override
			                        public boolean test(Node n) {
			                             return !"GetQuoteResult".equals(n.getNodeName());
			                         }
			                 });
Using getLocalName will solve my problem though I would be ignoring namespaces.

**Comment by bodewig** [comment]
Wrapping `getNodeName` in a `QName` should help, something like `Nodes.getQName` in https://github.com/xmlunit/xmlunit/blob/master/xmlunit-core/src/main/java/org/xmlunit/util/Nodes.java#L40

`QName`'s `equals` ignores the NS prefix.

**Comment by brettbaudin** [comment]
Thanks. I am close now on what I want. Just one issue remains. Namespace prefixes need to be the same. See attached code.
[XPathFilter.txt](https://github.com/xmlunit/xmlunit/files/76301/XPathFilter.txt)

**Comment by brettbaudin** [comment]
Final solution. Probably not the most efficient but works.
[XPathFilter.txt](https://github.com/xmlunit/xmlunit/files/76352/XPathFilter.txt)

**Comment by bodewig** [comment]
At least it looks quite a bit more complex than I had expected.

Is there anything missing in XMLUnit that would have helped you or can we close this issue?

**Comment by brettbaudin** [comment]
Probably an internal implementation would more efficient but this is fine for me. I am closing. 
Thanks again.
