### ISSUE TITLE
Very small documentation issue

### ISSUE THREAD

**Issue by TomDok** [xmlunit/xmlunit#46]
XMLunit is something one really needs when testing against xml-files. Nice piece of work! Just what I was looking for. 

I found a very, very minor documentation-only thing:

At
    https://github.com/xmlunit/user-guide/wiki/DiffBuilder
in the Basic Example, I guess a not-operator is forgotten before "myDiff.hasDifferences()":

Assert.assertTrue(myDiff.toString(),         !         myDiff.hasDifferences());

Also in the api (file:///home/tom/bin/ac2_tools/xmlunit-2.0.0-alpha-03/index.html) the same omission resides.

**Comment by TomDok** [comment]
file:///home/tom/bin/ac2_tools/xmlunit-2.0.0-alpha-03/index.html is OK. There an assertFalse is used.

**Comment by bodewig** [comment]
Hmm, in the userguide's "Basic Example" the values of the attributes are different, so there should be differences. Am I looking at the wrong example?

**Comment by TomDok** [comment]
Hello Stefan

sorry for my late response. Attached is a screenshot from the page 
including URL of the Basic Example that I used for my first experience 
with xmlunit.

In the Basic Example: IF there are differences THEN 
myDiff.hasDifferences() returns true (which is OK), but since it is an 
argument of an AssertTrue it will then not raise an error. For the basis 
example to work fine: either a AssertFalse should be used or the 
myDiff.hasDifferences() should be negated.

Once again its a minor, minor thing. FYI: xmlunit is now part of my  
testlibs-set.

Kind regards,

Tom

**Comment by bodewig** [comment]
Thanks for taking your time explaining it, Tom.

The detail I overlooked was the line above the example that says "This example will throw an AssertionError" :-)

I'm sorry for being dense, again.
