### ISSUE TITLE
Using custom Element selector I'm still unable to match correct element

### ISSUE THREAD

**Issue by Kerruba** [xmlunit/xmlunit#49]
Hi, 
first of all thank you for this wonderful library, it's really great.

I'm having a problem comparing elements in different order within my xml document. I've developed a custom ElementSelector to use with the NodeMatcher (later the code) but still it seems to check based on element order more than element content.
Let me write an example

Control 
```xml
<Parent>
<Person>
<FirstName>John</FirstName>
<LastName>Doe</LastName>
<Email>johndoe@email.com</Email>
</Person>
<Person>
<FirstName>Mickey</FirstName>
<LastName>Mouse</LastName>
<Email>mm@email.com</Email>
</Person>
<Person>
<FirstName>John</FirstName>
<LastName>Doe</LastName>
<Email />
</Person>
</Parent>
```

Test
```xml
<Parent>
<Person>
<FirstName>Mickey</FirstName>
<LastName>Mouse</LastName>
<Email>mm@email.com</Email>
</Person>
<Person>
<FirstName>John</FirstName>
<LastName>Doe</LastName>
<Email>johndoe@email.com</Email>
</Person>
<Person>
<FirstName>John</FirstName>
<LastName>Doe</LastName>
<Email />
</Person>
</Parent>
```

How I made the `Diff`
```java
Diff diff = DiffBuilder.compare(refSource)
                            .withTest(testSource)
                            .checkForSimilar()
                            .ignoreWhitespace()
                            .normalizeWhitespace()
                            .withNodeMatcher(new DefaultNodeMatcher(selector))
                            .build();
```
How I created the ElementSelector `selector` 

```java
ElementSelector selector = ElementSelectors.conditionalBuilder()
                            .whenElementIsNamed("Person").thenUse(new PersonNodeMatcher())
                            .defaultTo(ElementSelectors.byNameAndText).build();
```

How is actually implemented the PersonNodeMatcher
```java
public class PersonNodeMatcher extends BaseElementSelector {

    @Override
    protected boolean canBeCompared(Element control, Element test) {

        String controlFirstName = control.getElementsByTagName("FirstName").item(0).getTextContent();
        String controlLastName  = control.getElementsByTagName("LastName").item(0).getTextContent();

        Node controlEmailNode = control.getElementsByTagName("Email").item(0);
        String controlEmail = null;
        if ( controlEmailNode != null) {
            controlEmail = controlEmailNode.getTextContent();
        }


        String testFirstName = test.getElementsByTagName("FirstName").item(0).getTextContent();
        String testLastName  = test.getElementsByTagName("LastName").item(0).getTextContent();


        Node testEmailNode = test.getElementsByTagName("Email").item(0);
        String testEmail = null;
        if (testEmailNode != null) {
            testEmail = testEmailNode.getTextContent();
        }

        return bothNullOrEqual(controlFirstName,testFirstName) &&
                  bothNullOrEqual(controlLastName,testLastName) &&
                  bothNullOrEqual(controlEmail,testEmail);

    }

```

The routine is still checking the nodes in order, so they will never match.
I thought that providing a node custom node matcher I would be able to check all the Element with the tagName provided.

Am I doing something wrong or simply is not possible?

**Comment by bodewig** [comment]
I've just realized you asked the same question on [Stackoverflow](http://stackoverflow.com/questions/34946271/xmlunit-2-0-unable-to-avoid-order-comparison-with-custom-element-selector) and I started answering there rather than here. That's not what I intended, sorry. Let's try t figure out the answer here or there and close both incarnations at the same time :-)

**Comment by Kerruba** [comment]
If you prefer we can close this issue and continue on Stackoverflow. Thank you for your help

**Comment by bodewig** [comment]
I'd like to document the conclusion here as well - and ensure the user guide reflects what we find on the way.

The issue of `ElementSelectors.or` vs varargs-`DefaultNodeMatcher` is already covered in https://github.com/xmlunit/user-guide/wiki/SelectingNodes#elementselectorsnot-and-or-and-xor (second paragraph). This change https://github.com/xmlunit/user-guide/wiki/SelectingNodes/_compare/5a2dfa4a1adcfbfe1c5aff7636268a5eff760ff1...c62c957810113e50f16f1e5f5e769e06788fc13c should help with the element-order difference, I hope.

If there's anything else that could be clearer, please help me improve it.

**Comment by Kerruba** [comment]
This is certainly helpful, thanks! Just to be sure I've understood it properly:
- the `varargs` methods compares all the nodes using the first element selector and only if no match is found use the second element selector to look for potential matching, in a "vertical way";
- the `ElementSelectors.or`, instead, works in a more "horizontal way". So takes the first pair of nodes to compare, and if one of the `ElementSelector` return true, he consider the two nodes as comparable.

Let's write an example just to be sure I was clear
```xml
<root>
    <a>testA</a>
    <b>testB</b>
    <a />
</root>
```
and 

```xml
<root>
    <a />
    <a>TestA</a>
    <b>TestB</b>
</root>
```

With `ElementSelectors.or` when the difference engine is comparing `<a>TestA</a>` with `<a />` the first `ElementSelector` return `false` but the second return `true` so he considers the nodes as comparable, leading then to a `CompareResults.DIFFERENCE`, while with `varargs` use the first `ElementSelector` to compare all available nodes, if none is found as comparable it moves to the second `ElementSelector`, leading in this case to a `CompareResults.SIMILAR`?

**Comment by bodewig** [comment]
yes, this is correct.

**Comment by Kerruba** [comment]
Great! What do you think if we structure then the wiki in a way that is more explicit about this way? Like a section inside the `Selecting node` called `Combining ElementSelectors`, where we can describe the difference between using the `varargs`  DefaultNodeMatcher and the other `ElementSelectors.or`, `.not`, `.and`, `.xor`?

**Comment by bodewig** [comment]
Sounds good. I think I've set up the wiki so that anybody can change the pages, if you want to give it a try.

**Comment by Kerruba** [comment]
I will give a try, thanks :smile:

**Comment by Kerruba** [comment]
Actually, I was looking at the wiki and my suggestion sounds like a repetition of the content is now available. I think is then ok to close this issue as solved

**Comment by bodewig** [comment]
Fine with me. Thank you.
