### ISSUE TITLE
withComparaisonFormatter not implemented on DiffBuilder

### ISSUE THREAD

**Issue by math103** [xmlunit/xmlunit#51]
the method withComparaisonFormatter is not implemented in the DiffBuilder class but the user guide mention it. The user guide should be corrected until the method is really added.

**Comment by phbenisc** [comment]
Well,
this statement seems to be true. I also think an implementation would make sense.

DiffBuilder class:
https://github.com/xmlunit/xmlunit/blob/master/xmlunit-core/src/main/java/org/xmlunit/builder/DiffBuilder.java

DiffBuilder doc:
https://github.com/xmlunit/user-guide/wiki/DiffBuilder
(fluent API -> 7. withComparisonFormatter():

ComparisonFormatter class (interface):
https://github.com/xmlunit/xmlunit/blob/master/xmlunit-core/src/main/java/org/xmlunit/diff/ComparisonFormatter.java

default impl:
https://github.com/xmlunit/xmlunit/blob/master/xmlunit-core/src/main/java/org/xmlunit/diff/DefaultComparisonFormatter.java

**Comment by bodewig** [comment]
I agree it should be there - and probably on `CompareMatcher` as well.

**Comment by bodewig** [comment]
Implemented with 0259c3d - `CompareMatcher` already has the `withComparisonFormatter` method.

I'll close this issue once I've found time to update XMLUnit.NET

**Comment by bodewig** [comment]
fix ported to XMLUnit.NET
