### ISSUE TITLE
Port org.custommonkey.xmlunit.XMLAssert to v2 of xmlunit

### ISSUE THREAD

**Issue by mariusneo** [xmlunit/xmlunit#56]
With the release 2.0.0 of xmlunit the class org.custommonkey.xmlunit.XMLAssert is not anymore available.

Facility operations like : 
- assertXMLEqual
- assertXMLNotEqual
- assertXpathExists
- ... 

have to be written now by hand in the tests of each of the project where they are used.
It would make sense to have this class ported to a future minor release of xmlunit v2 library. 
If this makes sense not only for me, I could port the XMLAssert utility class (and its corresponding tests) from xmlunit-legacy to xmlunit-core library.

**Comment by bodewig** [comment]
`XMLAssert` is still available as part of the `xmlunit-legacy` artifact.

It is not suitable as for "pure" XMLUnit 2.x since it would introduce a dependency on JUnit.

**Comment by mariusneo** [comment]
Thanks for the heads up. While looking around I've noticed the xmlunit-matchers project and also the expressed need for new matchers (https://github.com/xmlunit/xmlunit/blame/master/HELP_WANTED.md). I'll contribute with new matchers that cover what XMLAssert was doing.

**Comment by bodewig** [comment]
This sounds great! The CompareMatcher should be doing what the equals and similar methods did, but there isn't anything for XPath, yet.
