### ISSUE TITLE
Different functionality in asserting XML equality between xmlunit-core and xmlunit-legacy

### ISSUE THREAD

**Issue by mariusneo** [xmlunit/xmlunit#57]
The pursose of this issue report is that I'd like to have a easy way to assert XML equality between the Strings : 
- `"<myRootElement></myRootElement>"`
- `"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><myRootElement></myRootElement>"
`
when using xmlunit-core / xmlunit-matchers.

Take the following test (with xmlunit-legacy) which runs successfully

```
        @Test
	public void demoXMLUnitLegacySuccess() throws Exception{
		assertXMLEqual("Invalid result", "<myRootElement></myRootElement>",
				"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><myRootElement></myRootElement>");
	}
```

And now take the following tests (based on xmlunit-core/xmlunit-matchers):

```
    @Test
    public void demoXMLUnitCoreFailure(){
        assertThat("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><myRootElement></myRootElement>",
                isSimilarTo("<myRootElement></myRootElement>"));
    }

    @Test
    public void demoXMLUnitCoreWorkaroundFailure(){
        Diff diffSimilar = DiffBuilder.compare("<myRootElement></myRootElement>")
                .withTest("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><myRootElement></myRootElement>")
                .withComparisonController(new ComparisonController() {
                    @Override
                    public boolean stopDiffing(Difference difference) {
                        if (ComparisonType.XML_STANDALONE.equals(difference.getComparison().getType()) ||
                                ComparisonType.XML_ENCODING.equals(difference.getComparison().getType()) ||
                                ComparisonType.XML_VERSION.equals(difference.getComparison().getType())){
                            return false;
                        }

                        return difference.getResult().ordinal() >= ComparisonResult.DIFFERENT.ordinal();
                    }
                })
                .checkForSimilar()
                .build();
        assertFalse("Differences: " + diffSimilar.toString(), diffSimilar.hasDifferences());
    }

    @Test
    public void demoXMLUnitCoreSuccess(){
        assertThat("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><myRootElement></myRootElement>",
                isSimilarTo("<myRootElement></myRootElement>"));
    }


```
After investigating in detail why do the tests fail I came across a few findings : 

- in the test demoXMLUnitCoreFailure I am using CompareMatcher's `isSimilarTo()` method, which is syntax sugar for building a `Diff` via `DiffBuilder` 
- in the test demoXMLUnitCoreWorkaroundFailure, I've tried to naively reproduce what was done in xmlunit-legacy with ComparisonController2ComparisonController in order to skip inequality issues produced by xml_standalone inequality (by default in xmlunit-core's DiffBuilder, the StopComparisonController is used). `DiffBuilder` sets also a `DifferenceListener` , which collects the differences found, so `diffSimilar.hasDifferences() `will return `true` causing the test to fail (in xmlunit-legacy there is only a `compListener` `IsBetweenDocumentNodeAndRootElement` used).

**Comment by bodewig** [comment]
The `xmlunit-legacy` project is supposed to be a drop-in replacement for XMLUnit 1.x. 2.x introduces a few new comparisons - like the ones that apply to the XML declaration and the legacy wrapper filters out those extra comparisons. In that sense different outcomes between legacy and the matcher are expected, and that's fine.

Rather than overriding the `ComparisonController` I'd suggest providing a different `DifferenceEvaluator` - see https://github.com/xmlunit/user-guide/wiki/DifferenceEvaluator . If been meaning to provide an easier way to construct new `DifferenceEvaluator`s for quite some time, I'll try to come up with something fluid.

**Comment by bodewig** [comment]
I think a `DifferenceEvaluator` like

```java
import static org.xmlunit.diff.ComparisonType.*;
import static org.xmlunit.diff.DifferenceEvaluators.*;

DifferenceEvaluator ev = chain(Default,
                                                  recordDifferencesAsEqual(XML_VERSION, XML_STANDALONE, XML_ENCODING));
```

using `recordDifferencesAsEqual` that I've just added should work. Could you please give it a try? I'll be pushing out a new SNAPSHOT build right now.

**Comment by bodewig** [comment]
I just realized I may need to fine tune this for the Similar and Error cases (to return EQUAL when it used to be EQUAL), but the `recordDifferencesAsEqual` method should work as it is.

**Comment by bodewig** [comment]
It's `downgradeDifferencesToEqual` now.

**Comment by mariusneo** [comment]
@bodewig thanks for the support on this one.

Indeed the rewritten test looks like this now : 


```
@Test
    public void demoXMLUnitCoreRewritten(){
        DifferenceEvaluator ev = chain(Default, downgradeDifferencesToEqual(XML_STANDALONE));
        assertThat("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><myRootElement></myRootElement>",
                isSimilarTo("<myRootElement></myRootElement>").withDifferenceEvaluator(ev));
    }
```


And it runs successfully.
:+1:  for the ellegant solution.
