### ISSUE TITLE
Difference functionality in asserting XML (with custom declaration) equality between xmlunit-core and xmlunit-legacy

### ISSUE THREAD

**Issue by mariusneo** [xmlunit/xmlunit#59]
Take the following test : 

```
@Test
    public void testXMLUnitCoreExtraDeclarationFailure() throws Exception{
        String control = "<?pi content?>" +
                "<root xmlns='namespace'>" +
                "<prefix:child xmlns:prefix='namespace2'>content</prefix:child>" +
                "</root>";
        String test = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<root xmlns=\"namespace\">" +
                "<prefix:child xmlns:prefix=\"namespace2\">content</prefix:child>" +
                "</root>";

        assertThat(test, isSimilarTo(control));
    }
```

NOTE in the control XML the presence of `<?pi content?>` declaration.
The test fails when being runned with xmlunit-core.

On the other hand with xmlunit-legacy it runs successfully :

```
    public void testXMLUnitLegacySuccess() throws Exception{
        String control = "<?pi content?>" +
                "<root xmlns='namespace'>" +
                "<prefix:child xmlns:prefix='namespace2'>content</prefix:child>" +
                "</root>";
        String test = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<root xmlns=\"namespace\">" +
                "<prefix:child xmlns:prefix=\"namespace2\">content</prefix:child>" +
                "</root>";

        assertXMLEqual(test, control);
    }
```

The stacktrace of the testcase above is : 

```
java.lang.AssertionError: 
Expected: Expected child nodelist length '2' but was '1' - comparing <root...> at / to <?xml version="1.0" encoding="UTF-8"?><root...> at /:
<root xmlns="namespace">
  ...
     but: result was: 
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="namespace">
```

What would be in this case the appropriate option to have the test done with xmlunit-core not taking into account the `CHILD_NODELIST_LENGTH` difference for the document node?

**Comment by mariusneo** [comment]
I came up with the following solution : 

```
@Test
    public void testXMLUnitCoreExtraDeclarationFailure() throws Exception{
        String control = "<?pi content?>" +
                "<root xmlns='namespace'>" +
                "<prefix:child xmlns:prefix='namespace2'>content</prefix:child>" +
                "</root>";
        String test = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<root xmlns=\"namespace\">" +
                "<prefix:child xmlns:prefix=\"namespace2\">content</prefix:child>" +
                "</root>";

        Predicate<Node> nodeFilter = new Predicate<Node>() {
            @Override
            public boolean test(Node n) {
                return n.getNodeType() != Node.DOCUMENT_TYPE_NODE && n.getNodeType() != Node.PROCESSING_INSTRUCTION_NODE;
            }
        };
        assertThat(test, isSimilarTo(control).withNodeFilter(nodeFilter));
    }
```

Please provide me feedback if there is some better one.

If you think my solution makes sense, does it make sense introducing an extra entry in the `org.xmlunit.diff.NodeFilters` ? (please close this ticket if you find it irrelevant)

:+1:  for the powerful plugin system built in the DOMDifferenceEngine class.

**Comment by bodewig** [comment]
In a more general setup there might be PIs inside the document itself. And you probably also want to ignore comments inside the document's prelude.

I've been thinking of adding an additional `DifferenceEvaluator` that mimics what the `swallowComparison` method in legacy's `NewDifferenceEngine` does, which might be a better fit than a `NodeFilter`. What do you think?

**Comment by mariusneo** [comment]
@bodewig I've just had a look over NewDifferenceEngine#swallowComparison method. There could be certainly added new DifferenceEvaluator preconfigured instances to DifferenceEvaluators  class.
Giving the API users the ability to easily customize DOMDifferenceEngine without having to write/invent on their own NodeFilter/DifferenceEvaluator  concrete implementations would help them to get the job (xml unit testing) done.

For custom scenarios where special implementations NodeFilter/DifferenceEvaluator the users can dig deeper in NodeFilters/DifferenceEvaluators or even DOMDifferenceEngine.

:+1:  for usability if you introduce this feature.

**Comment by bodewig** [comment]
I've added `ignorePrologDifferencesExceptDoctype` which does pretty much what XMLUnit 1.x did. I'll keep this issue open until I've managed to add a few notes about the prolog handling differences inside the user guide.

**Comment by bodewig** [comment]
documented: https://github.com/xmlunit/user-guide/wiki/Migrating-from-XMLUnit-1.x-to-2.x/_compare/959a896654f3b7861be53440b27787093a1ba650...6d840369c58ff33f120d01ce7f3c4d52094deeb5
