### ISSUE TITLE
XPathEngine#setNamespaceContext question

### ISSUE THREAD

**Issue by mariusneo** [xmlunit/xmlunit#60]
In the definition of the class org.xmlunit.xpath.XPathEngine I've found the following method 

```
/**
     * Establish a namespace context.
     *
     * @param prefix2Uri maps from prefix to namespace URI.
     */
    void setNamespaceContext(Map<String, String> prefix2Uri);
```

which takes a Map<String, String> and internally builds (along with a helper method) a namespace context out of it.

In the definition of org.custommonkey.xmlunit.XpathEngine interface (xmlunit-legacy) the namespace context setter looked like this : 

```
    /**
     * Establish a namespace context.
     */
    void setNamespaceContext(NamespaceContext ctx);
```

My question here is why was the change towards Map<String, String> from NamespaceContext parameter for the setter made during the migration from xmlunit 1.x to xmlunit 2.x ?
It seems to me that the previous setter was more appropriate for its purpose.

**Comment by bodewig** [comment]
Three reasons, not necessarily in that order:

* The 1.x version would have bound us to `javax.xml`, using a `Map` at least leaves the door open for other implementations.
* It is easier to create similar APIs for Java and .NET that way.
* `DifferenceEngine` needs a similar mechanism for prefixes inside the XPathContext and the `javax.xml` `NamespaceContext` doesn't feel right there.
