### ISSUE TITLE
hamcrest required library version

### ISSUE THREAD

**Issue by basisbit** [xmlunit/xmlunit#76]
What version of the hamcrest dependency is required for compiling and using xmlunit?
Compiling fails with current hamcrest 2 library because of missing BaseMatcher package,

**Comment by bodewig** [comment]
If you are compiling with Maven, it should download Hamcrest 1.3 - which is what the matchers depend on. It looks as if Hamcrest 2.0 was not compatible to 1.3 - which is fine with a new major version.

If there is any way to rewrite the matchers so they can be used with 1.3 and 2.0, then I'll be happy to lend a hand. Alternatively we could create separate matchers jars for Hamcrest 1.x (which is still widely used AFAICT, I've only vaguely been aware 2.0 existed) and 2.x - just as we do with NUnit constraints in XMLUnit.NET. In either case, I'd need help with the 2.0 compatible version.

**Comment by basisbit** [comment]
ok, thanks a lot for your fast reply and the great work you do in this project!
It worked perfectly with the hamcrest 1.3 core version.

**Comment by bodewig** [comment]
You're welcome.
