### ISSUE TITLE
change the control order in which nodes are pickde for compariosn

### ISSUE THREAD

**Issue by atreyee169** [xmlunit/xmlunit#85]
I am looking for a way to change the order in which a node is picked up for comparison.
For example,
control: `<root>
<a></a>
<b></b>
<c></c>
</root>`
test: `<root><a></a><b></b><c></c></root>`

I want the comparison to start from the <c> node of control rather than the <a> node. Please let me know if there is a library in xmlunit 2 for this requirement.

**Comment by bodewig** [comment]
I'm not sure what you mean by order here.

XMLUnit compares nodes in document order - and uses the NodeMatcher/ElementSelector to chose between siblings. So usually it would compare the `a`s and descend the subtree, then the `b`s and so on.

Are you asking to walk the `c` subtree before `a` and `b`? This might be possible by replacing `NodeMatcher` and simply returning the pairs in a different order. Not nice, but should work.

Why do you want to compare the `c`s first? Maybe there is a deeper reason and a different way to achieve that without major surgery.

**Comment by bodewig** [comment]
ping?

**Comment by dfev77** [comment]
sounds like he/she want to find the character index where the xml node starts, like the spaces would matter.
