### ISSUE TITLE
Not running combined with Saxon

### ISSUE THREAD

**Issue by maschhoff** [xmlunit/xmlunit#92]
Hey, I run into trouble after importing Saxon 9 HE.
The code works without importing the jar of Saxon. After importing it thows the exception.
It is only if I try to use ignoreWhitespace.
Any idea for a workaround. Or is this an issue?

Thanks for your help!

`    Diff diff_list = DiffBuilder.compare(Input.fromString(controlstr)).withTest(Input.fromString(teststr))
                .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))
                .checkForSimilar().**ignoreWhitespace**().ignoreComments()
                .withComparisonController(ComparisonControllers.Default)
                .build();
`

`java.lang.ClassCastException: net.sf.saxon.value.ObjectValue cannot be cast to net.sf.saxon.om.NodeInfo
	at net.sf.saxon.s9api.DocumentBuilder.wrap(DocumentBuilder.java:509)
	at net.sf.saxon.s9api.XsltTransformer.setSource(XsltTransformer.java:214)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:89)
	at org.xmlunit.transform.Transformation.transformTo(Transformation.java:186)
	at org.xmlunit.transform.Transformation.transformToDocument(Transformation.java:220)
	at org.xmlunit.input.CommentLessSource.<init>(CommentLessSource.java:45)
	at org.xmlunit.builder.DiffBuilder.wrap(DiffBuilder.java:389)
	at org.xmlunit.builder.DiffBuilder.build(DiffBuilder.java:368)
	at org.artdecor.TemplateDifference.compare(TemplateDifference.java:118)`

**Comment by bodewig** [comment]
I don't think this is related to XMLUnit at all, but more likely an issue with your setup.

XMLUnit really only used `javax.xml.transform` here and something inside of Saxon runs into an exception casting one Saxon class to another.

I don't really know enough about Saxon to provide any help, the Saxon support channels are probably the better place to ask.

Your stack-trace led me to http://www.saxonica.com/html/documentation/javadoc/net/sf/saxon/s9api/DocumentBuilder.html#wrap(java.lang.Object) which states

> To wrap nodes from other object models, such as DOM, the support module for the external object model must be on the class path and registered with the Saxon configuration. The support modules for DOM, JDOM, DOM4J and XOM are registered automatically if they can be found on the classpath.

Once you've used `ignoreWhitespace` you are dealing with a `DOMSource` (without it it is a `StreamSource`), maybe the "support module for DOM" is not on your CLASSPATH?

**Comment by RSN-IOP** [comment]
While it's a little late to the party, I thought I'd drop in that I'm having the same trouble as the original poster, and the support module is absolutely a dependency for the project. In my case I suspect the problem is using Saxon-HE, as mentioned [here](http://stackoverflow.com/questions/26913173/search-xml-using-xpath-with-jdom-jaxen-saxon), 'Sounds as if you're using Saxon-HE which doesn't come with JDOM2 support "out of the box"'

**Comment by bodewig** [comment]
I'll be more than happy to help but still think there isn't anything XMLUnit should be doing differently. We are certainly not using JDOM ourselves.

**Comment by jruillier** [comment]
I've solved the same issue by using :
```
System.setProperty("javax.xml.transform.TransformerFactory",
                "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");
```

**Comment by bodewig** [comment]
So you solved it by not using Saxon at all :-)

**Comment by keddie** [comment]
https://saxonica.plan.io/issues/3241

**Comment by bodewig** [comment]
Thanks @keddie looks as if Michael Kay has identified the problem as a bug in Saxon.

**Comment by bodewig** [comment]
I've just seen Michael has fixed it in Saxon and the fix will become available with the next maintenance releases. 

He also mentions a workaround

> Until the maintenance release comes out, you could try the workaround `setSource(new DOMSource(source.getNode()))`

which is a bit more difficult to translate to the original code of @maschhoff .

One thing you could do is move the `ignoreComments` parts to the `Input`s, this will make the XSLT transformation happen before whitespace is stripped, something like

```
Diff diff_list = DiffBuilder.compare(new CommentLessSource(Input.fromString(controlstr).build()))
    .withTest(new CommentLessSource(Input.fromString(teststr)))
    .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))
    .checkForSimilar().ignoreWhitespace() 
    .withComparisonController(ComparisonControllers.Default)
    .build();
```

**Comment by mkrivan** [comment]
Unfortunately bodewig's suggestion is not working see the following simple example below
`
   private static void case1() {
        String controlstr = "<root>hello</root>";
        String teststr = "<root>hello</root>";
        Diff diff = DiffBuilder.compare(new CommentLessSource(Input.fromString(controlstr).build()))
                .withTest(new CommentLessSource(Input.fromString(teststr).build()))
                .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))
                .checkForSimilar().ignoreWhitespace()
                .withComparisonController(ComparisonControllers.Default)
                .build();
        System.out.println(diff.hasDifferences());
    }

    private static void case2() {
        String controlstr = "<root>hello</root>";
        String teststr = "<root>hello</root>";
        Diff diff = DiffBuilder.compare(Input.fromString(controlstr))
                .withTest(Input.fromString(teststr))
                .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))
                .checkForSimilar().ignoreWhitespace()
                .ignoreComments()
                .withComparisonController(ComparisonControllers.Default)
                .build();
        System.out.println(diff.hasDifferences());
    }
`

The result is exactly the same:

run:
Warning at char 6 in template/@match on line 1 column 122 
  XTDE0160: An error occurred matching pattern {( element() | text() | comment() |
  processing-instruction() )[not(error("XPath 1.0 Compatibility Mode is not available in
  this configuration"))]}: XPath 1.0 Compatibility Mode is not available in this configuration
Warning at char 6 in template/@match on line 1 column 122 
  XTDE0160: An error occurred matching pattern {( element() | text() | comment() |
  processing-instruction() )[not(error("XPath 1.0 Compatibility Mode is not available in
  this configuration"))]}: XPath 1.0 Compatibility Mode is not available in this configuration
Error 
  org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node
  where it is not permitted. 
Exception in thread "main" org.xmlunit.XMLUnitException: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
	at org.xmlunit.transform.Transformation.transformTo(Transformation.java:190)
	at org.xmlunit.transform.Transformation.transformToDocument(Transformation.java:220)
	at org.xmlunit.input.CommentLessSource.<init>(CommentLessSource.java:45)
	at hu.telekom.reflex.util.Any.case1(Any.java:20)
	at hu.telekom.reflex.util.Any.main(Any.java:43)
Caused by: net.sf.saxon.trans.XPathException: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
	at net.sf.saxon.dom.DOMWriter.characters(DOMWriter.java:222)
	at net.sf.saxon.event.ProxyReceiver.characters(ProxyReceiver.java:190)
	at net.sf.saxon.event.ComplexContentOutputter.characters(ComplexContentOutputter.java:277)
	at net.sf.saxon.trans.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:75)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:477)
	at net.sf.saxon.trans.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:66)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:477)
	at net.sf.saxon.trans.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:66)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:477)
	at net.sf.saxon.Controller.transformDocument(Controller.java:2389)
	at net.sf.saxon.Controller.transform(Controller.java:1953)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:589)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:73)
	at org.xmlunit.transform.Transformation.transformTo(Transformation.java:186)
	... 4 more
Caused by: org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
	at com.sun.org.apache.xerces.internal.dom.ParentNode.internalInsertBefore(ParentNode.java:361)
	at com.sun.org.apache.xerces.internal.dom.ParentNode.insertBefore(ParentNode.java:288)
	at com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.insertBefore(CoreDocumentImpl.java:447)
	at com.sun.org.apache.xerces.internal.dom.NodeImpl.appendChild(NodeImpl.java:237)
	at net.sf.saxon.dom.DOMWriter.characters(DOMWriter.java:219)
	... 17 more

The ignoreWhitespace is working with Saxon 9.8.0-2

**Comment by mkrivan** [comment]
As an interim solution I am using simple regex removal `xmlString.replaceAll("(?s)<!--.*?-->", "")` before comparison.

**Comment by bodewig** [comment]
I currently haven't got Saxon around to test it easily, does something like this work?

```java
private static void case1() {
    String controlstr = "<root>hello</root>";
    String teststr = "<root>hello</root>";
    Document control = Convert.toDocument(new CommentLessSource(Input.fromString(controlStr)));
    Document test = Convert.toDocument(new CommentLessSource(Input.fromString(testStr)));
    Diff diff = DiffBuilder.compare(Input.fromDocument(control).build())
            .withTest(Input.fromDocument(test).build())
            .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))
            .checkForSimilar().ignoreWhitespace()
            .withComparisonController(ComparisonControllers.Default)
            .build();
    System.out.println(diff.hasDifferences());
}
```

This is the verbatim translation of Michael Kay's suggestion.

**Comment by mkrivan** [comment]
Thx for your reply and suggestion :-)
I had to modify a little the code pattern to compile:

    public class Any {

        private static void case1() {
            String controlStr = "<root>hello</root>";
            String testStr = "<root>hello</root>";
            Document control = Convert.toDocument(new CommentLessSource(Input.fromString(controlStr).build()));
            Document test = Convert.toDocument(new CommentLessSource(Input.fromString(testStr).build()));
            // Document control = Convert.toDocument(Input.fromString(controlStr).build());
            // Document test = Convert.toDocument(Input.fromString(testStr).build());
            Diff diff = DiffBuilder.compare(Input.fromDocument(control).build())
                    .withTest(Input.fromDocument(test).build())
                    .withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.byNameAndText))
                    .checkForSimilar().ignoreWhitespace()
                    .withComparisonController(ComparisonControllers.Default)
                    .build();
            System.out.println(diff.hasDifferences());
        }

        public static void main(String[] args) {
            case1();
        }
    }

But anyhow at this line

    Document control = Convert.toDocument(new CommentLessSource(Input.fromString(controlStr).build()));

the exception still raises. It looks the CommentLessSource constructor works exactly the same way as ignoreComments(). The underlying layer should be the same I think.

If I change the control and test construction (without CommentLessSource see the commented rows above) it works (but without eliminating the comments of course).

**Comment by bodewig** [comment]
Ahh, I see. So I'm afraid then there isn't much we can do except for waiting for new Saxon releases that incorporate the fix for https://saxonica.plan.io/issues/3241

A regex solution may work in specific cases but is not suitable as a general solution, unfortunately.

**Comment by mkrivan** [comment]
Many thanks for your feedback and support. And you are right the regex is only a partial interim solution. That is why I would be very happy if this kind of interference can be eliminated between this two libraries :-)

**Comment by mkrivan** [comment]
I have upgraded just now to xmlunit-2.4.0 and saxon-HE 9.7.0-19 and the ignoreComments() method works again perfect. Many thanks for the development.

**Comment by bodewig** [comment]
Thank you for reporting success, I'm glad it works!

Saxon must have done all the work as XMLUnit didn't change anything in that area :-)

**Comment by mkrivan** [comment]
I'm glad too :-)

**Comment by stoussaint** [comment]
I do just face the same issue. I'm not sure it is only Saxon related, but XSLT 1.0 support related.
The issue here comes from org.xmlunit.input.CommentLessSource which declare the following stylesheet 

`<stylesheet version="1.0" xmlns="http://www.w3.org/1999/XSL/Transform">
  <template match="node()[not(self::comment())]|@*"><copy>
    <apply-templates select="node()[not(self::comment())]|@*"/>
  </copy></template>
</stylesheet>`

A single change of version="1.0" to version="2.0" fix the issue.

If 1.0 support is still expected for XmlUnit2, maybe should will be able to detect the target execution version to be actually picked ?

As a work around I use the DiffBuilder as suggested with a CommentLessSourceXsl2 wrapper.

**Comment by bodewig** [comment]
@stoussaint you are correct. But this is a different issue that we will need to address. Could you please open a separate ticket for this?

Unfortunately I don't think we can unconditionally change the version to 2.0 as people may be using older transformers (XMLUnit for Java still targets Java6). We can't simply remove the attribute, either, see also #47.

**Comment by stoussaint** [comment]
Thanks for reply. I just create [https://github.com/xmlunit/xmlunit/issues/99](#99)

I was thinking about not mention the version at all... to bad it don't work either.

I do understand that XmlUnit still need to support legacy engine, but shouldn't the Matcher part preferably deal with "most recent engine" ?
