### ISSUE TITLE
Better difference description when using ElementSelectors.byNameAndAttributes

### ISSUE THREAD

**Issue by maciekwiso** [xmlunit/xmlunit#93]
It'd be useful if difference description for a node that used node matcher with specific attributes, like this:
.withNodeMatcher(new DefaultNodeMatcher(
                        ElementSelectors.conditionalBuilder()
                                .whenElementIsNamed("SomeElem").thenUse(ElementSelectors.byNameAndAttributes("Attr1", "Attr2"))
                                .elseUse(ElementSelectors.byName).build()
								
would also have those attributes' values, like this:
Expected child 'SomeElem' but was 'null' - comparing <SomeElem  Attr1="theValue1" Attr2="theValue2"...> at /RootElem[1]/SomeElem[16] to <NULL> (DIFFERENT)

**Comment by bodewig** [comment]
The output you see is the output of `DefaultComparisonFormatter`, it is always possible to provide a custom one  - see `withComparisonFormatter`. The `Difference`s themselves hold all the information they need.

I don't think it will be possible to derive all "interesting" information from an arbitrary `ElementSelector` so in the end you would have to customize the output yourself.

**Comment by maciekwiso** [comment]
I tried creating my implementation of DefaultComparisonFormatter.
That solution would be ok, if methods in that class would be protected not private.
I had to copy the whole class to my project and then tweak it to my needs.
I still think it'd be useful to be able to somehow specify in an easy way format of the diff output (like showing values of attributes used for matching the nodes with diff).

**Comment by bodewig** [comment]
I'm certainly open for improvements.

`DefaultComparisonFormatter` really seems to be more closed than it needs to be, I agree. It will take a little bit more of thought to identify what should become protected, what final and what may need to be made non-static in order to allow subclasses to provide useful extensions.

**Comment by bodewig** [comment]
@maciekwiso could you please take a look at 5f0dbe4 to see whether this provides all the hooks you would have needed? If so I'll port it over to XMLUnit.NET and cut new releases.

Thanks!

**Comment by maciekwiso** [comment]
Looks great. Thanks.
