### ISSUE TITLE
Detecting extra namespace declaration

### ISSUE THREAD

**Issue by zheng-wang** [xmlunit/xmlunit#96]
Hello. I am using XMLUnit Java 2.4.0. 

I have one control XML 
    
    <NS1:Root xmlns:NS1="http://www.example.com"/>

and two test XMLs 

    <NS1:Root xmlns:NS1="http://www.example.com" xmlns:NS2="http://www.mycompany.com"/>

    <NS1:Root xmlns:NS1="http://www.example.com" xmlns="http://www.mycompany.com"/>

Below code outputs `[identical]`.

    Diff diff = DiffBuilder.compare(control).withTest(test).build();
    System.out.println(diff);

Is there any way in XMLUnit to determine that the control XML and the test XMLs are different? I'd like to use it in unit testing to ensure the code under test does not generate garbage namespace declarations.

**Comment by bodewig** [comment]
XMLUnit deliberately ignores all namespace related attributes, for example the actual prefix used for a namespace or where it is declared doesn't matter during comparison at all as it is not relevant for the XML to be the same. The same is true for any unused "extra namespace" defined, it doesn't make any difference for the XML infoset at all.

Your two XML elements are identical (at least when read by a proper XML parser) as would they be identical to 

```
<foo:Root xmlns:foo='http://www.example.com'/>
```

or 

```
<Root xmlns='http://www.example.com'/>
```

Why do you want XMLUnit to state they'd not be identical?

**Comment by zheng-wang** [comment]
Thanks. I think my requirement consists of two parts. One is to compare the text XML with the control XML to ensure they are identical as to the infoset. The other is to ensure the text XML does not have garbage/unused namespace declarations (one of our clients likes to see XML to be neat as well as containing required infoset).

The second part of my requirement seems not very popular, and I myself also feel it not intuitive for XMLUnit to help address it. I'll probably need to write some custom Java code to only detect garbage/unused namespace declarations in an XML. So closing this issue now.
