### ISSUE TITLE
Retrieving an immediate child element or parent element

### ISSUE THREAD

**Issue by Abhi1186** [xmlunit/xmlunit#97]
Hi,
I have two xml files that i am comparing.Here are the sample xmls -attached
[testxmls.txt](https://github.com/xmlunit/xmlunit/files/1207657/testxmls.txt)

Below is the gist of code that i am using -
Diff myDiff2 = DiffBuilder.compare(doc3).withTest(doc4).withNodeMatcher(new DefaultNodeMatcher(ElementSelectors.conditionalBuilder()
                .whenElementIsNamed("Test").
                thenUse(ElementSelectors.byXPath("./name", ElementSelectors.byNameAndText))
                .whenElementIsNamed("name").
                thenUse(ElementSelectors.byNameAndText)
                .whenElementIsNamed("value").
                thenUse(ElementSelectors.byXPath("./value", ElementSelectors.byNameAndText))
                .elseUse(ElementSelectors.byName).build())).checkForSimilar().ignoreWhitespace().build();

Iterable<Difference> differences = myDiff2.getDifferences();
    	 DefaultComparisonFormatter formatter = new DefaultComparisonFormatter();
    	 
    
    	for (Difference difference : differences) {
System.out.println(""+difference.getComparison());
}

It works great and i am able to get the comparison that i need.However sample output gives something like below -
Expected child 'Test' but was 'null' - comparing <Test...>at /app[1]/NVTest[1]/Test[1] to <NULL>

While comparing a more bigger and complex xml,I will need the exact node path of the difference and its value and not just ' /app[1]/NVTest[1]/Test[1]' because in real-time it may have  /app[1]/NVTest[1]/Test[300] and i would need its child element i.e either name or value in this case to identify where the difference is.
Is it possible for me to get the difference more precisely i.e how do i know the exact position of difference using its child elements?

I have already tried using below solutions but somehow i am unable to get desired results .....maybe there is a simpler solution that i am missing.

1st way -

XPath xpath = XPathFactory.newInstance().newXPath();
    		//getting instance of xPath
    		XPathExpression expr =  xpath.compile("/app[1]/NVTest[1]/Test[1]");
    		Object result = expr.evaluate(doc4, XPathConstants.NODESET);
    		NodeList nodes = (NodeList) result;
    		 for (int i = 0; i < nodes.getLength(); i++) {
    		     System.out.println(nodes.item(i).getNodeValue());
    		}

2nd way -
Checking in source file and also target file - sample code

JAXPXPathEngine je=new JAXPXPathEngine();
    	File file3 = new File("D:/test.xml");
		Source source = Input.fromFile(file3).build();
    	Iterable<Node> n=je.selectNodes("/app[1]/NVTest[1]/Test[1]);
		
		
		
		for(Node n1 : n)
		{
			System.out.println("child element"+n1.getChildNodes());
		}
    

3rd way - 
 Node node =difference.getComparison().getControlDetails().getTarget();
    		 
    		 System.out.println("child element"+node.getFirstChild().getNodeName());

Can you help in getting the difffernce more precisely by making use of the child elements/nodes?

**Comment by Abhi1186** [comment]
xml1 -
<app name="Testerapp" xmlns="xyz">
    <NVTest name="test">
        <Test>
            <name>ABC</name>
            <value>abc1</value>
        </Test>
        <Test>
            <name>ABC/TESLA/name</name>
            <value>Hello</value>
        </Test>
        <Test>
            <name>ABC/TESLA/victory</name>
            <value>Help</value>
        </Test>
        <Test>
            <name>ABC/code/path</name>
            <value>/abc/work/in/</value>
        </Test>
</app>

**Comment by bodewig** [comment]
Each `Difference` holds the `Comparison` which in turn holds references to the things it has compared. The XPath you see is `difference.getComparison().getControlDetails().getXPath()`. The "control details" also provide you with the `Node` itself as `getTarget` so you don't need to use any XPath engine to resolve it. I think this should give you enough context to output whatever information you need to locate the element later.

The alternative is to provide a `ComparisonFormatter` of your own that emits the extra information you need (again based on the `Node` rather than the XPath of the `Detail`.

**Comment by Abhi1186** [comment]
Thank you.
difference.getComparison().getTestDetails().getTarget().getTextContent() did the job perfectly ! :)

**Comment by bodewig** [comment]
Glad I could help.
